### ISSUE TITLE
Reverse Engineering: Enable pluralization/singularization when scaffolding a model from a database

### ISSUE THREAD

**Issue by abelepereira** [aspnet/EntityFramework#3060] opened 2015-09-08 20:37 UTC
Database scaffolding has no pluralization service and the entity models are generated mapping the exact name of database objects. My suggestion is to enable this pluralization through a DI service that could be overridden at the `ef` CLI like this:

```
dnx ef dbcontext scaffold "Server=myserver;Database=Foo;user id=me;password=pwd" EntityFramework.SqlServer --use-pluralization "MyAssembly.PlurarizationService, MyAssembly"
```

And on Razor templates this could be exposed as:

``` csharp
...
@:namespace @Model.Namespace
@:{
@:    public class  @PluralizationService.Singularize(Model.EntityType.Name)
@:    {
...
```

I think the default service could be the one shipped with EF6 (`System.Data.Entity.Design.PluralizationServices.PluralizationService`)

**Comment by anpete** [comment] 2015-09-08 21:04
We could consider this inflector (which I wrote a long time ago) - https://github.com/srkirkland/Inflector

It is very lightweight (single class, ~200 loc). MIT license.

**Comment by rowanmiller** [comment] 2015-09-09 19:03
**EF Team Triage:** Pluralization caused a lot of issues in EF6, where even a simple bug fix can break existing models. For that reason we are not going to have pluralization on by default in EF7. That said, we are going to have a simple way to get the model before it is passed to code generators so that you can run any logic over the model to manipulate it. Pluralization would be exactly the kind of thing that should be simple to do (and a good way to verify our work).

This ability was tracked as part of some larger work, but I opened https://github.com/aspnet/EntityFramework/issues/3077 to track this piece.

**Comment by divega** [comment] 2016-02-03 02:32
Reopening this issue to follow up on the discussion we had in triage. We would like to support pluralization for collection navigation properties and singularization of tables names in scaffolding (which is what the original request was about). We need to discuss if this is really part of the potentially more complex extensibility feature described in #3077 or something we have out of the box.

**Comment by gdoron** [comment] 2016-02-11 20:48
@divega I think it is a feature almost all EF < 7 users used so it will be a shame not to have it in EF 7.
But it should be an extension method on DbContext whether it should use the pluralization strategy or not.

**Comment by divega** [comment] 2016-02-11 21:21
@gdoron this issue is only about using pluralization/singularization in scaffolding, i.e. in the process of reverse engineering a database into an EF Core model. 

Past experience has demonstrated that using pluralization to automatically create table names based on the entity types is not a good idea: it means any time you fix a bug on then pluralizer it becomes a breaking change for the runtime, so we are not planning to do that. One idea we have talked about is to create a convention that uses the name of the DbSet property on the derived DbContext to name the table. Would that work for you?

**Comment by gdoron** [comment] 2016-02-11 21:42
@divega it most definitely would and I think it's the best solutions (even if the pluralizer had no bugs at all) because this is the way I use it in the code, I expect it to be the same in the DB.

Even if for some weird reason someone has a class name completely different than the DbSet propery name, e.g. Post class with DbSet<Post> Comments. I would still say that the DbSet name should be that table name and in this case the table name should be Comments.

**Comment by rowanmiller** [comment] 2016-02-11 22:27
@gdoron stick this code at the start of `OnModelCreating` and it will give you what you are after :smile: 

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    var dbSets = GetType().GetProperties()
        .Where(p => p.PropertyType.Name == "DbSet`1")
        .Select(p => new
        {
            PropertyName = p.Name,
            EntityType = p.PropertyType.GenericTypeArguments.Single()
        })
        .ToArray();

    foreach (var type in modelBuilder.Model.GetEntityTypes())
    {
        var dbset = dbSets.SingleOrDefault(s => s.EntityType == type.ClrType);
        if(dbset != null)
        {
            type.Relational().TableName = dbset.PropertyName;
        }

    }

    // Other configuration code...
}
```

**Comment by gdoron** [comment] 2016-02-11 23:02
Thanks @rowanmiller, in case someone else finds it helpful, I wrapped it in an extension method:

    public static void UseDbSetNamesAsTableNames(this DbContext dbContext, ModelBuilder modelBuilder)
    {

        var dbSets = dbContext.GetType().GetProperties()
            .Where(p => p.PropertyType.Name == "DbSet`1")
            .Select(p => new
                                {
                                    PropertyName = p.Name,
                                    EntityType = p.PropertyType.GenericTypeArguments.Single()
                                })
            .ToArray();

        foreach (var type in modelBuilder.Model.GetEntityTypes())
        {
            var dbset = dbSets.SingleOrDefault(s => s.EntityType == type.ClrType);
            if (dbset != null)
            {
                type.Relational().TableName = dbset.PropertyName;
            }

        }
    }
And used it like this:

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);
        this.UseDbSetNamesAsTableNames(builder);

But I get an error says cannot find the object "Posts"

I checked what EF is trying to execute with `dnx ef migrations script 20160211201857_second -o c:\temp\rename.txt` and  [pasted it here](http://pastebin.com/CpJnuvpP).
EF is using the new name Posts before it was renamed, so that's a bug.

Since it's a just a test application I created for a lecture I will present in the office next week I don't mind using  `dnx ef database 0` and start all over again. 
But out of curiosity what should I do if it is a real production application? fiddle with the `__EFMigrationsHistory` table?

Thank you very much Rowan, I really like what you did with EF 7 and in ASP.NET 5 in general!

**Comment by smitpatel** [comment] 2016-02-11 23:12
Renaming issue is dupe of #3990 
Its ordering issue. You can manually edit generated migration to use older name in operations before the rename operation is executed. Sql script is generated from migration file so once migration file is modified it will generate correct script. (i.e. using older names before rename operation is called)

**Comment by gdoron** [comment] 2016-02-12 00:35
@rowanmiller  Should be noted that Type.GetProperties is not available on dnxcore.
Are there alternatives?

**Comment by smitpatel** [comment] 2016-02-12 00:51
@gdoron - try using `type.GetRuntimeProperties()`

**Comment by divega** [comment] 2016-02-12 01:24
@gdoron You should probably use code like what we have in `DbSetFinder` to accomplish this (or even use our internal type in the extension for now). 

Anyway, in the interest of keeping this work item actionable for the scaffolding part, I have created a separate issue for using the DbSet property names for tables names without having to write any extra code: https://github.com/aspnet/EntityFramework/issues/4540. 

Consider creating a new issue if you hit any bugs that aren't covered by existing issues.

**Comment by rowanmiller** [comment] 2016-07-01 20:01
Talk with @anpete about using a 3rd party pluralizer

**Comment by rowanmiller** [comment] 2016-07-29 23:07
Currently planned for 1.1 - see https://blogs.msdn.microsoft.com/dotnet/2016/07/29/entity-framework-core-1-1-plans/ for details.

**Comment by ammar-haider** [comment] 2016-11-20 09:28
Is it resolved in latest 1.1? I do not find a switch.

**Comment by jwooley** [comment] 2017-02-09 03:14
@rowanmiller Any update to this? It didn't make 1.1 and doesn't appear to be on the [published roadmap](http://bit.ly/efcoreroadmap).

**Comment by rowanmiller** [comment] 2017-02-10 18:58
@jwooley it didn't end up fitting into 1.1. I just hacked together something that does this by replacing some of the services that reverse engineering uses. I'll turn it into a blog post over the next few days and reply back here with it.

**Comment by rowanmiller** [comment] 2017-02-13 17:50
@jwooley here is a solution that replaces internal services to generate pluralized/singularized code https://romiller.com/2017/02/10/ef-core-1-1-pluralization-in-reverse-engineer/

**Comment by rowanmiller** [comment] 2017-02-16 23:00
Clearing up to discuss whether we want to have pluralization baked into the default experience, or whether we are ok with just having the hook to wire in your own.

**Comment by divega** [comment] 2017-02-19 02:36
@maumar @rowanmiller just to make sure, was this closed intentionally or was there something else we wanted to do?

**Comment by maumar** [comment] 2017-02-19 02:42
@divega accident I think I goofed something up with that last commit

**Comment by rowanmiller** [comment] 2017-02-22 18:26
Discussed and decided that we are ok with just having the hook for the moment. We'd like to avoid taking a dependency on a pluralization service. We may reconsider in the future if we see folks having issues with using a third party service.

**Closed by rowanmiller** 2017-02-22 18:26 UTC
Labels: closed-fixed, type-enhancement

**Comment by chumakov-ilya** [comment] 2017-03-08 11:30
> https://romiller.com/2017/02/10/ef-core-1-1-pluralization-in-reverse-engineer/

@rowanmiller, is this solution designed to be provider-dependent? At least it depends on `SqlServerScaffoldingModelFactory`. It works fine with SQL Server 2014 but falls with PostgreSQL and latest Npgsql provider.

**Comment by SidShetye** [comment] 2018-07-05 17:20
What's the definitive final guide on singularization of entity classes and pluralization of collections? Documentation is [empty](https://docs.microsoft.com/en-us/ef/core/managing-schemas/scaffolding) (as of now) and across the last 3 years there are multiple offered solutions on stackoverflow and github; esp as EF Core has evolved (e.g. dbsets now take the table names i.e. pluralized)

For some background, we're looking at EF Core 2.1 from EF 6. We don't trust migration wizardry anywhere close to our QA or production databases, so use proper SQL scripts to manage DB schema and then reverse engineering/scaffold the model back into code. IMHO since pluralization of collections and singularization of entity classes is standard practice, the default out-of-box product experience should address.

**Comment by ErikEJ** [comment] 2018-07-05 17:55
@SidShetye "EF Core Power Tools" reverse engineer has pluralization

**Comment by SidShetye** [comment] 2018-07-10 17:17
@ErikEJ that looks great. We used `IDesignTimeServices` and `IPluralizer` with a custom class that pluralized and singularized strings (i.e. acting as in Inflector). 

My request is have this on by default; as an out-of-box feature that makes EF Core even better. It's literally a few hours of engineering time but adds so much value for folks following the reverse engineering workflow, that the value/invest fraction should be worth it (obv. the EF Core team knows their constraints best).

Plus there are multiple well-licensed implementations ([here](https://stackoverflow.com/a/47410837/862563) and [here](https://github.com/srkirkland/Inflector/blob/master/Inflector/Inflector.cs) and even your own one [here](https://github.com/ErikEJ/EFCorePowerTools/blob/master/src/GUI/ReverseEngineer20/ReverseEngineer/Pluralizer.cs) :) ) to accelerate this.

**Comment by bricelam** [comment] 2018-07-12 19:29
We talked about adding one as part of #11160. Not sure what we decided...

See also [Pluralization in EF Core](https://www.bricelam.net/2018/03/02/efcore-pluralization.html).
