### ISSUE TITLE
"DNX commands" still in resource file

### ISSUE THREAD

**Issue by bruceyclee** [aspnet/EntityFramework#5212] opened 2016-04-28 22:26 UTC
Small issue in src/Microsoft.EntityFrameworkCore.Tools.Core/Properties/ToolsCoreStrings.resx, there are some sentences still indicating "DNX commands". 

For example,  <value>More than one DbContext was found. Specify which one to use. Use the '-Context' parameter for PowerShell commands and the '--context' parameter for DNX commands.</value>

Maybe you want to change them to "Dotnet commands"

**Comment by natemcmaster** [comment] 2016-04-28 23:51
Looks like we also need to update the error for MigrationsAssemblyMismatch. This doesn't apply to CLI commands

**Comment by Eilon** [comment] 2016-05-03 18:35
@rowanmiller @natemcmaster any update on this? If we can't get it in today we'll likely need to move it out to RTM.

**Comment by natemcmaster** [comment] 2016-05-03 18:37
I believe this was fixed in https://github.com/aspnet/EntityFramework/pull/5229. @rowanmiller did this go into release branch?

**Comment by natemcmaster** [comment] 2016-05-03 19:12
Confirmed. The fix is in release. I didn't find DNX any other strings/resources.

**Comment by Eilon** [comment] 2016-05-03 19:41
Thanks!

**Comment by natemcmaster** [comment] 2016-05-03 23:56
Reopened. The fix broke the build. https://github.com/aspnet/EntityFramework/commit/2af1137acca85f9f53c8344bb813739ad3e727b0

**Comment by rowanmiller** [comment] 2016-05-04 05:20
The fix is in the release branch so closing this issue. I'm taking care of the merge to dev but build.cmd is broken for me at the moment, so I'll track the merge elsewhere.

**Closed by rowanmiller** 2016-05-04 05:20 UTC
Labels: bug, pri0
