### ISSUE TITLE
Query provider has problem processing MemberBinding expression that contains initilization of subclass

### ISSUE THREAD

**Issue by rayao** [aspnet/EntityFramework#1404] opened 2015-01-14 11:00 UTC
With following code, when evaluating the IQueryable returned by SelectExpandBinder.Select, ArgumentException thrown said that:
Property 'System.String Name' is not defined for type 'System.Web.OData.Query.Expressions.PropertyContainer'

    class SelectExpandBinder
    {
        public static IQueryable<SelectAllAndExpand<Contacts>> Select(IQueryable<Contacts> This)
        {
            return This.Select(o => new SelectAllAndExpand<Contacts>()
            {
                Instance = o,
                Container = new PropertyContainer.NamedProperty<Users>()
                {
                    Name = "User2",
                    Value = o.User2,
                },
            });
        }

        public class SelectAllAndExpand<T>
        {
            public T Instance
            {
                get;
                set;
            }

            public PropertyContainer Container
            {
                get;
                set;
            }
        }
    }

    internal abstract class PropertyContainer
    {
        public class NamedProperty<T> : PropertyContainer
        {
            public string Name
            {
                get;
                set;
            }
            public T Value
            {
                get;
                set;
            }
            public bool AutoSelected
            {
                get;
                set;
            }
            public virtual object GetValue()
            {
                return this.Value;
            }
        }
    }

And stack is:
   at System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
   at System.Linq.Expressions.Expression.MakeMemberAccess(Expression expression, MemberInfo member)
   at Remotion.Linq.Clauses.ExpressionTreeVisitors.AccessorFindingExpressionTreeVisitor.GetMemberAccessExpression(Expression input, MemberInfo member)
   at Remotion.Linq.Clauses.ExpressionTreeVisitors.AccessorFindingExpressionTreeVisitor.CheckAndVisitMemberAssignment(MemberInfo member, Expression expression)
   at Remotion.Linq.Clauses.ExpressionTreeVisitors.AccessorFindingExpressionTreeVisitor.VisitMemberAssignment(MemberAssignment memberAssigment)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMemberBinding(MemberBinding memberBinding)
   at Remotion.Linq.Clauses.ExpressionTreeVisitors.AccessorFindingExpressionTreeVisitor.VisitMemberBinding(MemberBinding memberBinding)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitList[T](ReadOnlyCollection`1 list, Func`2 visitMethod)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMemberBindingList(ReadOnlyCollection`1 expressions)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMemberInitExpression(MemberInitExpression expression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
   at Remotion.Linq.Clauses.ExpressionTreeVisitors.AccessorFindingExpressionTreeVisitor.VisitExpression(Expression expression)
   at Remotion.Linq.Clauses.ExpressionTreeVisitors.AccessorFindingExpressionTreeVisitor.CheckAndVisitMemberAssignment(MemberInfo member, Expression expression)
   at Remotion.Linq.Clauses.ExpressionTreeVisitors.AccessorFindingExpressionTreeVisitor.VisitMemberAssignment(MemberAssignment memberAssigment)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMemberBinding(MemberBinding memberBinding)
   at Remotion.Linq.Clauses.ExpressionTreeVisitors.AccessorFindingExpressionTreeVisitor.VisitMemberBinding(MemberBinding memberBinding)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitList[T](ReadOnlyCollection`1 list, Func`2 visitMethod)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMemberBindingList(ReadOnlyCollection`1 expressions)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMemberInitExpression(MemberInitExpression expression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
   at Remotion.Linq.Clauses.ExpressionTreeVisitors.AccessorFindingExpressionTreeVisitor.VisitExpression(Expression expression)
   at Remotion.Linq.Clauses.ExpressionTreeVisitors.AccessorFindingExpressionTreeVisitor.FindAccessorLambda(Expression searchedExpression, Expression fullExpression, ParameterExpression inputParameter)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel, Type resultType)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Relational.RelationalDataStore.Query[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryExecutor.ExecuteCollection[T](QueryModel queryModel)
   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteCollectionQueryModel[T](QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor)
   at Remotion.Linq.QueryProviderBase.Execute(Expression expression)
   at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at EF7Test.Program.Main(String[] args) in c:\Users\rayao\Documents\Visual Studio 2013\Projects\DumpExternalUser\EF7Test\Program.cs:line 302
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by rayao** [comment] 2015-01-14 11:01
Version is 7.0.0-rc1-11953

**Comment by rayao** [comment] 2015-01-14 11:24
A simple change can work around this bug, like this:
        public class SelectAllAndExpand<T>
        {
            public T Instance
            {
                get;
                set;
            }

            //public PropertyContainer Container
            public PropertyContainer.NamedProperty<Users> Container
            {
                get;
                set;
            }
        }

But we can't change it since it's not in our control.
It seems a bug in Remotion.Linq?

**Comment by rayao** [comment] 2015-01-14 11:26
It seems a bug in Remotion.Linq?

A simple change can work around this bug, like this:

 public class SelectAllAndExpand
 {
 public T Instance
 {
 get;
 set;
 }
        //public PropertyContainer Container
        public PropertyContainer.NamedProperty<Users> Container
        {
            get;
            set;
        }
    }


But we can't actually change this way since the real code is not in our control.

**Comment by rayao** [comment] 2015-01-14 11:53
It seems a bug in Remotion.Linq? Or something wrong in IncludeNavigations?

A simple change can work around this bug, like this:

public class SelectAllAndExpand
 {
 public T Instance
 {
 get;
 set;
 }
 //public PropertyContainer Container
 public PropertyContainer.NamedProperty Container
 {
 get;
 set;
 }
 }

But we can't actually change this way since the real code is not in our control.

**Comment by rayao** [comment] 2015-01-16 17:00
Without an Include call, the same exception thrown, just different stack.

   at System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
   at System.Linq.Expressions.Expression.MakeMemberAccess(Expression expression, MemberInfo member)
   at Remotion.Linq.Clauses.ExpressionTreeVisitors.AccessorFindingExpressionTreeVisitor.GetMemberAccessExpression(Expression input, MemberInfo member)
   at Remotion.Linq.Clauses.ExpressionTreeVisitors.AccessorFindingExpressionTreeVisitor.CheckAndVisitMemberAssignment(MemberInfo member, Expression expression)
   at Remotion.Linq.Clauses.ExpressionTreeVisitors.AccessorFindingExpressionTreeVisitor.VisitMemberAssignment(MemberAssignment memberAssigment)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMemberBinding(MemberBinding memberBinding)
   at Remotion.Linq.Clauses.ExpressionTreeVisitors.AccessorFindingExpressionTreeVisitor.VisitMemberBinding(MemberBinding memberBinding)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitList[T](ReadOnlyCollection`1 list, Func`2 visitMethod)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMemberBindingList(ReadOnlyCollection`1 expressions)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMemberInitExpression(MemberInitExpression expression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
   at Remotion.Linq.Clauses.ExpressionTreeVisitors.AccessorFindingExpressionTreeVisitor.VisitExpression(Expression expression)
   at Remotion.Linq.Clauses.ExpressionTreeVisitors.AccessorFindingExpressionTreeVisitor.CheckAndVisitMemberAssignment(MemberInfo member, Expression expression)
   at Remotion.Linq.Clauses.ExpressionTreeVisitors.AccessorFindingExpressionTreeVisitor.VisitMemberAssignment(MemberAssignment memberAssigment)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMemberBinding(MemberBinding memberBinding)
   at Remotion.Linq.Clauses.ExpressionTreeVisitors.AccessorFindingExpressionTreeVisitor.VisitMemberBinding(MemberBinding memberBinding)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitList[T](ReadOnlyCollection`1 list, Func`2 visitMethod)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMemberBindingList(ReadOnlyCollection`1 expressions)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMemberInitExpression(MemberInitExpression expression)
   at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
   at Remotion.Linq.Clauses.ExpressionTreeVisitors.AccessorFindingExpressionTreeVisitor.VisitExpression(Expression expression)
   at Remotion.Linq.Clauses.ExpressionTreeVisitors.AccessorFindingExpressionTreeVisitor.FindAccessorLambda(Expression searchedExpression, Expression fullExpression, ParameterExpression inputParameter)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.<>c__DisplayClass34_0`1.<GetEntityAccessors>b__0(QuerySourceReferenceExpression qsre)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.GetEntityAccessors[TResult](IEnumerable`1 querySourceReferenceExpressions, Expression selector)

**Comment by rayao** [comment] 2015-01-16 17:09
I highly suspect that in EF code the result type is made wrong, before calling into Remotion.Linq
Perhaps for a MemberInit expression like:
            Container = new PropertyContainer.NamedProperty<Users>()
            {
                Name = "User2",
                Value = o.User2,
            },
The code assume the property type (type of Container here) is identical to the NewExpression type. But actually NewExpression could be of a subclass type.

**Comment by rayao** [comment] 2015-01-21 06:48
Sorry I forgot to mention in this code snippet only Contacts and Users are entity types, others are just pure CLR types that aren't mapped to entity data.

**Comment by jasper-186** [comment] 2015-01-24 01:54
So I've been digging through the whole stack and looks like the wires get crossed about half way down the Remotion.Linq Stack. what ends up happening is that, at least for me, when the remotion lib gets the bindings for the  Property Container Expression, it returns the Contents of the Container, not the Members associated with the class. Thus when the Remotion.Linq attempts to get the values of the Members it looks at the members of the System.Web.OData.Query.Expressions.PropertyContainer Class and not the contents of the class. I'm still trying to find a solution for it, but Im hoping that this helps clarify whats happening. Also Remotion.Linq Source code is here:

https://github.com/re-motion/Relinq

in case you want to take a look, heads up though im using the futures branch, in order to get Azure Table Support, and am fully expecting more bugs then this

**Comment by rayao** [comment] 2015-01-30 04:58
I possibly found the root cause and fix, in class Remotion.Linq.Clauses.ExpressionTreeVisitors.AccessorFindingExpressionTreeVisitor, the method GetMemberAccessExpression should check if the input expression is the member’s declaring type (or subclass of declaring type), and do a conversion when necessary.
But I don’t know how to submit fix to relinq, could anyone help?

    private Expression GetMemberAccessExpression (Expression input, MemberInfo member)
    {
// This is the fix part <<
        if (!member.DeclaringType.GetTypeInfo().IsAssignableFrom(input.Type.GetTypeInfo()))
        {
            input = Expression.Convert(input, member.DeclaringType);
        }
// >> This is the fix part

      var methodInfo = member as MethodInfo;
      if (methodInfo != null)
        return Expression.Call (input, methodInfo);
      else
        return Expression.MakeMemberAccess (input, member);
    }

**Comment by jasper-186** [comment] 2015-01-30 05:13
Did some research and came across these couple of pages:

https://relinq.codeplex.com/team/view

https://github.com/re-motion/Relinq/network/members

I would guess that you can do one of three(?) things to get their attention:

try pushing it to the github repo
Contact one of the devs from the pages above, and ask them the proper way to enter code
use mentions to get the devs to see these comments(see https://guides.github.com/features/mastering-markdown)

it looks like the users :

Michaelketting
stefan-wenig

seem to be the primary devs for the whole remotion organization, so they might be one of the first to be contacted about the bug/fix

**Comment by divega** [comment] 2015-01-30 06:26
Thanks for investigating! We have worked with the Relinq team. I am sure we'll find a way.

**Comment by rayao** [comment] 2015-01-30 06:44
That will be great! Thank you Diego.
And thank you jasper-186 for attention and advices.

**Comment by anpete** [comment] 2015-01-30 16:52
@rayao 

You can connect with the relinq developers here: https://groups.google.com/forum/#!forum/re-motion-dev

**Comment by MichaelKetting** [comment] 2015-01-31 09:43
Hi Guys!

Thanks for bringing this to our attention over at the list (https://groups.google.com/forum/#!topic/re-motion-dev/Xt13qzt-MM4)

Best regards, Michael

**Comment by anpete** [comment] 2015-01-31 17:57
Thanks @MichaelKetting.

**Comment by MichaelKetting** [comment] 2015-02-08 20:40
@anpete I've reproduced the issue and released a fix with v2.0.0-alpha-002 of re-linq.

Best regards, Michael

**Comment by rowanmiller** [comment] 2015-02-10 18:49
@MichaelKetting - Thanks for being so proactive about fixing this... always a pleasure doing business with you guys :smile:

**Comment by divega** [comment] 2015-02-11 21:46
@anpete I had a chat with @rowanmiller and we agreed we can upgrade EF to depend on the new version of Relinq. I am assigning this to you as it is the remaining actionable part of getting this bug fixed.

**Comment by rayao** [comment] 2015-02-12 07:41
Thank you guys! I knew from the start that this is a rare case and few people would step into and might be a low priority issue, but you guys took action so quickly, which is a good favor to me.
Thanks and regards!

**Closed** 2015-02-12 22:46 UTC
Labels: bug, pri0
