### ISSUE TITLE
InvalidCastException on Select Clause

### ISSUE THREAD

**Issue by a99cl208** [aspnet/EntityFramework#2732] opened 2015-07-28 18:39 UTC
Hi,

Using EF7 beta 6 over WebApi2/OData4, I get a cast error doing a simple $select=Id on my entity set.

Here is the error message (approximative translation) :

```
Object cannot be cast from 'Microsoft.Data.Entity.Query.QueryResultScope`1[MySoft.MyEntity]' to 'Microsoft.Data.Entity.Query.QueryResultScope`1[Microsoft.Data.Entity.Storage.ValueBuffer]'.
```

Here is the stack trace

```
stacktrace=   à Microsoft.Data.Entity.Query.QueryResultScope._GetResult[TResult](IQuerySource querySource)
   à lambda_method(Closure , QueryResultScope )
   à System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   à Microsoft.Data.Entity.Query.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   à System.Web.OData.Formatter.Serialization.ODataFeedSerializer.WriteFeed(IEnumerable enumerable, IEdmTypeReference feedType, ODataWriter writer, ODataSerializerContext writeContext)
   à System.Web.OData.Formatter.Serialization.ODataFeedSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
   à System.Web.OData.Formatter.Serialization.ODataFeedSerializer.WriteObject(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext)
   à System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content, HttpContentHeaders contentHeaders)
   à System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à System.Web.Http.Owin.HttpMessageHandlerAdapter.<BufferResponseContentAsync>d__13.MoveNext()
```

and here is the Debug view of the queryable expression :

```
.Call System.Linq.Queryable.Select(
    .Constant<Microsoft.Data.Entity.Query.EntityQueryable`1[MySoft.MyEntity]>(Microsoft.Data.Entity.Query.EntityQueryable`1[MySoft.MyEntity]),
    '(.Lambda #Lambda1<System.Func`2[MySoft.MyEntity,System.Web.OData.Query.Expressions.SelectExpandBinder+SelectSome`1[MySoft.MyEntity]]>))

.Lambda #Lambda1<System.Func`2[MySoft.MyEntity,System.Web.OData.Query.Expressions.SelectExpandBinder+SelectSome`1[MySoft.MyEntity]]>(MySoft.MyEntity $var1)
{
    .New System.Web.OData.Query.Expressions.SelectExpandBinder+SelectSome`1[MySoft.MyEntity](){
        ModelID = "90ec004f-6f1c-4209-9626-44bb977a14f0",
        Container = .New System.Web.OData.Query.Expressions.PropertyContainer+NamedProperty`1[System.Nullable`1[System.Int32]](){
            Name = "Id",
            Value = .If ($var1 == null) {
                null
            } .Else {
                (System.Nullable`1[System.Int32])$var1.Id
            }
        }
    }
}
```

Regards.

**Comment by rowanmiller** [comment] 2015-07-30 18:37
Hey,

Could you provide some code that we can use to reproduce the issue so that we can investigate?

~Rowan

**Comment by a99cl208** [comment] 2015-07-30 22:03
Hi Rowan,

Sample here : https://onedrive.live.com/redir?resid=D8BBA8E0EB927AC8!61043&authkey=!AG-V67J7aH6kSes&ithint=folder%2ccs

To reproduce the bug :
- Run dnx . ef migration apply on project
- Add an entry on the Customer table in the newly created local db
- Start website and browse for http://localhost:1200/odata/Customers?$select=Id,FirstName

Could you let me know when you've downloader the sample, so i can remove it from one drive?

Thank you.

**Comment by maumar** [comment] 2015-07-31 18:37
@a99cl208 i have downloaded the sample, feel free to take it down

**Comment by mikary** [comment] 2016-04-18 19:54
Ran the example and was able to reproduce with the beta6 packages. This appears to be a very basic OData scenario and we have some working examples on desktop, but this isn't currently supported on core.
Closing this issue as the underlying issue in EF appears to be resolved.

**Closed by mikary** 2016-04-18 19:54 UTC
Labels: bug, pri0

**Comment by mikary** [comment] 2016-04-20 23:27
Note: based on the query plan, it looks like regression testing for this scenario is covered by the test `GearsOfWarQueryTestBase.Select_null_propagation_negative1` added in 616886d
