### ISSUE TITLE
dbContext.<Entity>.Update() is creating new records

### ISSUE THREAD

**Issue by DiegoZoracKy** [aspnet/EntityFramework#3890] opened 2015-11-25 17:08 UTC
When i do something like:
```javascript
var e = new Entity();
e.Id = 100;
e.Name = "Name 100";
dbContext.Entities.Update(e);
dbContext.SaveChanges();
```
a new record is created.

Is this the correct behaviour?

**Comment by rowanmiller** [comment] 2015-11-30 19:28
@DiegoZoracKy it should attempt to update an existing record, not insert a new one. Can you share a full code listing that we can use to reproduce the issue? (i.e. the code for `Entity` and your context)

**Comment by DiegoZoracKy** [comment] 2015-11-30 19:53
@rowanmiller i've created something simple to show the case. See:

```javascript
using Microsoft.AspNet.Mvc;
using System.Linq;
using Microsoft.Data.Entity;
using Newtonsoft.Json.Linq;
		
public class TestUpdate
{
	public int Id { get; set; }
	public string Name { get; set; }
}

public class MyContext : DbContext
{
	public DbSet<TestUpdate> TestUpdates { get; set; }		
}			

[Route("api/[controller]")]
public class TestController : Controller
{
	private MyContext dbContext;

	public TestController(MyContext context)
	{
		dbContext = context;
	}

	[HttpGet]
	public IActionResult Get()
	{
		var e = new TestUpdate();
		e.Name = "Name 100";
		dbContext.TestUpdates.Update(e);
		dbContext.SaveChanges();

		return new ObjectResult(dbContext.TestUpdates.AsNoTracking().ToList());
	}
}	
```

Everytime you hit api/test (GET) a new record will be saved.

**Comment by DiegoZoracKy** [comment] 2015-12-01 20:55
@rowanmiller  i've found what it seems to be another weird behavior on `Update` method. Let's suppose that in my previous example, `AnotherClass` exists on the project and it makes a reference to `TestUpdate`, like:

```javascript
	public class AnotherClass
	{
    	public int Id { get; set; }
    	public virtual List<TestUpdate> TestUpdate { get; set; }
	}
```

Thinking about SQLServer, this will create a column `AnotherClassId` on the `TestUpdate` Table, with a reference to records on `AnotherClass`, right?

The problem is that when i do `.Update` on `TestUpdate`, this reference is being set to `NULL`.

**Comment by rowanmiller** [comment] 2015-12-01 22:19
@DiegoZoracKy regarding the first issue you reported...

This situation is arising because `TestUpdate.Id` is assigned a value of 0. The fact that we are implying this means it is added (even though you called `Update`) is a bug and we will fix it. That said, do you actually have an existing row in the database with an Id of zero... or is that just a coding error where you are not setting the key property? 

If having a key value of zero is a legitimate requirement, then you can workaround this until we fix the bug by explicitly setting the state (rather than calling `Update`).

```
dbContext.Entry(e).State = EntityState.Modified;
```

**Comment by rowanmiller** [comment] 2015-12-01 22:20
@DiegoZoracKy can you open a new issue for the second case you mentioned (and include code that demonstrates the issue again).

**Comment by DiegoZoracKy** [comment] 2015-12-01 22:46
@rowanmillerNo, id 0 is not a requirement of my software.  I've created this simple example for you to see that the Update method is creating new records. Good that it is a Bug and not its correct behavior.

I will create a new issue for sure, within some hours. This current issue is something easy to be avoided, just bringing a performance penalty by checking if the record exists for real before update it. But this last one can be a huge problem.

**Comment by rowanmiller** [comment] 2015-12-01 22:55
@DiegoZoracKy just to be clear, it only inserts a row if the key is set to zero. If it is set to anything else then it will correctly update it.

i.e. this code

```
var e = new TestUpdate();
e.Name = "Name 100";
e.Id = 5;
dbContext.TestUpdates.Update(e);
dbContext.SaveChanges();
```

Produces this SQL

```
exec sp_executesql N'SET NOCOUNT OFF;
UPDATE [TestUpdate] SET [Name] = @p1
WHERE [Id] = @p0;
SELECT @@ROWCOUNT;
',N'@p0 int,@p1 nvarchar(4000)',@p0=5,@p1=N'Name 100'
```

Not saying that it's not a bug... but just that you'll only see the insert behavior if you are attempting to update an entity with a key set to zero.

**Comment by DiegoZoracKy** [comment] 2015-12-02 01:50
@rowanmiller i just tried setting a value to `Id`, like that:

```javascript
var e = new TestUpdate();
        e.Id = 100;
        e.Name = "Name 100";
        dbContext.TestUpdates.Update(e);
        dbContext.SaveChanges();
```

And a new record was created. But for this test i used inMemory (`EntityFramework.InMemory: 7.0.0-rc1-final`) instead of SQL Server.

**Comment by DiegoZoracKy** [comment] 2015-12-02 03:18
@rowanmiller And, a new issue about the reference being lost during `Update`, that i commented above: #3948

**Comment by rowanmiller** [comment] 2015-12-02 19:07
@DiegoZoracKy I was able to reproduce that issue with InMemory. It's different from the original bug on this issue (which is already fixed), so I opened https://github.com/aspnet/EntityFramework/issues/3953 for the new issue.

**Comment by DiegoZoracKy** [comment] 2015-12-02 19:11
Thanks @rowanmiller. I will track this new issue.

**Comment by rowanmiller** [comment] 2015-12-03 19:03
Re-opening as we still need this to track the issue where the entity being passed to Update is marked as added if it has no key value assigned.

**Closed** 2016-01-26 21:18 UTC
Labels: bug, pri0
