### ISSUE TITLE
EntityQueryExecutor.AsyncExecuteCollection throws null ref exception

### ISSUE THREAD

**Issue by egorpavlikhin** [aspnet/EntityFramework#1428] opened 2015-01-19 18:43 UTC
NullReferenceException: Object reference not set to an instance of an object.
    Microsoft.Data.Entity.Query.EntityQueryExecutor.AsyncExecuteCollection[T](QueryModel queryModel, CancellationToken cancellationToken)
    Microsoft.Data.Entity.Query.EntityQueryProvider.AsyncQuery[T](Expression expression)
    Microsoft.Data.Entity.Query.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
    System.Linq.AsyncEnumerable.Aggregate[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, Func`2 resultSelector, CancellationToken cancellationToken)
    System.Linq.AsyncEnumerable.Aggregate[TSource,TAccumulate](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, CancellationToken cancellationToken)
    System.Linq.AsyncEnumerable.ToList[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
    System.Linq.QueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
    System.Linq.QueryableExtensions.ToListAsync[TSource](IQueryable`1 source)
    Microsoft.AspNet.Identity.EntityFramework.UserStore`4.<GetRolesAsync>d__34.MoveNext()

Calling code in aspnet/Identity

    var query = from userRole in UserRoles
                     join role in Roles on userRole.RoleId equals role.Id
                     where userRole.UserId.Equals(userId)
                     select role.Name;
         return await query.ToListAsync();

**Comment by egorpavlikhin** [comment] 2015-01-20 16:43
Same happens when trying to get user logins.

    at Microsoft.Data.Entity.Query.EntityQueryExecutor.AsyncExecuteCollection[T](QueryModel queryModel, CancellationToken cancellationToken)
    at Microsoft.Data.Entity.Query.EntityQueryProvider.AsyncQuery[T](Expression expression)
    at Microsoft.Data.Entity.Query.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
    at System.Linq.AsyncEnumerable.Aggregate[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, Func`2 resultSelector, CancellationToken cancellationToken)
    at System.Linq.AsyncEnumerable.Aggregate[TSource,TAccumulate](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, CancellationToken cancellationToken)
    at System.Linq.AsyncEnumerable.ToList[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
    at System.Linq.QueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
    at Microsoft.AspNet.Identity.EntityFramework.UserStore`4.<GetLoginsAsync>d__52.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
    at Microsoft.AspNet.Identity.UserManager`1.<GetLoginsAsync>d__93.MoveNext()

**Comment by egorpavlikhin** [comment] 2015-01-21 16:52
I'm running under IIS Express if that helps.

**Comment by maumar** [comment] 2015-02-13 02:20
@egorpavlikhin I'm unable to reproduce this in my environment. Which package version are you using (and which VS?).

**Comment by ExistentialEnso** [comment] 2015-05-03 00:31
I got this with both EF7 beta3 and beta4, both running in IIS express through VS 2015 and after deploying to a webserver.

I think it has something to do with the fact I'm trying to use StructureMap as a DI container.

Strangely enough, I can fix it locally by switching to the commit before adding StructureMap, building, switching back to latest, and building, and it works again for a few more builds (before the cycle repeats).

**Comment by ExistentialEnso** [comment] 2015-05-03 01:58
Just fixed it by adding this to the StructureMap container configuration:

c.For<IUserStore<ApplicationUser>>().Singleton().Use(new UserStore<ApplicationUser>(new ApplicationDbContext()));

**Comment by maumar** [comment] 2015-08-19 21:30
Can't reproduce the issue based on provided information, closing

**Closed by maumar** 2015-08-19 21:30 UTC
Labels: bug, pri0
