### ISSUE TITLE
Query: ArgumentNullException when using ternary operator with null comparison in the test expression

### ISSUE THREAD

**Issue by Caskia** [aspnet/EntityFramework#9223] opened 2017-07-20 10:57 UTC
Hi,
   When use ternary operator in a linq statement, then throw ArgumentNullException.

#### Step to reproduce

- Event.cs
```
    [Table("Events")]
    public class Event : Entity<long,>
    {
        public string Name { get; set; }

        public ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
    }
```

- Ticket.cs
```
    [Table("Tickets")]
    public class Ticket : Entity<long,>
    {
        public Event Event { get; set; }
        public long EventId { get; set; }
        public string Name { get; set; }
    }
```

- Linq
```
            var eventQuery = from evnt in dbContext.Events
                             join ticket in dbContext.Tickets
                             on evnt.Id equals ticket.EventId
                             into ets
                             from et in ets.DefaultIfEmpty()
                             select new
                             {
                                 Event = evnt,
                                 IsDisplay = (et == null ? (true) : (et.Id < 1))
                             };
            var events = await eventQuery.Where(e => e.IsDisplay).Select(e => e.Event).ToListAsync();
```

#### Further technical details
EF Core version: 1.1.2
Database Provider: Pomelo.EntityFrameworkCore.MySql
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by ajcvickers** [comment] 2017-07-20 16:24
@Caskia Can you post the full stack trace from the exception?

**Comment by Caskia** [comment] 2017-07-21 07:30
#### StackTrace
```
   在 System.Linq.Expressions.Expression.RequiresCanRead(Expression expression, String paramName)
   在 System.Linq.Expressions.Expression.AndAlso(Expression left, Expression right, MethodInfo method)
   在 Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitConditional(ConditionalExpression expression)
   在 System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   在 Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
   在 Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   在 System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   在 System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   在 System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   在 System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   在 Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitNew(NewExpression expression)
   在 System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   在 Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
   在 Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   在 Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression node)
   在 Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   在 Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   在 Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   在 Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   在 Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   在 Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   在 Microsoft.EntityFrameworkCore.Storage.Database.CompileAsyncQuery[TResult](QueryModel queryModel)
   在 Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database)
   在 Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass21_0`1.<CompileAsyncQuery>b__0()
   在 Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   在 Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddAsyncQuery[TResult](Object cacheKey, Func`1 compiler)
   在 Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQuery[TResult](Expression query)
   在 Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   在 Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   在 Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   在 Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.CountAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   在 Sparxo.Platform.Application.Merchants.MerchantFacebookAppService.<GetMerchantEventsByPageIdAsync>d__9.MoveNext()
```

**Comment by maumar** [comment] 2017-07-21 21:07
bug was introduced in 10f74f9db2b09adba693286cb11a2d70d2929958 - we try to optimize conditionals with logical iftrue/iffalse but the logic around it is not robust enough - we can return null from Invert(...) method which throws the exception seen in the bug

**Comment by ajcvickers** [comment] 2017-07-21 21:20
@maumar Do you know if it is a regression?

**Comment by maumar** [comment] 2017-07-24 18:01
Fixed in 64db1a41b774c4079338b9c09c275fdade12d4ff

**Closed by maumar** 2017-07-24 18:01 UTC
Labels: type-bug

**Comment by rguerreiro** [comment] 2018-04-24 18:32
I'm getting this error only when testing properties are boolean. Here's an example:
```
var query = from person in Db.Persons
                    join sr in (
                        from serviceReport in Db.ServiceReports
                        where serviceReport.ServiceDate == currentServiceDate
                        select serviceReport
                    ) on person.Id equals sr.PersonId into serviceReports
                    from serviceReport in serviceReports.DefaultIfEmpty()
                    where person.Removed == false
                    select new ServiceReportViewModel
                    {
                        PersonId = person.Id,
                        PersonName = person.DisplayName,
                        // the line below works fine. PersonStatusId is an int?
                        PersonStatusId = serviceReport == null ? person.PersonStatusId : serviceReport.PersonStatusId,
                        // the line below throws the exception if not commented. Auxiliary is a boolean
                        //Auxiliary = serviceReport == null ? person.Auxiliary : serviceReport.Auxiliary,
                        Gender = person.Gender
                    };

return await query.ToListAsync();
```

I'm using Microsoft.EntityFrameworkCore.Sqlite 2.0.2

**Comment by ajcvickers** [comment] 2018-04-24 19:07
@rguerreiro Can you test with the [latest 2.1 preview](https://blogs.msdn.microsoft.com/dotnet/2018/04/11/announcing-entity-framework-core-2-1-preview-2/)? (If using ASP.NET Core, then [install the .NET Core 2.1 preview2 SDK](https://blogs.msdn.microsoft.com/webdev/2018/04/12/asp-net-core-2-1-0-preview2-now-available/) instead of updating NuGet packages. If the issue is still present, then please file a new issue including a runnable project/solution or complete code listing that reproduces what you are seeing.

**Comment by rguerreiro** [comment] 2018-04-24 21:38
@maumar @ajcvickers thanks for the feedback. I'll try to update to preview 2 but it won't be possible immediately because I also need to install VS preview and that is something which I do not have the time, at the moment. Whenever I'm able to do it, I'll follow with a comment in here.

**Comment by rguerreiro** [comment] 2018-05-25 10:54
Finally was able to test and I can confirm that is fixed. Thanks for your work
