### ISSUE TITLE
Query: Translate DateTime.Month/Day/Year etc.

### ISSUE THREAD

**Issue by kennywangjin** [aspnet/EntityFramework#4582] opened 2016-02-17 07:58 UTC
I want to filter database records:
item.PurchDate.Year==2016&&item.TransactionType==PCTransactionType.Purchase (PCTransactionType is type of Enum)
when I check the log, it shows that these two conditions could not be executed in database server and must be evaluated locally.
Does EF7 support these kind of filtering?

**Comment by gdoron** [comment] 2016-02-17 10:06
@kennywangjin enum is supported so I guess the problem is with date.
As a temporary workaround, you could use:

    var from = new DateTime(2016,1,1,0,0,0);
    var to = new DateTime(2017,1,1,0,0,0);
    ...
    item.PurchDate >= from && item.PurchDate < to && 
    item.TransactionType == PCTransactionType.Purchase

**Comment by maumar** [comment] 2016-05-16 17:50
fixed in c4776ac7fc24cdca6a64051f8e32377c1015b1d5

**Closed by maumar** 2016-05-16 17:50 UTC
Labels: enhancement, pri0, up-for-grabs
