### ISSUE TITLE
Modeling an entity that has multiple foreign keys in EF7

### ISSUE THREAD

**Issue by rajajhansi** [aspnet/EntityFramework#2234] opened 2015-05-20 00:58 UTC
I have a table named Favorites with the fields MemberId, PostId and TopicId that are technically foreign keys pointing to the ID fields of the tables: Members, Posts and Topics. In SQL Server, they are not modeled as Foreign Keys but just as fields. When I reverse engineered that  database, EF7 generated the following C# POCO class for Favorites:
```
public class Favorite  
 {
        public Guid Id { get; set; }
        public DateTime DateCreated { get; set; }
        public Guid MemberId { get; set; }
        public Guid PostId { get; set; }
        public Guid TopicId { get; set; }
} 
```
It looks like I have to introduce the virtual navigation properties for Member, Post and Topic to load them for use inside the UI that uses Favorite class. If I introduce the navigation properties myself, then I'd assume that I need to define the Foreign Key mapping in OnModelCreating() of DbContext, right?

Whereas for other tables where there were FKs defined explicitly in SQL Server, reverse engineered POCO generated a navigation property for each foreign key field like:
```
public class LocaleStringResource
    {
        public Guid Id { get; set; }
        public Guid Language_Id { get; set; }
        public Guid LocaleResourceKey_Id { get; set; }
        public string ResourceValue { get; set; }

        public virtual Language Language { get; set; }
        public virtual LocaleResourceKey LocaleResourceKey { get; set; }
    }
```
Language_Id and LocaleResourceKey_Id are FKs and hence the reverse engineered DbContext generated the following code in OnModelCreating method:

```
 modelBuilder.Entity<Language>(entity =>
            {
                entity.Property(e => e.LanguageCulture).Required();

                entity.Property(e => e.Name).Required();

                entity.Property(e => e.RightToLeft).Required();
            });

            modelBuilder.Entity<LocaleResourceKey>(entity =>
            {
                entity.Property(e => e.DateAdded).Required();

                entity.Property(e => e.Name).Required();
            });

            modelBuilder.Entity<LocaleStringResource>(entity =>
            {
                entity.Property(e => e.Language_Id).Required();

                entity.Property(e => e.LocaleResourceKey_Id).Required();

                entity.Property(e => e.ResourceValue).Required();

                entity.Reference(d => d.Language).InverseCollection(p => p.LocaleStringResources).ForeignKey(d => d.Language_Id);

                entity.Reference(d => d.LocaleResourceKey).InverseCollection(p => p.LocaleStringResources).ForeignKey(d => d.LocaleResourceKey_Id);
            });
```

Running a LINQ query like this: 
```
var results = _context.LocaleStringResource
                                .Include(x => x.Language)
                                .Include(x => x.LocaleResourceKey)
                                .Where(x => x.Language.Id == languageId).ToList();
```
throws:
 An exception of type 'System.InvalidOperationException' occurred in mscorlib.dll but was not handled in user code

Additional information: Sequence contains more than one element

**Comment by divega** [comment] 2015-05-20 01:39
Thanks for reporting this. At first glance reverse engineering is behaving as designed. 

The issue with the query could be #325 which is a known limitation at this stage, but I can't tell for sure. @maumar can you take a

**Comment by divega** [comment] 2015-05-20 01:48
#1543 seems to be a better match but addressing it could be part of addressing #325.

**Comment by rajajhansi** [comment] 2015-05-20 01:51
@divega, I looked at both the issues #1543 and #325. Looks like it fails even before it generates the SQL statements because I don't see anything in SQL Profiler.

**Comment by rajajhansi** [comment] 2015-05-20 02:22
The same query runs just fine in EF6.X.

**Comment by rowanmiller** [comment] 2015-05-20 18:12
@anpete probably a dupe of #1543 but leaving open so we can verify when that is fixed

**Comment by rajajhansi** [comment] 2015-05-20 20:43
@rowanmiller, I should have paid attention to the warning you gave on ado.net blog about not using it on production go live apps but was worried about using EF6 with ASP.NET5. It is a bit of annoyance to connect the new configuration json with EF6 and also having to keep the EF6 references onto a separate VNext class library and add that class library as a project reference to my ASP.NET5 web application. But, that is much better than a preview version of EF7 failing on .Include() etc.

**Comment by rowanmiller** [comment] 2015-05-20 21:29
@rajajhansi the warning against production use would apply as much to ASP.NET 5 as it does to EF7... so if you are using ASP.NET 5 then I think EF7 would be the logical choice. Using EF6 is possible... but it's not ideal (as you already mentioned).

**Comment by dzolnjan** [comment] 2015-06-04 07:56
I've just got same issue. I've noticed that querying directly by exposed key works.

    public class Dummy 
    {
        public int Id { get; set; }
        public int CreatedById { get; set; }
        public User CreatedBy { get; set; }
    }

.Where(x => x.CreatedBy.Id == id)    <<<  same error

.Where(x => x.CreatedById == id)    <<<   works

**Comment by rowanmiller** [comment] 2015-06-04 16:34
@dzolnjan yep that is because translation of navigation properties isn't implemented yet (https://github.com/aspnet/EntityFramework/issues/325). We're just starting work on that now.

**Comment by rowanmiller** [comment] 2015-09-17 21:14
Nav prop translation is now implemented and these scenarios work

**Closed by rowanmiller** 2015-09-17 21:14 UTC
Labels: bug, pri0
