### ISSUE TITLE
Multiple includes leads to invalid query

### ISSUE THREAD

**Issue by grandchamp** [aspnet/EntityFramework#1841] opened 2015-03-17 19:37 UTC
Version: 7.0.0-beta3
I can't test it at nigthly builds.

Models
```
    public class Motocicleta
    {
        public int Id { get; set; }
        public string Modelo { get; set; }

        public int FabricanteId { get; set; }
        public Fabricante Fabricante { get; set; }
    }

    public class Telefone
    {
        public int Id { get; set; }

        public int PerfilId { get; set; }
        public Perfil Perfil { get; set; }

		[RegularExpression(@"^(\([0-9]{2}\))\s([9]{1})?([0-9]{4})-([0-9]{4})$")]
		public string Numero { get; set; }

        public int Tipo { get; set; }
    }

    public class UsuarioBloqueado
    {
        public int ApplicationUserId { get; set; }
        public ApplicationUser ApplicationUser { get; set; }

        public int BlockedId { get; set; }
        public ApplicationUser Blocked { get; set; }
    }

    public class Perfil
    {
        public int Id { get; set; }

        public int ApplicationUserId { get; set; }
        public virtual ApplicationUser ApplicationUser { get; set; }
        ...
        ...
        public int MotocicletaId { get; set; }
        public Motocicleta Motocicleta { get; set; }

        public ICollection<Telefone> Telefones { get; set; }
    }

    public class ApplicationUser : IdentityUser<int>
    {
        ...
        public ICollection<UsuarioBloqueado> UsuariosBloqueados { get; set; }
        ...
    }
```

Query
```
_db.Perfis.Include(x => x.Motocicleta)
                             .Include(x => x.Telefones)
                             .Include(x => x.ApplicationUser).ThenInclude(x => x.UsuariosBloqueados)
                             .SingleOrDefault(x => x.ApplicationUserId == id);
```

That generates 
```
exec sp_executesql N'SELECT TOP(@p0) [x].[ApplicationUserId], [x].[DataRegistro], [x].[Descricao], [x].[Id], 
[x].[ImagemPerfil], [x].[MotocicletaId], [x].[Nome],
[a].[AccessFailedCount], [a].[ConcurrencyStamp], [a].[Email], [a].[EmailConfirmed], 
[a].[Id], [a].[LockoutEnabled], [a].[LockoutEnd], [a].[NormalizedEmail], 
[a].[NormalizedUserName], [a].[PasswordHash], [a].[PerfilId], [a].[PhoneNumber], 
[a].[PhoneNumberConfirmed], [a].[SecurityStamp], [a].[TwoFactorEnabled], [a].[UserName], 
[m].[FabricanteId], [m].[Id], [m].[Modelo]
FROM [Perfil] AS [x]
INNER JOIN [AspNetUsers] AS [a] ON [x].[ApplicationUserId] = [a].[Id]
INNER JOIN [Motocicleta] AS [m] ON [x].[MotocicletaId] = [m].[Id]
WHERE [x].[ApplicationUserId] = @p0
ORDER BY [x].[Id], [a].[Id] AS [Id0]',N'@p0 int',@p0=2
go
```

And leads to
```
Msg 156, Level 15, State 1, Line 12
Incorrect syntax near the keyword 'AS'.
```

If i cut the line `.Include(x => x.ApplicationUser).ThenInclude(x => x.UsuariosBloqueados)` it works ok.

**Comment by maumar** [comment] 2015-03-20 20:09
duplicate of https://github.com/aspnet/EntityFramework/issues/1460

**Closed by maumar** 2015-03-20 20:09 UTC
Labels: bug, pri0

**Comment by maumar** [comment] 2015-03-23 22:30
this is actually duplicate of https://github.com/aspnet/EntityFramework/issues/1829, which is fixed in current bits (post beta3)
