### ISSUE TITLE
OrderByDescending(...).First() returns random for a not mapped property

### ISSUE THREAD

**Issue by gisek** [aspnet/EntityFramework#3302] opened 2015-10-01 22:10 UTC
For an unmapped property:

```
        public DateTime TimeStampInternal { get; set; }

        [NotMapped]
        public Instant TimeStamp
        {
            get { return TimeStampInternal.AsUtc().ToInstant(); }
            set { TimeStampInternal = value.ToDateTimeUtc(); }
        }
```

This code returns a random value

```
var latestSnapshot = _context
                .TagsSnapshots
                .Include(snapshot => snapshot.Tags)
                .Where(snapshot => snapshot.SiteId == siteId)
                .OrderByDescending(snapshot => snapshot.TimeStamp) 
                .FirstOrDefault();
```

This one however works fine
```
var latestSnapshot = _context
                .TagsSnapshots
                .Include(snapshot => snapshot.Tags)
                .Where(snapshot => snapshot.SiteId == siteId)
                .OrderByDescending(snapshot => snapshot.TimeStamp) 
                .ToList()
                .FirstOrDefault();
```

The same with First, FirstAsync, FirstOrDefaultAsync

**Comment by anpete** [comment] 2015-10-01 22:25
Thanks for reporting.

**Comment by anpete** [comment] 2015-10-01 22:26
I think this is an issue with FirstOrDefault being translated to SQL even though the ordering is client-eval.

**Comment by gisek** [comment] 2015-10-01 22:28
@anpete That's also my guess.

**Comment by anpete** [comment] 2015-10-01 22:31
If you want to send a PR, the issue is likely around this line:

https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Relational/Query/Internal/RelationalResultOperatorHandler.cs#L141

**Comment by gisek** [comment] 2015-10-01 22:33
Currently I'm totally out of time. :(

**Comment by anpete** [comment] 2015-10-01 22:35
No problem :smile:

**Comment by fujiy** [comment] 2015-10-14 22:57
I'll try to fix it

**Comment by fujiy** [comment] 2015-10-24 02:31
Is it fixed in this commit? https://github.com/aspnet/EntityFramework/blob/5fd6b00457b8b005cdedb6200de8c7989113221e/src/EntityFramework.Relational/Query/Internal/RelationalResultOperatorHandler.cs#L138

**Comment by rowanmiller** [comment] 2015-12-09 19:33
Fixed

**Closed by rowanmiller** 2015-12-09 19:33 UTC
Labels: bug, pri0, up-for-grabs
