### ISSUE TITLE
ModelBuilder: Shadow property introduction doesn't work without calling Property<T>()

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#4843] opened 2016-03-17 22:10 UTC
```C#
class TestClass
{
    public string Name { get; set; }
}

class Test
{
    public int Id { get; set; }
    public TestClass Class { get; set; }
}
```
```C#
modelBuilder.Entity<TestClass>(
    x =>
    {
        // NOTE: HasKey fails without this
        x.Property<string>("AssemblyName");

        x.HasKey("AssemblyName", "Name");
    });
modelBuilder.Entity<Test>(
    x =>
    {
        // NOTE: HasForeignKey fails without this
        x.Property<string>("AssemblyName");

        x.HasOne(t => t.Class).WithMany(c => c.Tests)
            .HasForeignKey("AssemblyName", "ClassName");
    });
```

**Comment by smitpatel** [comment] 2016-03-18 19:30
`HasKey` does not create shadow properties therefore the shadow property needs to be defined first. (same with `HasIndex`)
`HasForeignKey` creates shadow properties but only when there is compatible Principal Key to replicate the property types. For composite FK, there should be either `HasPrincipalKey` call or the PK of principal type should have composite FK defined.

**Comment by divega** [comment] 2016-06-04 00:15
Updating title because the issue isn't specific to composite keys. It would be nice if calling `HasKey("Id")` could act as a shortcut to both create the property (if it doesn't already exists) and make it a key, but `HasKey()` currently doesn't have a way to specify the type. 

BTW, the exception is:

> The property 'Id' cannot be added to the entity type 'Customer' because there was no property type specified and there is no corresponding CLR property. To add a shadow state property the property type needs to be specified.

**Comment by smitpatel** [comment] 2016-06-04 00:20
One of the reasons for not creating shadow properties for `HasKey` & `HasIndex` is "typo"

**Comment by divega** [comment] 2016-06-04 00:42
@smitpatel agreed, but when using the string version of `Property<T>()` we already assume the user's intent is a bit more likely to be to refer to a shadow property. Then by extension I think it would be ok to assume the same thing for other string based APIs on the same `EntityTypeBuilder` where the property would need to be created.

In any case (unless I am missing a detail that justified the original title to be about composite keys), this is assigned to 1.0.1, so we can discuss it soon.

**Closed** 2016-06-08 19:33 UTC
Labels: app-week, bug, pri0
