### ISSUE TITLE
The column was specified multiple times for 't0'.

### ISSUE THREAD

**Issue by Aequoris** [aspnet/EntityFramework#2608] opened 2015-07-13 05:18 UTC
I am using a nightly build
"EntityFramework.SqlServer": "7.0.0-beta6-13735",

When including multiple relationships in a query, I am getting an exception thrown with
The column 'DeletedDate' was specified multiple times for 't0'.
The duplicate column names are in Profile and ProfileSkill

var querybuilder = dbContext.Person
                .Include(p => p.GeoData)
                .Include(tp => tp.Profile)
                .ThenInclude(s => s.ProfileSkill)

**Comment by maumar** [comment] 2015-07-16 21:26
@Aequoris Could you also include the model you are using, DbContext and all relevant entities (Person, GeoData, Profile, ProfileSkill)

**Comment by maumar** [comment] 2015-08-19 21:57
unable to reproduce based on provided information, closing

**Closed by maumar** 2015-08-19 21:57 UTC
Labels: bug, pri0
