### ISSUE TITLE
SqlServer one to many post savechanges items gone?

### ISSUE THREAD

**Issue by julielerman** [aspnet/EntityFramework#1449] opened 2015-01-21 20:02 UTC
Testing out a simple one to many relationship w sql server provider. (I have confirmed that all packages are current & from the same build - beta3-12013). No fluent configurations involved.
Migrations comprehends the relationship and builds the tables, keys and FKs correctly.

In my code, I'm creating a graph in memory:
1 new parent with one new child added to it's children navigation property. 
SaveChanges correctly inserts into database, with FK value correctly applied to child.

Prior to SaveChanges, parent.Children.Count (and also inspecting object in debug) shows the child.
Just after SaveChanges, the parent has no children at all. The child did get inserted in to the database. The context is aware of that object. Regardless of whether I depend 100% on the parent.children property to define the 1:* relationship or if I explicitly have a navigation property and FK property defined in the child type, after SaveChanges, the child is no longer attached to the parent.

This was not a problem with inmemory provider. Just SQLServer.

Is this known? A new problem? Something I'm doing wrong?

thanks

**Comment by ajcvickers** [comment] 2015-01-21 21:24
@julielerman Repro code?

**Comment by julielerman** [comment] 2015-01-21 21:30
Will put it together

**Comment by julielerman** [comment] 2015-01-21 22:35
bah... how best to share a tiny solution with you? do I have to put it up on github? I don't like putting not working stuff on gh

**Comment by ajcvickers** [comment] 2015-01-21 22:38
You could email it to me, or just copy/paste the code here, inside a code block markdown.

**Comment by cherrydev** [comment] 2015-01-29 23:43
When you're re-fetching the parent entity, are you Include()ing the child collection?  EF7 doesn't implement proper object graph navigation yet; you have to explicitly include collections or they don't get loaded.  I had this problem too when implementing a bi-directional relationship.

**Comment by julielerman** [comment] 2015-01-30 01:15
Hi Cherrydev,
Thanks for the thought. In this case I'm not re-fetching.

Easier to see if I share the method. :)
I'm just counting children before and after saving.

   var parent= new Parent{ Name = "Foo" };
   context.Parents.Add(parent);
   parent.Bars.Add(new Bar{ Text = "Such a fooey bar" });
   Console.WriteLine("Bars before saving:" + parent.Bars.Count());
(Bars.count is 1)
   context.SaveChanges();
   Console.WriteLine("Bars after saving:" + parent.Bars.Count());
(Bars.count is 0)
             
Cheers
Julie

**Comment by rowanmiller** [comment] 2015-03-20 18:42
Here is another repro from the project I am working on. Moving from Investigation so that this can be re-triaged.

```
using System;
using System.Collections.Generic;
using Microsoft.Data.Entity;

namespace ConsoleApp1
{
    public class Program
    {
        public void Main(string[] args)
        {
            using (var db = new UnicornStoreContext())
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                var category = new Category { Products = new List<Product>() };
                db.Categories.Add(category);

                var product = new Product { Category = category, CategoryId = category.CategoryId };
                category.Products.Add(product);
                db.Products.Add(product);

                Console.WriteLine("{0} products in collection before save", category.Products.Count);
                var records = db.SaveChanges();
                Console.WriteLine("Saved {0} rows", records);
                Console.WriteLine("{0} products in collection after save", category.Products.Count);
            }
        }
    }

    public class UnicornStoreContext : DbContext
    {
        public DbSet<Category> Categories { get; set; }
        public DbSet<Product> Products { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=(localdb)\\v11.0;Database=Unicorns;Trusted_Connection=True;");
        }
    }

    public class Category
    {
        public int CategoryId { get; set; }

        public List<Product> Products { get; set; }
    }

    public class Product
    {
        public int ProductId { get; set; }

        public int CategoryId { get; set; }
        public Category Category { get; set; }
    }
}
```

**Comment by divega** [comment] 2015-08-23 14:09
Assigning this back to @ajcvickers for now.

**Comment by rowanmiller** [comment] 2015-10-14 18:50
@rowanmiller to verify if this is still broken

**Comment by rowanmiller** [comment] 2015-12-08 00:23
Confirmed that this no longer repros on the latest build

**Closed by rowanmiller** 2015-12-08 00:23 UTC
Labels: bug, pri0

**Comment by JeffgLiu** [comment] 2016-09-03 11:28
I am using AspnetCore 1.0.0, and still having this problem. I initially posted my question in this forum:
https://forums.asp.net/t/2102659.aspx?Is+bug+1449+fixed+
I am pretty sure it's not EF's loading problem, because I pass the object to the view immediately after the values of the collection navigation properties are assigned. In another word, I didn't retrieve them from the database. The good news is everything is in the database, the bad news is I can not wield them using Entity Framework.

**Comment by divega** [comment] 2016-09-03 23:44
@JeffgLiu If you think you may be running into a bug, could you please create a new issue and include full repro details?
