### ISSUE TITLE
Query compilation error or data corruption for queries with GroupJoin wrapped in a subquery when the subset of columns is being projected

### ISSUE THREAD

**Issue by shaulbehr** [aspnet/EntityFramework#7290] opened 2016-12-21 10:27 UTC
This is a pretty specific corner case, but I've managed to repro it several times using different tables.

You need two tables, one with a non-mandatory FK to the other, e.g.

```
public class Salesperson
{
    public Guid SalespersonId {get; set;}
    public string Name {get; set;}
}
public class Customer
{
    public Guid CustomerId {get;set;}
    public Guid? SalespersonId {get;set;}
    public Salesperson Salesperson {get;set;}
}
```
Now you write a query to get the IDs of the top 100 Customers whose salesperson is named Fred:
```
var query = db.Customers
    .Where(q=>q.Salesperson.Name == "Fred")
    .Take(100)
    .Select(q=>q.SalespersonId)
    .ToList();
```
Result: a nasty error with sharp, pointy teeth:
> System.ArgumentException : Expression of type 'Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ValueBufferShaper' cannot be used for parameter of type 'Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.IShaper`1[MyNamespace.Salesperson]' of method 'System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Storage.ValueBuffer,System.Collections.Generic.IEnumerable`1[MyNamespace.Salesperson]]] _GroupJoin[ValueBuffer,BookTag,Nullable`1,TransparentIdentifier`2](Microsoft.EntityFrameworkCore.Query.RelationalQueryContext, System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Storage.ValueBuffer], Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.IShaper`1[Microsoft.EntityFrameworkCore.Storage.ValueBuffer], Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.IShaper`1[MyNamespace.Salesperson], System.Func`2[MyNamespace.Salesperson,System.Nullable`1[System.Guid]], System.Func`3[Microsoft.EntityFrameworkCore.Storage.ValueBuffer,System.Collections.Generic.IEnumerable`1[MyNamespace.Salesperson],Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Storage.ValueBuffer,System.Collections.Generic.IEnumerable`1[MyNamespace.Salesperson]]], Microsoft.EntityFrameworkCore.Query.Internal.GroupJoinInclude, Microsoft.EntityFrameworkCore.Query.Internal.GroupJoinInclude)'

This error goes away if you change any of the following:

- Remove the "Where" clause
- Remove the "Take" clause
- Remove the final "Select" clause (i.e. you get back the whole original object)
- Move the "Select" to before the "Take"
- Make the SalespersonId mandatory

It's a perfect storm of a corner case, but it did, nonetheless, show up in my code, and it is a bug.  I discovered it in EFCore 1.1.0, but even in the latest prerelease of 1.2.0 it is still a problem.

**Comment by divega** [comment] 2017-01-06 19:44
@maumar this could be related to another 1.1.1 issue you are working on.

**Comment by maumar** [comment] 2017-01-11 23:13
turns out to be unrelated to #7367 
Problem is that we are not marking one of the groupjoin sources for materialization, because its wrapped in a subquery

**Comment by maumar** [comment] 2017-01-20 23:20
Problem here is that our current mechanism to find the groupjoin sources that needs to be materialized only works on top level query. If the query has subqueries containing groupjoins, they will not be marked for materialization and cause the error.

The simple fix would be to introduce the visitor that walks the entire QueryModel and finds all the necessary query sources, however the problem with that approach is that we would regress perf in some scenarios - we would bring out even more data (which we currently don't do).

Better solution is to be smart about which sources we need - only mark for materialization sources that are part of the client side GroupJoin. If the GroupJoin is eliminated (flattened using SelectMany) - we don't need to materialize the main from clause. This effectively could address https://github.com/aspnet/EntityFramework/issues/6647. Problem is that there is significant risk associated with doing so, and it might not fit into 1.1.1

**Comment by maumar** [comment] 2017-01-20 23:20
clearing milestone for re-triage

**Comment by maumar** [comment] 2017-01-27 02:44
Moving to 1.1.1. again since this bug may cause data corruption in some cases

**Comment by rowanmiller** [comment] 2017-01-30 19:54
We are OK with taking a minimal fix to this in 1.1.1. A more complete fix (better perf, cleaner SQL, etc.) will go into 2.0.

**Comment by maumar** [comment] 2017-01-31 21:47
@divega
Justification to include this in 1.1.1 release:

Impact: High. Issue was reported by a customer and is a regression introduced in 1.1.0. It can also cause data corruption in specific cases. 

Risk: Low/Medium. We already have the same logic that applied to GroupJoin clauses, but we were not doing it recursively. However, the fix incurs a performance hit - we will now yield more unnecessary data from database and materialize them as entities for the affected scenarios (groupjoins in a subquery). For simpler cases its just extra columns, more complicated ones can turn into N+1 queries.

**Comment by maumar** [comment] 2017-02-04 03:19
Fixed in c99151d2b27d8ffc2cfed7d27eb099c399fcbdcf

**Comment by shaulbehr** [comment] 2017-02-05 07:21
Great, thanks!  Any idea when 1.1.1 will be released?

**Comment by maumar** [comment] 2017-02-07 09:34
We don't have exact dates yet, but most likely sometime this month

**Comment by Eilon** [comment] 2017-02-08 22:52
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.

**Closed** 2017-02-09 00:24 UTC
Labels: closed-fixed, patch-approved, type-bug
