### ISSUE TITLE
Re-enable tests skipped to unblock CI

### ISSUE THREAD

**Issue by pranavkm** [aspnet/EntityFramework#1499] opened 2015-01-29 07:03 UTC
Revert this changeset: e1fb1deaeda8890ce1567176c68381abc3988161

**Comment by divega** [comment] 2015-01-29 09:35
@anpete Looks like yesterday's change may have broken something.

**Comment by AndriySvyryd** [comment] 2015-01-29 22:16
This is caused by different branches (i.e. dev and release) running on the same CI agent and creating different databases.

**Comment by anpete** [comment] 2015-02-12 22:57
Closing as already re-enabled.

**Closed by anpete** 2015-02-12 22:57 UTC
Labels: pri0, test
