### ISSUE TITLE
Support self-referencing overlapping FK/PK (since generated value does not need to be propagated)

### ISSUE THREAD

**Issue by waterfallbay** [aspnet/EntityFramework#3376] opened 2015-10-08 06:11 UTC
I have a ModifierGroupHeader which has a foreign key 
.ForeignKey(x => new { x.LinkedGroupHeaderId, x.AccountId, });
pointing to itself with self reference.

An exception of type 'System.InvalidOperationException' occurred in EntityFramework.Core.dll but was not handled in user code

Additional information: A circular dependency was detected: 'ModifierGroupHeader' {'LinkedGroupHeaderId', 'AccountId'} -> 'ModifierGroupHeader' {'GroupHeaderId', 'AccountId'}.

My EF7 is written as follows:
```C#
modelBuilder.Entity<ModifierGroupHeader>()
                            .Reference(x => x.ModifierGroupHeader2)
                            .InverseCollection(x => x.ModifierGroupHeader1)
                            .ForeignKey(x => new { x.LinkedGroupHeaderId, x.AccountId, });
```

**Comment by rowanmiller** [comment] 2015-10-09 20:46
__EF Team Triage:__ This issue is lacking enough information for us to be able to effectively triage it. For a guide on submitting good bug reports, read_ [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). _The most important elements to help us act on a bug report are example code/steps that reproduce the issue, the outcome/results you are expecting, and the results or error message that you are receiving. Following are a few questions to help us understand this bug report, for future issues please try to include this info in the initial report._

Could you share a complete code listing (or a project) that we can use to reproduce and debug the issue you are seeing?

**Comment by smitpatel** [comment] 2015-10-09 22:53
As the exception message says - the property `AccountId` is part of both principal key and foreign key. Not sure if that is a valid relationship.

**Comment by smitpatel** [comment] 2015-10-09 23:11
discussed with @AndriySvyryd  about this. It is cycle so we are throwing correct exception but since there is only one node in the cycle we could allow it too. Though not required at present.

Example model
````
public class Node
    {
        public int ListId { get; set; }
        public int PreviousNodeId { get; set; }
        public int NextNodeId { get; set; }

        public Node PreviousNode { get; set; }
        public Node NextNode { get; set; }
    }

modelBuilder.Entity<Node>(b =>
{
    b.HasKey(e => new {e.ListId, e.PreviousNodeId});
    b.HasOne(e => e.NextNode)
        .WithOne(e => e.PreviousNode)
        .ForeignKey<Node>(e => new {e.ListId, e.NextNodeId});
});
````

Take Node as linked list node. ListId denotes which linked list this node belongs to. ListId, PreviousNodeId is PK. All nodes in same linked list will have same ListId and when you add new node in existing linked list you propagate same ListId value to new node.

**Comment by waterfallbay** [comment] 2015-10-12 03:30
@smitpatel we put exactly your example model into our project, the same problem arouse that we cannot even load HasKey and HasOne in our model. Is this being supported in UWP? We are using EF7 Beta 6.
![2015-10-12_11-23-09](https://cloud.githubusercontent.com/assets/13427419/10421108/1553d34c-70d4-11e5-970c-dd492b4e305b.png)

What we expected is HasKey and HasOne should be loaded successfully in our project.

**Comment by smitpatel** [comment] 2015-10-12 07:31
@waterfallbay - Can you tell me what is the primary key for `ModifierGroupHeader`? According to the exception message, it seems that you have a common property in principal key and foreign key which is causing the cycle and exception is thrown.

The example I have given is simplified repro of the exception. It is not the solution. It is primary investigation so that team can triage this. The reason you could not find `HasKey` & `HasOne` method is I have used the nightly build for the example and API has changed.

**Comment by waterfallbay** [comment] 2015-10-13 02:36
@rowanmiller sorry for not asking the question precisely and lack of information provided
@smitpatel OK, i guess I should reword question:

Is that HasKey and HasOne is not available in beta 6? If yes, we would wait for beta 8 and look into this issue again (as beta 7 cannot be used in UWP project). Anyways, here is my table schema and model:
```sql
CREATE TABLE "ModifierGroupHeader" (
"GroupHeaderId"  integer NOT NULL,
"AccountId"  integer NOT NULL,
"GroupBatchName"  nvarchar(50) NOT NULL COLLATE NOCASE ,
"GroupBatchNameAlt"  nvarchar(200) COLLATE NOCASE ,
"MaxModifierSelectCount"  integer NOT NULL,
"LinkedGroupHeaderId"  integer,
"Enabled"  bit NOT NULL,
"CreatedDate"  datetime NOT NULL,
"CreatedBy"  nvarchar(50) NOT NULL COLLATE NOCASE ,
"ModifiedDate"  datetime NOT NULL,
"ModifiedBy"  nvarchar(50) NOT NULL COLLATE NOCASE ,
"IsFollowSet"  bit DEFAULT 0,
PRIMARY KEY ("GroupHeaderId" ASC, "AccountId" ASC),
CONSTRAINT "FK_ModifierGroupHeader_ModifierGroupHeader" FOREIGN KEY ("LinkedGroupHeaderId", "AccountId") REFERENCES "ModifierGroupHeader" ("GroupHeaderId", "AccountId")
);
```
Datacontext:
```C#
public virtual DbSet<ModifierGroupHeader> ModifierGroupHeaders { get; set; }

modelBuilder.Entity<ModifierGroupHeader>()
                            .Key(x => new { x.GroupHeaderId, x.AccountId });

modelBuilder.Entity<ModifierGroupHeader>()
                            .Reference(x => x.ModifierGroupHeader2)
                            .InverseCollection(x => x.ModifierGroupHeader1)
                           .ForeignKey(x => new { x.LinkedGroupHeaderId, x.AccountId, });

```
ModifierGroupHeader.cs
```C#
namespace POS.WebService.DataContext
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    [Table("ModifierGroupHeader")]
    public partial class ModifierGroupHeader
    {
        public ModifierGroupHeader()
        {
            ItemMasters = new HashSet<ItemMaster>();
            ItemSets = new HashSet<ItemSet>();
            ModifierGroupDetails = new HashSet<ModifierGroupDetail>();
            ModifierGroupHeader1 = new HashSet<ModifierGroupHeader>();
        }

        [Key]
        [Column(Order = 0)]
        public int GroupHeaderId { get; set; }

        [Key]
        [Column(Order = 1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int AccountId { get; set; }

        [Required]
        [StringLength(50)]
        public string GroupBatchName { get; set; }

        [StringLength(200)]
        public string GroupBatchNameAlt { get; set; }

        public int MaxModifierSelectCount { get; set; }

        public int? LinkedGroupHeaderId { get; set; }

        public bool Enabled { get; set; }

        public DateTime CreatedDate { get; set; }

        [Required]
        [StringLength(50)]
        public string CreatedBy { get; set; }

        public DateTime ModifiedDate { get; set; }

        [Required]
        [StringLength(50)]
        public string ModifiedBy { get; set; }

        public bool? IsFollowSet { get; set; }

        public virtual ICollection<ItemMaster> ItemMasters { get; set; }

        public virtual ICollection<ItemSet> ItemSets { get; set; }

        public virtual ICollection<ModifierGroupDetail> ModifierGroupDetails { get; set; }

        public virtual ICollection<ModifierGroupHeader> ModifierGroupHeader1 { get; set; }

        public virtual ModifierGroupHeader ModifierGroupHeader2 { get; set; }
    }
}
```

**Comment by ajcvickers** [comment] 2016-05-06 23:54
Closing since both these models work with the current bits. Will send PR with regression tests.

**Closed by ajcvickers** 2016-05-06 23:54 UTC
Labels: enhancement, investigation-needed, pri0
