### ISSUE TITLE
Weird join and group exception

### ISSUE THREAD

**Issue by buraktamturk** [aspnet/EntityFramework#1341] opened 2014-12-31 16:03 UTC
I have two tables in sql server. When i join and group them like this

    from d in db.testq
    join sk in db.test2 on d.test_id equals sk.test_id
    where sk.kid == token.getID()
    group d by d.test_id into a
    select new { id = a.First().d.test_id });

I got the following Exception

    System.InvalidCastException
    Unable to cast object of type 'Microsoft.Data.Entity.Query.QuerySourceScope`1[<>f__AnonymousType10`2[service.Model.test1,service.Model.test2]]' to type 'Microsoft.Data.Entity.Query.QuerySourceScope`1[service.Model.test1]'.

I can't figure it out, is this implemented in EF7?

**Comment by maumar** [comment] 2015-02-12 23:19
@buraktamturk I'm having hard time reproducing this issue. Do you still have the sample project? If so, could you share some more details about it? I'm mostly interested in the shape of the model. Ideally, I would love to see the entire repro code, but if the project is too large or you don't want/can't share it for any reason, the model should be sufficient for me to go ahead with the investigation.

**Comment by buraktamturk** [comment] 2015-02-13 00:18
I would like to post it but i converted entire project to EF6. But the models just having two integers and one string. (I specially made for this case) 

It might be fixed with never version of EF7. I was using beta1 while trying it. I'll be in work in two days, i'll happily share the result. You could try reproducing this case in beta1 version. If it's not working in beta1 but working at now. You could close this issue. Thanks!

**Comment by maumar** [comment] 2015-02-13 02:26
Thanks, will try Beta1. Did you seed the database with any particular data?

**Comment by maumar** [comment] 2015-02-13 22:03
I was able to reproduce this in Beta1 and it seems to be fixed in the latest bits, closing

**Closed by maumar** 2015-02-13 22:03 UTC
Labels: bug, pri0
