### ISSUE TITLE
System.TypeLoadException on applying migrations on sqlite [OSX]

### ISSUE THREAD

**Issue by jazemzer** [aspnet/EntityFramework#3862] opened 2015-11-23 22:20 UTC
Steps to reproduce
1. Create a fresh Web application using 'aspnet' yo generator
2. Restore and build using rc1 release of mono
3. Apply migrations for the IdentitySchema 

```
mlxxxx% dnx ef database update
System.TypeLoadException: Could not load type 'Microsoft.Data.Entity.Scaffolding.SqliteDesignTimeServices, EntityFramework.Sqlite.Design' from assembly ''.
  at Microsoft.Data.Entity.Design.Internal.DesignTimeServicesBuilder.ConfigureProviderServices (System.String provider, IServiceCollection services, Boolean throwOnError) <0x5f98d60 + 0x00023> in <filename unknown>:0
  at Microsoft.Data.Entity.Design.Internal.DesignTimeServicesBuilder.Build (Microsoft.Data.Entity.DbContext context) <0x5d72af0 + 0x00133> in <filename unknown>:0
  at Microsoft.Data.Entity.Design.MigrationsOperations.UpdateDatabase (System.String targetMigration, System.String contextType) <0x5b4a158 + 0x00039> in <filename unknown>:0
  at Microsoft.Data.Entity.Commands.Program+Executor+<>c__DisplayClass7_0.<UpdateDatabase>b__0 () <0x35c8dc8 + 0x00034> in <filename unknown>:0
  at Microsoft.Data.Entity.Commands.Program+Executor.Execute (System.Action action) <0x35c8d48 + 0x0001c> in <filename unknown>:0
Could not load type 'Microsoft.Data.Entity.Scaffolding.SqliteDesignTimeServices, EntityFramework.Sqlite.Design' from assembly ''.

Version information

mlxxxx% yo --version
1.5.0

mlxxxx% dnvm list
Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
       1.0.0-rc1-final      coreclr x64          darwin
  *    1.0.0-rc1-final      mono                 linux/osx       default

mlxxxx% dnu --version
Microsoft .NET Development Utility
 Version:      1.0.0-rc1-16202
 Type:         Mono
 Architecture: x64
 OS Name:      Darwin
 OS Version:   10.10
 Runtime Id:   osx.10.10-x64

mlxxxx% dnvm --version
1.0.0-rc2-15545

mlxxxx% dnx --version
Microsoft .NET Execution environment
 Version:      1.0.0-rc1-16202
 Type:         Mono
 Architecture: x64
 OS Name:      Darwin
 OS Version:   10.10
 Runtime Id:   osx.10.10-x64
```
Note: Switching to Coreclr-rc1-final solves the issue though.

**Comment by rowanmiller** [comment] 2015-11-24 20:04
@bricelam @natemcmaster any thoughts on this one?

**Comment by natemcmaster** [comment] 2015-11-24 20:47
Case sensitive package name issue (again)? Try `EntityFramework.Sqlite` instead of `EntityFramework.SQLite`

**Comment by natemcmaster** [comment] 2015-11-24 21:47
@jazemzer can you post your project.json?

**Comment by jazemzer** [comment] 2015-11-25 09:06
{
  "version": "1.0.0-*",
  "userSecretsId": "xxxx",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "tooling": {
    "defaultNamespace": "xxxx"
  },

  "dependencies": {
      
    "Microsoft.AspNet.Authentication.Google": "1.0.0-rc1-final",
    "AspNet.Security.OAuth.LinkedIn": "1.0.0-*",
    "EntityFramework.Commands": "7.0.0-rc1-final",
    "EntityFramework.SQLite": "7.0.0-rc1-final",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-final",
    "Microsoft.AspNet.Authentication.Cookies": "1.0.0-rc1-final",
    "Microsoft.AspNet.Diagnostics.Entity": "7.0.0-rc1-final",
    "Microsoft.AspNet.Identity.EntityFramework": "3.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final",
    "Microsoft.Dnx.Runtime":"1.0.0-rc1-final",
    "Microsoft.Extensions.CodeGenerators.Mvc": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions" : "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel",
    "ef": "EntityFramework.Commands"
  },

  "frameworks": {
    "dnx451": { },
    "dnxcore50": { }
  },

  "exclude": [
    "wwwroot",
    "node_modules",
    "bower_components"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc"
  ],
  "scripts": {
    "prepublish": [
      "npm install",
      "bower install",
      "gulp clean",
      "gulp min"
    ]
  }
}

**Comment by jazemzer** [comment] 2015-11-25 09:13
I tried lowercasing the sqlite package 
"EntityFramework.Sqlite": "7.0.0-rc1-final",
but the issue persisted. Am I missing something here?

mlxxxx% dnx ef database update
System.TypeLoadException: Could not load type 'Microsoft.Data.Entity.Scaffolding.SqliteDesignTimeServices, EntityFramework.Sqlite.Design' from assembly ''.
  at Microsoft.Data.Entity.Design.Internal.DesignTimeServicesBuilder.ConfigureProviderServices (System.String provider, IServiceCollection services, Boolean throwOnError) <0x5e38538 + 0x00023> in <filename unknown>:0
  at Microsoft.Data.Entity.Design.Internal.DesignTimeServicesBuilder.Build (Microsoft.Data.Entity.DbContext context) <0x5e35348 + 0x00133> in <filename unknown>:0
  at Microsoft.Data.Entity.Design.MigrationsOperations.UpdateDatabase (System.String targetMigration, System.String contextType) <0x59f2958 + 0x00039> in <filename unknown>:0
  at Microsoft.Data.Entity.Commands.Program+Executor+<>c__DisplayClass7_0.<UpdateDatabase>b__0 () <0x34d8dc8 + 0x00034> in <filename unknown>:0
  at Microsoft.Data.Entity.Commands.Program+Executor.Execute (System.Action action) <0x34d8d48 + 0x0001c> in <filename unknown>:0
Could not load type 'Microsoft.Data.Entity.Scaffolding.SqliteDesignTimeServices, EntityFramework.Sqlite.Design' from assembly ''.
mlxxxx% dnvm list

Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
       1.0.0-rc1-final      coreclr x64          darwin
  *    1.0.0-rc1-final      mono                 linux/osx       default

mlxxxx% dnvm use 1.0.0-rc1-final -r coreclr
Adding /Users/xxx/.dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-rc1-final/bin to process PATH
mlxxxx% dnx ef database update
Done.

**Comment by natemcmaster** [comment] 2015-11-25 17:07
It looks like you are missing the design dependency:
```json
"EntityFramework.Sqlite.Design": "7.0.0-rc1-final"
```

@bricelam It looks like `DesignTimeServicesBuilder` is not throwing `CannotFindDesignTimeProviderAssembly` correctly in this case.

**Comment by jazemzer** [comment] 2015-11-25 18:19
I added sqlite Design, restored and built the project and ended up in a different error. 

    "EntityFramework.Sqlite": "7.0.0-rc1-final",
    "EntityFramework.Sqlite.Design": "7.0.0-rc1-final",

mlxxx% dnvm list

Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
       1.0.0-rc1-final      coreclr x64          darwin
  *    1.0.0-rc1-final      mono                 linux/osx       default

mlxxxx% dnx ef database update
System.EntryPointNotFoundException: sqlite3_close_v2
  at (wrapper managed-to-native) Microsoft.Data.Sqlite.Interop.NativeMethods:sqlite3_close_v2 (intptr)
  at Microsoft.Data.Sqlite.Interop.Sqlite3Handle.ReleaseHandle () <0x601b230 + 0x00013> in <filename unknown>:0
  at System.Runtime.InteropServices.SafeHandle.DangerousReleaseInternal (Boolean dispose) <0x18917a0 + 0x00106> in <filename unknown>:0
  at System.Runtime.InteropServices.SafeHandle.DisposeInternal () <0x1891760 + 0x00025> in <filename unknown>:0
  at System.Runtime.InteropServices.SafeHandle.InternalDispose () <0x18916d0 + 0x00028> in <filename unknown>:0
  at System.Runtime.InteropServices.SafeHandle.Dispose (Boolean disposing) <0x1891550 + 0x00025> in <filename unknown>:0
  at System.Runtime.InteropServices.SafeHandle.Dispose () <0x1891520 + 0x00025> in <filename unknown>:0
  at Microsoft.Data.Sqlite.SqliteConnection.Close () <0x601b190 + 0x00057> in <filename unknown>:0
  at Microsoft.Data.Entity.Storage.RelationalConnection.Close () <0x601a8b0 + 0x000c2> in <filename unknown>:0
  at Microsoft.Data.Entity.Storage.Internal.SqliteRelationalConnection.Close () <0x601a878 + 0x00013> in <filename unknown>:0
  at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.Execute[T] (IRelationalConnection connection, System.Func`3 action, System.String executeMethod, Boolean openConnection, Boolean closeConnection) <0x6016948 + 0x004d1> in <filename unknown>:0
  at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.ExecuteScalar (IRelationalConnection connection, Boolean manageConnection) <0x6016850 + 0x000dc> in <filename unknown>:0
  at Microsoft.Data.Entity.Migrations.HistoryRepository.Exists () <0x6015fe0 + 0x0006f> in <filename unknown>:0
  at Microsoft.Data.Entity.Migrations.Internal.Migrator.Migrate (System.String targetMigration) <0x5fabba8 + 0x0007f> in <filename unknown>:0
  at Microsoft.Data.Entity.Design.MigrationsOperations.UpdateDatabase (System.String targetMigration, System.String contextType) <0x5ab0c90 + 0x0006b> in <filename unknown>:0
  at Microsoft.Data.Entity.Commands.Program+Executor+<>c__DisplayClass7_0.<UpdateDatabase>b__0 () <0x3534dc8 + 0x00034> in <filename unknown>:0
  at Microsoft.Data.Entity.Commands.Program+Executor.Execute (System.Action action) <0x3534d48 + 0x0001c> in <filename unknown>:0
sqlite3_close_v2
mlxxxx% dnvm use 1.0.0-rc1-final -r coreclr
Adding /Users/jaeliezer/.dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-rc1-final/bin to process PATH
mlxxxx% dnx ef database update
Done.

**Comment by natemcmaster** [comment] 2015-11-25 18:21
Possible duplicate of https://github.com/aspnet/EntityFramework/issues/3870. Are you using mono-x86? This includes an incompatible version of SQLite. Use Mono-x64 instead.

**Comment by jazemzer** [comment] 2015-11-25 19:42
Yes the mono version is x86. And would you be kind enough to tell me how can I switch to x64 architecture? 

mlxxx% mono --version
Mono JIT compiler version 4.2.1 (explicit/6dd2d0d Tue Nov 10 18:01:18 EST 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug
	LLVM:          yes(3.6.0svn-mono-(detached/a173357)
	GC:            sgen

**Comment by natemcmaster** [comment] 2015-11-25 19:44
http://www.mono-project.com/download/. Install the "Mono Universal Installer".

http://download.mono-project.com/archive/4.2.1/macos-10-universal/MonoFramework-MDK-4.2.1.102.macos10.xamarin.universal.pkg

Feel free to reopen if this does not solve the issue.

**Comment by jazemzer** [comment] 2015-11-25 19:51
I already tried the universal installer after removing the x86 version but the architecture still is x86

**Comment by natemcmaster** [comment] 2015-11-25 19:59
Try homebrew http://brew.sh/
brew install mono
brew link --overwrite mono

**Comment by jazemzer** [comment] 2015-11-25 22:40
Didn't help. I think I'll stick to coreclr or ditch Sqlite for the time being.

**Comment by natemcmaster** [comment] 2015-11-25 22:43
Might be for the best. Mono can be buggy in a lot of other aspects. :+1: for using CoreCLR instead.

**Comment by bricelam** [comment] 2015-11-28 03:20
> It looks like DesignTimeServicesBuilder is not throwing CannotFindDesignTimeProviderAssembly correctly in this case.

I suspect the code wasn't updated appropriately while resolving #3111

**Comment by bricelam** [comment] 2015-11-28 03:24
Oh, or it might be due to strong-naming...

**Comment by eko24** [comment] 2016-01-22 14:16
_I faced with same issue on Ubuntu(Linux), so perhaps it could help._
For me error was in current dnvm version - I've been using `1.0.0-rc1-final` on mono architechture, so I switched to `1.0.0-rc1-update1` on coreclr.

**Comment by divega** [comment] 2016-01-22 19:56
> I suspect the code wasn't updated appropriately while resolving #3111

@bricelam is there additional work there we need to track? Should we reactivate an issue?

**Comment by bricelam** [comment] 2016-01-22 22:40
Yes, if only to make sure it's actually resolved...

**Comment by bricelam** [comment] 2016-01-22 22:42
My theory is that [our DesignTimeProviderServices attributes](https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.Sqlite/Properties/AssemblyInfo.cs#L10-L12) which only have the simple assembly name, aren't able to load the strong-named assemblies in our packages.

**Closed** 2016-02-24 21:51 UTC
Labels: 2 - Done, bug, xplat
