### ISSUE TITLE
Investigate parallelization issues with SqlServer.FunctionalTests

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#7411] opened 2017-01-13 20:44 UTC
These tests fail a lot on CI (and for me after I drop databases) when run in parallel. We used to mitigate this on CI using an environment variable, but this feature is being removed from KoreBuild (see aspnet/KoreBuild#157). Instead, we'll need to disable them at the assembly level by adding the following. (Or debug and fix the issues.)

```C#
[assembly: CollectionBehavior(DisableTestParallelization = true)]
```

**Comment by rowanmiller** [comment] 2017-01-13 22:54
Setting up the "Simple CI" I consistently saw these tests fail when the LocalDb databases were dropped before the test run. I see 28 failures with:

``` ======= Failed test run #1 ==========
System.Data.SqlClient.SqlException : Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
ALTER DATABASE statement failed.
---- System.ComponentModel.Win32Exception : The wait operation timed out
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.TransactionSqlServerFixture.<CreateTestStore>b__2_0() in C:\BuildAgent\work\15b0c01bdac8ff3d\test\Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests\TransactionSqlServerFixture.cs:line 49
   at Microsoft.EntityFrameworkCore.Specification.Tests.TestStore.CreateShared(String name, Action initializeDatabase) in C:\BuildAgent\work\15b0c01bdac8ff3d\src\Microsoft.EntityFrameworkCore.Specification.Tests\TestStore.cs:line 31
   at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.Utilities.SqlServerTestStore.CreateShared(Action initializeDatabase) in C:\BuildAgent\work\15b0c01bdac8ff3d\test\Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests\Utilities\SqlServerTestStore.cs:line 98
   at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.TransactionSqlServerFixture.CreateTestStore() in C:\BuildAgent\work\15b0c01bdac8ff3d\test\Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests\TransactionSqlServerFixture.cs:line 26
   at Microsoft.EntityFrameworkCore.Specification.Tests.TransactionTestBase`2..ctor(TFixture fixture) in C:\BuildAgent\work\15b0c01bdac8ff3d\src\Microsoft.EntityFrameworkCore.Relational.Specification.Tests\TransactionTestBase.cs:line 680
   at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.TransactionSqlServerTest..ctor(TransactionSqlServerFixture fixture) in C:\BuildAgent\work\15b0c01bdac8ff3d\test\Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests\TransactionSqlServerTest.cs:line 14
----- Inner Stack Trace -----
```

I've disabled the step that cleans the databases for the moment.

**Comment by rowanmiller** [comment] 2017-01-17 19:42
@bricelam feel free to disable paralellization for now, if needed to unblock CI

**Comment by bricelam** [comment] 2017-02-17 16:20
I disabled parallelization in with the move to VS 2017.

@ajcvickers This may be why the tests got six minutes slower on your machine...

**Comment by smitpatel** [comment] 2017-02-17 17:08
either this or #7195  should be closed as dupe.

**Comment by ajcvickers** [comment] 2017-03-13 21:12
@AndriySvyryd Could you bump up the priority of this and do some initial investigation this week? See also  #7837

**Comment by ajcvickers** [comment] 2017-03-13 21:13
@AndriySvyryd Also, FYI, @bricelam is able to reproduce these issues running locally.

**Comment by AndriySvyryd** [comment] 2017-03-13 21:58
On it.

**Closed** 2017-03-15 19:26 UTC
Labels: type-test
