### ISSUE TITLE
Trace when query is done. This is needed in order to get SelectRows statistics.

### ISSUE THREAD

**Issue by fitzchak** [aspnet/EntityFramework#7105] opened 2016-11-23 12:19 UTC
In order to get the SelectRows from SqlStatistics we need to add this trace statement, since "System.Data.SqlClient.WriteCommandAfter" tracing is not enough, as this is before the reader is reading the results.
This let us in Entity Framework Profiler report the results for the query.

**Comment by fitzchak** [comment] 2016-11-24 10:12
cc  @anpete

**Comment by fitzchak** [comment] 2017-03-27 14:02
Can this get into next release of v1?

**Comment by ajcvickers** [comment] 2017-03-27 20:33
Marking for re-triage to consider putting it in patch release.

**Comment by ajcvickers** [comment] 2017-03-31 22:26
@fitzchak We discussed this but unfortunately we don't think it meets the bar for a patch release, especially because it contains a binary-compat breaking change. Is there any way you can work around the issue you have without taking the change?

**Comment by fitzchak** [comment] 2017-04-02 07:30
@ajcvickers We cannot work around this.
What is the binary compat breaking change? Isn't it just adding more logs?

**Comment by ajcvickers** [comment] 2017-04-04 16:30
@fitzchak The PR changes the signature for the RelationalDataReader constructor. We might be able to make the change in a non-breaking way, but to justify it going into a patch release we will need some details as to exactly what is not working so we can get approval.

**Comment by ajcvickers** [comment] 2017-04-12 18:41
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2017-04-12 18:41 UTC
Labels: type-enhancement

**Comment by fitzchak** [comment] 2017-05-22 06:39
Hi,
We need this in order to show Row Count in EntityFrameworkProfiler: http://issues.hibernatingrhinos.com/issue/UberProf-365

**Comment by divega** [comment] 2017-05-22 07:27
@fitzchak to be clear, your PR made it into 2.0.0-preview1. It just did make into a patch for the 1.x versions (that is what the last few comments are about). Are you getting many customer requests for this functionality in 1.x versions?

**Comment by fitzchak** [comment] 2017-05-23 12:50
@divega Hi, yes. We have many customer requests to use the profiler with the current version of EntityFrameworkCore. The profiler is working well, but do not show the row count and duration for the statements (see attachment image) and we get many requests to fix this. This PR should fix this.

![image](https://cloud.githubusercontent.com/assets/629734/26354868/261b3c44-3fcf-11e7-8156-243a90bb62ab.png)
