### ISSUE TITLE
.net core 1.1 indexes

### ISSUE THREAD

**Issue by sbradley090877** [aspnet/EntityFramework#7082] opened 2016-11-21 09:24 UTC
Having trouble upgrading to .net core 1.1. following the guide
created a brand new console app, as per the guide, created as 1.0.1
ran nuget package manager to update to 1.1
generated context from database first
created basic entity framework get all on db context on random table
I get error;

The indexes {'LocationId', 'PromotionId'} on 'DrpromotionLocation' and {'PromotionId'} on 'DrpromotionLocation' are both mapped to 'DRPromotionLocation.IX_DRPromotionLocation_PromotionId' but with different columns ({'LocationId', 'PromotionID'} and {'PromotionID'}).

This is not a one off, it seems to be on any table with an index
its been generated from database first, so nothing wrong with the database
This has all worked so far on .net core 1.0.1 and previous version of .net
any help appreciated

**Comment by rowanmiller** [comment] 2016-11-21 21:29
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information? If you are just reverse engineering, and not making any extra changes to the model, then just providing the database schema should be enough.

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean 😄... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

**Comment by rowanmiller** [comment] 2016-11-28 19:20
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean 😄... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).

**Comment by rowanmiller** [comment] 2016-11-28 19:21
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Comment by kudoz83** [comment] 2017-01-04 04:09
I'm suffering from the same issue. 

SCHEMA: 
`CREATE TABLE [dbo].[Application]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1000,1), 
	[Name] NVARCHAR(128) NOT NULL,
        [CreatedDate] SMALLDATETIME NOT NULL DEFAULT getutcdate(), 
	[DeletedDate] SMALLDATETIME NULL
) GO `

`CREATE TABLE [dbo].[ApplicationKey]
(
	[Id] INT NOT NULL IDENTITY(1000, 1),
    [ApplicationId] INT NOT NULL, 
    [CreatedDate] SMALLDATETIME NOT NULL DEFAULT getutcdate(), 	
    [DeletedDate] SMALLDATETIME NULL,	
    [Value] NVARCHAR(64) COLLATE Latin1_General_CS_AS NOT NULL,  
	[Label] NVARCHAR(32) NULL,
    CONSTRAINT [PK_ApplicationKey] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_ApplicationKey_Application] FOREIGN KEY ([ApplicationId]) REFERENCES [Application]([Id]),
	CONSTRAINT [UNIQUE_ApplicationKey_Value] UNIQUE NONCLUSTERED ([Value])
) GO `

`CREATE INDEX [IX_ApplicationKey_ApplicationId] ON [dbo].[ApplicationKey] ([ApplicationId], [DeletedDate]) INCLUDE([Id], [Value], [Label], [CreatedDate])
GO`

`CREATE INDEX [IX_ApplicationKey_Value] ON [dbo].[ApplicationKey] ([Value], [DeletedDate]) INCLUDE([Id], [ApplicationId], [Label], [CreatedDate])
GO`

SCAFFOLD DATA CLASSES FROM DATABASE:
`dotnet ef dbcontext scaffold ... -o "Data" -c "DbContext" -f`

Project will build fine, try to do a list or something from the database and you should get the errors.

**Comment by ajcvickers** [comment] 2017-01-04 22:21
Note for triage: schema to repro provided above.

**Comment by Reonekot** [comment] 2017-01-06 12:53
Just a "me 2" - I'm surprised this hasn't got any more mentions, as I think it breaks with any "real life" production databases. Half our tables has indexes that breaks and as we use database first and recreates the context on changes, hand editing is out of the question for us.

I have worked around it for now by removing all "entity.HasIndex" calls through a script (which I need anyway to rename namespaces because I need more than one context in the project), but I don't know if there is any downside to doing this, when not using migrations etc.? It seems to be working...

**Comment by sbradley090877** [comment] 2017-01-06 13:00
I gave up and just left entity framework as v1.01 until it gets fixed hopefully in a newer version

**Comment by kudoz83** [comment] 2017-01-06 17:21
@Reonekot - if we're discussing feelings on the matter -  The problem is that Database First feels like it is becoming a 2nd class citizen to Code First.  I can't imagine a high value project where I wouldn't *prefer* a qualified DBA managing the database, and that won't happen in a code first scenario.   Even as a start up we've structured our database processes to support growth in that direction later... If I'm doing a hackathon - maybe code first makes sense... but even then, if the tooling for DB first were in better shape today I think a VS database project would still be easier.   Just the fact that there isn't some unit test, with at least one index created (which would have failed), demonstrates how Code First completely discourages proper performance considerations while creating the database.

**Comment by kudoz83** [comment] 2017-01-06 17:28
@sbradley090877 in the team's defense - they did ask you to provide steps to reproduce, like 3 months ago.  Submit bugs, and then stay on top of them - it will be a big help to the rest of the community (I'm sure this fix would have made it into the 1.1 release for example had you followed up)

Just food for thought next time.

**Comment by RonCass** [comment] 2017-01-18 15:07
@rowanmiller Hi Rowan/EF Team, I just started having the same issue. Here is some information that hopefully helps.

**Also, I just reverted my packages back to the original version that works and I don't get the exception anymore. I put the both package versions below.**

I generated my models and DBContext about 4-6 months ago and have been building a site off them since then. Just yesterday I upgraded a bunch of packages from 1.0.* to 1.1.* and started to get this error. Nothing has changed with those models or the DBContext so it appears this error is due to the upgrade to 1.1.

Error: The indexes { ClaimNumberOnFile', 'DateOfLoss', 'ClaimId', 'AdjusterId', 'ClaimStatusId'} on 'Claims' and {'ClaimStatusId'} on 'Claims' are both mapped to 'Claims.IX_Claims_ClaimStatusID' but with different columns ({'ClaimNumberOnFile', 'DateOfLoss', 'ClaimID', 'AdjusterID', 'ClaimStatusID'} and {'ClaimStatusID'}).

I commented out that index in the DbContext and it just gave me another error on the next index.

Here is a copy of the package versions that are causing the error :
 "Microsoft.AspNetCore.SpaServices": "1.1.0-rc1-final",
    "Microsoft.AspNetCore.AngularServices": "1.1.0-beta-000002",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Configuration.CommandLine": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    //Rons Additions
    "IdentityModel": "2.1.1",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
    "Microsoft.AspNetCore.Authentication.OpenIdConnect": "1.1.0",
    "Thinktecture.IdentityModel.Client": "4.0.1",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.1.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.1.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": "1.1.0-preview4-final",
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": "1.1.0-preview4-final",
    "Serilog.Extensions.Logging": "1.3.1",
    "Serilog.Sinks.Literate": "2.0.0",
    "Serilog.Sinks.RollingFile": "3.3.0",
    "MailKit": "1.4.0",
    "RonsASPPDFPackage": "1.0.0",
    "AutoMapper": "5.2.0",
    "System.Linq.Dynamic.Core": "1.0.6.9"
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.1.0-preview4-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.1.0-preview4-final",
     "Microsoft.VisualStudio.Web.CodeGeneration.Tools": "1.1.0-preview4-final"
  },
  "frameworks": {
    "net461": {
      "frameworkAssemblies": {
        "System.Web.Extensions": "4.0.0.0"
      }
    }
  },

I just reverted my packages back the original working versions and now it works with no index exception:
   "Microsoft.AspNetCore.AngularServices": "1.0.0-*",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Configuration.CommandLine": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    //Rons Additions
    "IdentityModel": "2.1.1",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Authentication.OpenIdConnect": "1.0.0",
    "Thinktecture.IdentityModel.Client": "4.0.1",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": {
      "version": "1.0.0",
      "type": "build"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Serilog.Extensions.Logging": "1.0.0",
    "Serilog.Sinks.Literate": "2.1.0-dev-00028",
    "Serilog.Sinks.RollingFile": "2.1.0",
    "MailKit": "1.4.0",
    "RonsASPPDFPackage": "1.0.0",
    "AutoMapper": "5.2.0",
    "System.Linq.Dynamic.Core": "1.0.6.5"
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.DotNet.Watcher.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8"
      ]
    }
  },
  "frameworks": {
    "net461": {
      "frameworkAssemblies": {
        "System.Web.Extensions": "4.0.0.0"
      }
    }
  },

**Comment by AndriySvyryd** [comment] 2017-01-25 01:49
Currently we don't uniquify names
This is a regression in a sense, because previously we didn't validate the name uniqueness.

**Comment by AndriySvyryd** [comment] 2017-01-25 19:50
Justification: this is a functional regression in 1.1 for models with indexes that happen to have a name that matches our convention for a different index.
Risk: Low, the fix only affects models that currently would throw an exception.

**Comment by Eilon** [comment] 2017-02-08 22:52
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.

**Closed** 2017-02-08 23:58 UTC
Labels: patch-approved, type-bug
