### ISSUE TITLE
RC2, using ?? operator in select fails with casting error

### ISSUE THREAD

**Issue by sadjadbp** [aspnet/EntityFramework#5439] opened 2016-05-20 04:40 UTC
RC2, using ?? operator in select fails with casting error. 

`.Select(x => x.NullableBooleanProperty ?? false)` 

would fail with casting error. But the same like this is ok

`.Select(x => x.NullableBooleanProperty == null ? false : x.NullableBooleanProperty.value)`

**Comment by mikary** [comment] 2016-05-31 18:06
The invalid cast exception is the result of a general problem with materialization and SQL Server. There are a few different ways to compensate for this issue:

  1. Compensate in SQL generation by always casting `bool` literals to `BIT` (original proposed solution in #5523)
    * This is the most general solution to the problem, but introduces unnecessary `CAST`s into the SQL where results are not required.
    * The new behavior may be introduced through the `RelationalSqlGenerationHelper` or `SqlServerSqlGenerationHelper` (Possible to move all bit casts to SQL Server implementation, probably requires a "providers-beware").
    * The current implementation for `DefaultQuerySqlGenerator.VisitConditional` does similar compensation for this issue and could be simplified by this implementation
  2. Detect and compensate for `bool` casts in materialization
    * Adds additional check / cast logic when using the `ValueBuffer` that could prevent the exception from being thrown in all `int` to `bool` cast cases, but potentially has a negitive performance impact on a very hot path
  3. Modify the `DefaultQuerySqlGenerator` and or `SqlServerQuerySqlGenerator` to special case on `bool` values
    * Introduces logic in SQL generation to compensate for `bool` values in the projection expressions
    * May not be feasible without modifying the expression due to `AliasExpression`s (generating a cast around an alias results in invalid SQL)
  4. Alter the expression before SQL generation (i.e. in `RelationalProjectionExpressionVisitor`)
    * Requires introducing a new `Expression` node / `ExpressionType` to provide a `Convert` expression that can be distinguished from existing converts (current SQL generation ignores `Convert` operations to avoid unnecessary casts)

**Comment by smitpatel** [comment] 2016-07-01 19:23
Already fixed in RTM. Adding test.

**Comment by smitpatel** [comment] 2016-07-01 19:24
dupe of #5652

**Closed** 2016-07-12 21:09 UTC
Labels: closed-fixed, type-bug
