### ISSUE TITLE
Filtering parent entity by a condition in child entity using ANY causing invalid SQL

### ISSUE THREAD

**Issue by dshamim** [aspnet/EntityFramework#5049] opened 2016-04-13 05:31 UTC
When trying to filter the parent entity by child entity, SQL generated is invalid

Parent Entity:

```
[Table("tblOrders")]
    public class Order
    {   
        public int OrderId { get; set; }
        public int MemberId { get; set; }        
        public DateTime OrderDate { get; set; }
        public double TotalValue { get; set; }        
        [Column("OrderCancelled")]
        public bool Cancelled { get; set; }
        [Column("Special_Instructions")]
        public string SpecialInstructions { get; set; }        
        public string CallCentreNotes { get; set; }
        public DateTime? DoorEntryTime { get; set; }
        public int DoorEntryCount { get; set; }

        //navigation properties
        public ICollection<Ticket> Tickets { get; set; }
        
    }
```

Child Entity:

 ```
[Table("tblTicketSales")]
    public class Ticket {
        public int TicketId { get; set; }
        [Column("TicketQty")]
        public int Quantity { get; set; }
        //[Column("TicketPax")]
        //public int Pax { get; set; }        
        //public string Seats { get; set; }

        public double TicketPrice { get; set; }

        //navigation property
        [ForeignKey("Order")]
        [Column("OrderId")]
        [JsonIgnore]
        public int OrderId { get; set; }
        [ForeignKey("OrderId")]
        [JsonIgnore]
        public virtual Order Order { get; set; }
        public int TicketSeatTypeId { get; set; }
        public virtual TicketSeatType TicketSeatType { get; set; }
    }
```

Controller Query:
`var order = _context.Orders.Include(e => e.Tickets).Where(e => e.Cancelled == false && e.OrderId == id).Any(e=>e.Tickets.Any(t=>t.Quantity!=0))`

Generated SQL with syntax error:

`SELECT CASE
    WHEN EXISTS (
        SELECT 1
        FROM [tblOrders] AS [e]
        WHERE (([e].[OrderCancelled] = 0) AND ([e].[OrderId] = @__id_0)) AND (
            SELECT CASE
                WHEN EXISTS (
                    SELECT 1
                    FROM [tblTicketSales] AS [t]
                    WHERE ([t].[TicketQty] <> 0) AND ([e].[OrderId] = [t].[OrderId]))
                THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
            END
        ))
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END`

**Comment by smitpatel** [comment] 2016-04-19 19:49
dupe of #4877. fixed in latest code already.
Generated SQL now
````
SELECT CASE
    WHEN EXISTS (
        SELECT 1
        FROM [tblOrders] AS [e]
        WHERE (([e].[OrderCancelled] = 0) AND ([e].[OrderId] = @__id_0)) AND EXISTS (
            SELECT 1
            FROM [tblTicketSales] AS [t]
            WHERE ([t].[TicketQty] <> 0) AND ([e].[OrderId] = [t].[OrderId])))
    THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END
````

**Closed by smitpatel** 2016-04-19 19:49 UTC
Labels: bug, pri0
