### ISSUE TITLE
Tests are failing because of timeouts

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/EntityFramework#1971] opened 2015-04-01 21:22 UTC
There are some EF tests that keep timing out on different build agents. It is pretty bad because the entire run of 15K tests is marked as failed because 1-10 EF tests fail.

Here is an example of a build that has one single EF test failed:
https://aspnet-ci.cloudapp.net/viewLog.html?buildId=263&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win10_Universe

```
BuiltInDataTypesSqlServerTest.Can_insert_and_read_back_all_nullable_data_types_with_values_set_to_non_null

System.Data.SqlClient.SqlException : Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
 ---- System.ComponentModel.Win32Exception : The wait operation timed out
    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
    at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
    at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
    at Microsoft.Data.Entity.Relational.SqlStatementExecutor.<>c__DisplayClass7_0.<ExecuteNonQuery>b__0() in C:\BuildAgent\work\35116a8defcd3a21\Universe\EntityFramework\src\EntityFramework.Relational\SqlStatementExecutor.cs:line 125
    at Microsoft.Data.Entity.Relational.SqlStatementExecutor.Execute(IRelationalConnection connection, Func`1 action) in C:\BuildAgent\work\35116a8defcd3a21\Universe\EntityFramework\src\EntityFramework.Relational\SqlStatementExecutor.cs:line 168
    at Microsoft.Data.Entity.Relational.SqlStatementExecutor.ExecuteNonQuery(IRelationalConnection connection, DbTransaction transaction, IEnumerable`1 sqlBatches) in C:\BuildAgent\work\35116a8defcd3a21\Universe\EntityFramework\src\EntityFramework.Relational\SqlStatementExecutor.cs:line 116
    at Microsoft.Data.Entity.SqlServer.SqlServerDataStoreCreator.Create() in C:\BuildAgent\work\35116a8defcd3a21\Universe\EntityFramework\src\EntityFramework.SqlServer\SqlServerDataStoreCreator.cs:line 45
    at Microsoft.Data.Entity.Relational.Migrations.Migrator.Execute(IEnumerable`1 sqlBatches, Boolean ensureDatabase) in C:\BuildAgent\work\35116a8defcd3a21\Universe\EntityFramework\src\EntityFramework.Relational\Migrations\Migrator.cs:line 310
    at Microsoft.Data.Entity.Relational.Migrations.Migrator.ApplyMigrations(String targetMigration) in C:\BuildAgent\work\35116a8defcd3a21\Universe\EntityFramework\src\EntityFramework.Relational\Migrations\Migrator.cs:line 157
    at Microsoft.Data.Entity.Relational.RelationalDatabase.ApplyMigrations() in C:\BuildAgent\work\35116a8defcd3a21\Universe\EntityFramework\src\EntityFramework.Relational\RelationalDatabase.cs:line 35
    at Microsoft.Data.Entity.SqlServer.FunctionalTests.SqlServerMigrationsTest.<Empty_Migration_Creates_Database>d__0.MoveNext() in C:\BuildAgent\work\35116a8defcd3a21\Universe\EntityFramework\test\EntityFramework.SqlServer.FunctionalTests\SqlServerMigrationsTest.cs:line 26
 --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
 --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 ----- Inner Stack Trace -----
```

I talked to @bricelam and he suggested making the connection string configurable so we can use SQL express instead of localdb. In the end, any solution that unblocks the CI works.

cc @divega

**Comment by victorhurdugaci** [comment] 2015-04-15 21:20
Ping, @divega is it possible to address this? We still haven't got a successful run because of these timeouts...

**Comment by divega** [comment] 2015-04-29 20:31
@mikary please talk to @victorhurdugaci if we need to try any possible workarounds.

**Comment by mikary** [comment] 2015-05-12 22:05
Appears to be some kind of performance issue in ```EntityFramework.SqlServer.FunctionalTests``` resulting in commands getting queued and timing out. We considered adjusting the SQL Server ```CommandTimeout``` through some kind of configuration file options, but this introduces an undesirable amount of test infrastructure and complexity.

The current workaround for this problem is to not allow these tests to run in parallel on the impacted CIs by adding an environment variable to disable parallel testing for specified projects aspnet/Universe#217

**Comment by mikary** [comment] 2015-05-13 21:50
While looking into the root cause of this issue, I observed occasional error messages on timeouts stating:

```Could not obtain exclusive lock on database ‘model’. Retry the operation later```

There is a related issue on SQL Server marked as closed (by design) that describes how database creation requires an exclusive lock on the 'model' database:
https://connect.microsoft.com/SQLServer/feedback/details/631177/creating-database-fails-with-error-could-not-obtain-exclusive-lock-on-database-model-retry-the-operation-later

Many of the failing test fixtures include multiple tests that each create and delete a scratch database (for example ```SqlServerDatabaseCreationTest``` has 8 tests that create unique scratch databases).

While running these tests, the CI disk I/O hovers around 100%. If SQL Server is I/O bound and receiving multiple table creation operations in parallel, these operations are probably being queued up and eventually timing out.

**Comment by mikary** [comment] 2015-05-21 20:33
Opened #2247 to track long term solution for this issue, for now the work around (running tests with no parallel option) appears to resolve the issue for the CIs.

**Closed** 2015-05-21 20:33 UTC
Labels: 2 - Done, pri0
