### ISSUE TITLE
Exception msg for properties not included in the model

### ISSUE THREAD

**Issue by JanLenoch** [aspnet/EntityFramework#4627] opened 2016-02-23 09:33 UTC
### Title
PropertyMappingValidationConvention throws upon scaffolding a new migration in a full .NET solution.

### Functional impact
Migration cannot be created (scaffolded).

### Minimal repro steps
1. Open the [ZIP archive](https://onedrive.live.com/redir?resid=A58EF47BA9A2178B!114720&authkey=!AN-ENf-QKOU4Ly8&ithint=file%2czip) and restore the solution.
2. Within the SqlServerAccess project, restore NuGet packages.
3. In the Package Manager Console, add a new migration (e.g. `Add-Migration Migration01`).

### Expected result
New migration should be scaffolded.

### Actual result
The following error message appears in the Package Manager Console window:
System.ArgumentNullException: Value cannot be null.
Parameter name: propertyInfo
   at Microsoft.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.Data.Entity.Metadata.Conventions.Internal.RelationalPropertyMappingValidationConvention.FindCandidateNavigationPropertyType(PropertyInfo propertyInfo)
   at Microsoft.Data.Entity.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.Data.Entity.Metadata.Conventions.Internal.ConventionDispatcher.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.Data.Entity.Metadata.Internal.InternalModelBuilder.Validate()
   at Microsoft.Data.Entity.ModelBuilder.Validate()
   at Microsoft.Data.Entity.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.Data.Entity.Infrastructure.ModelSource.<>c__DisplayClass8_0.<GetModel>b__0(Type k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Data.Entity.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.Data.Entity.Internal.DbContextServices.CreateModel()
   at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_5(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Data.Entity.Design.Internal.DesignTimeServicesBuilder.<>c__DisplayClass7_0.<ConfigureContextServices>b__8(IServiceProvider _)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Data.Entity.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.Data.Entity.Design.OperationExecutor.<AddMigrationImpl>d__7.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Design.OperationExecutor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at Microsoft.Data.Entity.Design.OperationExecutor.OperationBase.Execute(Action action)

### Further technical details
Although it might be unrelated to the issue above, how can I 'tell EF to use specific types' if I need to use declarations with interfaces (like `public List<IDocumentPart> Parts { get; set; }`)?

Thank you.

**Comment by smitpatel** [comment] 2016-02-23 09:54
dupe of #3679 

> how can I 'tell EF to use specific types' if I need to use declarations with interfaces (like  public List<IDocumentPart> Parts { get; set; } )?
You can use fluent API to cast the navigation to concrete type for EF. Like
`modelBuilder.Entity<EntityA>().HasMany(e => (List<DocumentPart>)e.Parts).WithOne(e => e.InverseNavigation)`

**Comment by rowanmiller** [comment] 2016-02-26 18:36
@smitpatel this issue was spawned off from #3679 and was specifically about the unhelpful exception that is thrown. Did we do any work to improve the exception message to help folks work out that they need to write the code you listed above?

**Comment by smitpatel** [comment] 2016-02-26 19:58
@rowanmiller - I see that now. Thanks. The stack trace shown in first post mislead me a bit.
After the fix for this
```System.ArgumentNullException: Value cannot be null.
 Parameter name: propertyInfo
```
The exception message thrown will be,
`The property 'Parts' in Entity 'InnerCollection' has not been added to the model or ignored.`

Since there are many reasons for a property was not added to the model by convention, we do not try to find it. If property is candidate navigation then we throw navigation not added else we throw property not added exception.

**Comment by AndriySvyryd** [comment] 2016-03-09 17:01
Fixed by https://github.com/aspnet/EntityFramework/issues/4720

**Closed by AndriySvyryd** 2016-03-09 17:01 UTC
Labels: bug, pri0
