### ISSUE TITLE
SQLite: HasDefaultValueSql + ValueGeneratedOnAddOrUpdate loses default value

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#4502] opened 2016-02-05 18:54 UTC
```c#
public class MyContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite("Data Source=Sample.db");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>()
        .Property(b => b.Modified)
        .HasDefaultValueSql("CURRENT_DATE");
    }
}

public class Blog
{
    public int BlogId { get; set; }
    public DateTime Modified { get; set; }
}
```

Correctly adds a default value to the column...

```SQL
CREATE TABLE "Blog" (
    "BlogId" INTEGER NOT NULL CONSTRAINT "PK_Blog" PRIMARY KEY AUTOINCREMENT,
    "Modified" TEXT NOT NULL DEFAULT (CURRENT_DATE)
)
```

Adding in a call to `ValueGeneratedOnAddOrUpdate`...

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Blog>()
    .Property(b => b.Modified)
    .HasDefaultValueSql("CURRENT_DATE")
    .ValueGeneratedOnAddOrUpdate();
}
```

Results in no default constraint... 

```SQL
CREATE TABLE "Blog" (
    "BlogId" INTEGER NOT NULL CONSTRAINT "PK_Blog" PRIMARY KEY AUTOINCREMENT,
    "Modified" TEXT NOT NULL
)
```

**Comment by ajcvickers** [comment] 2016-03-29 18:36
Same root cause as #4501, so closing as duplicate.

**Closed by ajcvickers** 2016-03-29 18:36 UTC
Labels: bug, pri0
