### ISSUE TITLE
Type conversion error with a DateTime constant in a dynamic Where expression (rc1)

### ISSUE THREAD

**Issue by AlekseyMartynov** [aspnet/EntityFramework#3361] opened 2015-10-07 10:34 UTC
Sample project: https://github.com/AlekseyMartynov/ef7-bugs/tree/date-const-bug

I generate a dynamic Where condition with a `DateTime` constant ([code](https://github.com/AlekseyMartynov/ef7-bugs/blob/date-const-bug/EF7Bugs/Submission1.cs))

And get a type conversion error ("Conversion failed when converting date and/or time from character string.") and the following generated SQL:

    SELECT COUNT(*)
    FROM [Orders] AS [i]
    WHERE [i].[OrderDate] = '1998-05-06 00:00:00.0000000'

**Comment by rowanmiller** [comment] 2015-10-09 19:02
Notes: this is because the column in the database is `datetime`. You should include login in `OnModelCreating` to setup the correct datatype for this column (since the default type for `DateTime` is `datetime2`)... but we're also not sure that EF will do the correct thing even if you do this.

To work with `datetime` we could generate `WHERE [i].[Date] = '1998-05-06 00:00:00.000'`. Alternatively this also works `WHERE [i].[Date] = CAST('1998-05-06 00:00:00.0000000' AS datetime2)`.

**Comment by rowanmiller** [comment] 2015-10-09 19:03
BTW if you split the date time value out into a variable rather than inline in the LINQ query it should work because it will get parameterized.

**Comment by divega** [comment] 2015-10-09 20:17
Just a note on the alternate approach

``` SQL
WHERE [i].[Date] = CAST('1998-05-06 00:00:00.0000000' AS datetime2) 
``` 

I am not sure what type semantic rules SQL Server would apply in this case. If it upcasts `[i].[Date]` implicitly to `datetime2` the resulting query will likely not be sargable. We should check what the case is and take that into account when resolving this issue. A lossy conversion usually works.

**Comment by AlekseyMartynov** [comment] 2015-10-12 10:23
@rowanmiller 

> if you split the date time value out into a variable

Thanks for the suggestion. I tried but with no luck, adding variable leads to `The LINQ expression '{var Param_0; ... }' could not be translated and will be evaluated locally` ([diff](https://github.com/AlekseyMartynov/ef7_const_bug/commit/179cda54a1ecdfe58995e39a5b6b4ac9d3f9db8d))

What actually helps is using a closure over the constant value: https://github.com/AlekseyMartynov/ef7_const_bug/commit/459261c9cf54a071723b2d30bad2d4b3003a7216

**Comment by divega** [comment] 2015-10-12 21:05
@AlekseyMartynov Yes, when we suggested to use a variable that was actually a shortcut for "use the expression pattern the compiler would generate for accessing a variable". Sorry if it wasn't clear.

**Comment by louislewis2** [comment] 2015-11-24 09:33
Is there a tested workaround for this issue at the moment? I had a look at the code from @AlekseyMartynov and found that his sample illustrates the issue nicely, but the part that helps commit is not available anymore. We where using the dynamic linq package out there, but it no longer works for us, so I am urgently looking for a fix, any help will be appreciated.

**Comment by AlekseyMartynov** [comment] 2015-11-24 09:40
@louislewis2 check the workaround I'm using [here](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/a7e69c2df9f626afadfb7980e996ff1cc15ab399/net/DevExtreme.AspNet.Data/FilterExpressionCompiler.cs#L47-L50)

**Comment by louislewis2** [comment] 2015-11-24 09:52
@AlekseyMartynov Thanks for your quick reply. The workaround seems to bring our system back to life again. Greatly appreciate the help.

**Comment by rowanmiller** [comment] 2015-12-10 21:21
This is fixed in the RC2 code base.

Reproduced error on RC1, generates the following SQL:

```SQL
SELECT COUNT(*)
FROM [Product] AS [i]
WHERE [i].[ReleaseDate] = '2015-12-10 00:00:00.0000000'
```

Upgraded to latest RC2 build and we now generate:

```SQL
SELECT COUNT(*)
FROM [Product] AS [i]
WHERE [i].[ReleaseDate] = '2015-12-10T00:00:00.000'
```

Here is the code I used to verify:

```c#
using System;
using Microsoft.Data.Entity;
using System.Linq;
using System.Linq.Expressions;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new ProductContext())
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                db.Products.Add(new Product
                {
                    Name = "Crackers",
                    ReleaseDate = DateTime.Today
                });

                db.Products.Add(new Product
                {
                    Name = "Cheese",
                    ReleaseDate = DateTime.Today
                });

                db.SaveChanges();

                var dataParam = Expression.Parameter(typeof(IQueryable<Product>), "data");
                var itemParam = Expression.Parameter(typeof(Product), "i");

                Expression query = dataParam;

                var whereClause = Expression.Lambda(
                    Expression.MakeBinary(
                        ExpressionType.Equal,
                        Expression.PropertyOrField(Expression.PropertyOrField(itemParam, "ReleaseDate"), "Value"),
                        Expression.Constant(new DateTime(2015, 12, 10))
                    ),
                    itemParam
                );

                query = Expression.Call(typeof(Queryable), "Where", new[] { typeof(Product) }, query, whereClause);
                query = Expression.Call(typeof(Queryable), "Count", new[] { typeof(Product) }, query);

                Expression.Lambda(query, dataParam).Compile().DynamicInvoke(db.Products);
            }
        }
    }

    public class ProductContext : DbContext
    {
        public DbSet<Product> Products { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=Products;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Product>()
                .Property(p => p.ReleaseDate)
                .HasColumnType("datetime");
        }
    }

    public class Product
    {
        public int ProductId { get; set; }
        public string Name { get; set; }
        public DateTime? ReleaseDate { get; set; }
    }
}
```

**Closed by rowanmiller** 2015-12-10 21:21 UTC
Labels: bug, pri0
