### ISSUE TITLE
GroupBy problem

### ISSUE THREAD

**Issue by danroth27** [aspnet/EntityFramework#4623] opened 2016-02-22 22:07 UTC
Originally reported as https://github.com/aspnet/Mvc/issues/4123

Hello!
Exists this model:
```c#
public partial class AddressToOrganisation
	{
		public int AddressId { get; set; }

		public int OrganisationId { get; set; }

		public int TypeId { get; set; }

		public Address Address { get; set; }

		public Organisation Organisation { get; set; }
	}
```
I write query with grouping
```c#
dataContext.Set<AddressToOrganisation>()
                .Include(_ => _.Address)
                .GroupBy(_=> new {_.Address, _.OrganisationId })
                .Select(_=> new {_.Key.Address.FullAddress, _.Key.Address.Id});
```
Result
```
System.ArgumentException: Expression of type 'System.Func`2[Microsoft.Data.Entity.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Organisations.Models.AddressToOrganisation,Satelite.Core.Models.Address],<>f__AnonymousType0`2[Satelite.Core.Models.Address,System.Int32]]' cannot be used for parameter of type 'System.Func`2[Organisations.Models.AddressToOrganisation,<>f__AnonymousType0`2[Satelite.Core.Models.Address,System.Int32]]' of method 'System.Collections.Generic.IEnumerable`1[System.Linq.IGrouping`2[<>f__AnonymousType0`2[Satelite.Core.Models.Address,System.Int32],Organisations.Models.AddressToOrganisation]] _GroupBy[AddressToOrganisation,<>f__AnonymousType0`2,AddressToOrganisation](System.Collections.Generic.IEnumerable`1[Organisations.Models.AddressToOrganisation], System.Func`2[Organisations.Models.AddressToOrganisation,<>f__AnonymousType0`2[Satelite.Core.Models.Address,System.Int32]], System.Func`2[Organisations.Models.AddressToOrganisation,Organisations.Models.AddressToOrganisation])'
   at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0, Expression arg1, Expression arg2)
   at Microsoft.Data.Entity.Query.ResultOperatorHandler.HandleGroup(EntityQueryModelVisitor entityQueryModelVisitor, GroupResultOperator groupResultOperator, QueryModel queryModel)
   at Microsoft.Data.Entity.Query.ResultOperatorHandler.<>c.<.cctor>b__25_9(EntityQueryModelVisitor v, ResultOperatorBase r, QueryModel q)
   at Microsoft.Data.Entity.Query.ResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel)
   at Microsoft.Data.Entity.Query.Internal.RelationalResultOperatorHandler.HandlerContext.EvalOnClient(Boolean requiresClientResultOperator)
   at Microsoft.Data.Entity.Query.Internal.RelationalResultOperatorHandler.HandleGroup(HandlerContext handlerContext)
   at Microsoft.Data.Entity.Query.Internal.RelationalResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
   at Remotion.Linq.Clauses.ResultOperatorBase.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitResultOperators(ObservableCollection`1 resultOperators, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.Internal.SqlServerQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
   at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression node)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CompileMainFromClauseExpression(MainFromClause mainFromClause, QueryModel queryModel)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.CompileMainFromClauseExpression(MainFromClause mainFromClause, QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitMainFromClause(MainFromClause fromClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.MainFromClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.Internal.SqlServerQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
```

**Comment by mikary** [comment] 2016-03-04 23:14
This appears to be a duplicate of #1909. Tested the provided reproduction against current dev and it did not throw the exception.

**Closed by mikary** 2016-03-04 23:14 UTC
Labels: bug, pri0

**Comment by anpete** [comment] 2016-03-04 23:16
Nice!
