### ISSUE TITLE
Query: Exception during composite-keyed entity equality comparison

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#4840] opened 2016-03-17 20:46 UTC
### Model
```C#
class Test
{
    public string Assembly { get; set; }
    public string Class { get; set; }
    public string Name { get; set; }
}

class TestResult
{
    public int Id { get; set; }
    public Test Test { get; set; }
}
```
```C#
modelBuilder.Entity<Test>().HasKey(t => new { t.Assembly, t.Class, t.Name });
```

### Query
```C#
var test = db.Tests.FirstOrDefault();
var testResults = Enumerable.ToArray(
    from r in db.TestResults
    where r.Test == test
    select r);
```

### Exception
    System.InvalidOperationException: No coercion operator is defined between types 'Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor+CompositeKey' and 'Test'.
        at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)
        at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)
        at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitBinary(BinaryExpression node)
        at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
        at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
        at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitBinary(BinaryExpression node)
        at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
        at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
        at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitBinary(BinaryExpression node)
        at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
        at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
        at Remotion.Linq.Clauses.WhereClause.TransformExpressions(Func`2 transformation)
        at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ExpressionTransformingQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
        at Remotion.Linq.Clauses.WhereClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
        at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
        at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
        at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel)
        at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel)
        at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
        at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)

### Workaround

Manually expanding the key comparison operators works.

```C#
var testResults = Enumerable.ToArray(
    from r in db.TestResults
    where r.Test.Assembly == test.Assembly
        && r.Test.Class == test.Class
        && r.Test.Name == test.Name
    select r);
```

**Comment by rowanmiller** [comment] 2016-04-04 18:18
Dupe of https://github.com/aspnet/EntityFramework/issues/113

**Comment by anpete** [comment] 2016-04-04 18:23
Not a dupe of #113. Looks like an issue in nav prop rewriting.

**Comment by maumar** [comment] 2016-05-10 22:30
This has already been fixed, closing

**Closed by maumar** 2016-05-10 22:30 UTC
Labels: app-week, bug, pri0
