### ISSUE TITLE
Incorrect syntax near the keyword 'AS'.

### ISSUE THREAD

**Issue by 0xdeafcafe** [aspnet/EntityFramework#1829] opened 2015-03-14 02:04 UTC
This is being thrown in my repository on the follow marked line:

```csharp
return _db.Users
	.Include(u => u.Sessions)
	.ThenInclude(s => s.TokenPairs) // exception is thrown when this line isn't commented
	.Skip(startAt).Take((int)count)
	.Where(a => !a.IsDeleted)
	.ToList().AsEnumerable();
```

The stacktrace is as follows:
```
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.Data.Entity.Relational.Query.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.Data.Entity.Relational.Query.IncludeCollectionIterator.<GetRelatedValues>d__4.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Query.QueryBuffer.Include(Object entity, IReadOnlyList`1 navigationPath, IReadOnlyList`1 relatedValueReaders, Int32 currentNavigationIndex)
   at Microsoft.Data.Entity.Query.QueryBuffer.Include(Object entity, IReadOnlyList`1 navigationPath, IReadOnlyList`1 relatedValueReaders)
   at Microsoft.Data.Entity.Relational.Query.QueryMethodProvider.<>c__DisplayClass11_0`1.<_Include>b__2(T qss)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Data.Entity.Relational.Utilities.EnumerableExtensions.<Finally>d__0`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Data.Entity.Query.EntityQueryExecutor.EnumerableExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OneOEight.Api.Models.Repositories.UserRepository.GetAllWithIncludes(Int32 startAt, Nullable`1 count) in C:\Users\Alex\Source\Freelance\OneOEight\OneOEight.Api\src\OneOEight.Api\Models\Repositories\UserRepository.cs:line 43
   at OneOEight.Api.Areas.V1.Controllers.UsersController.Get() in C:\Users\Alex\Source\Freelance\OneOEight\OneOEight.Api\src\OneOEight.Api\Areas\V1\Controllers\UsersController.cs:line 82
```

My User Model:
``` csharp
public class User
	: Audit, IUser
{
	/// <summary>
	/// Gets or Sets the username of the <see cref="User"/>.
	/// </summary>
	public string Username { get; set; }

	/// <summary>
	/// Gets or Sets the first name of the <see cref="User"/>.
	/// </summary>
	public string FirstName { get; set; }

	/// <summary>
	/// Gets or Sets the last name of the <see cref="User"/>.
	/// </summary>
	public string LastName { get; set; }

	/// <summary>
	/// Gets or Sets the email address of the <see cref="User"/>.
	/// </summary>
	public string EmailAddress { get; set; }

	#region [ Image ]

	/// <summary>
	/// Gets or Sets the Id of the <see cref="Image"/> containg the Profile Picture of this <see cref="User"/>.
	/// </summary>
	public Nullable<Guid> ImageId { get; set; }

	/// <summary>
	/// Gets or Sets the <see cref="Image"/> containg the Profile Picture of this <see cref="User"/>.
	/// </summary>
	public Image Image { get; set; }

	#endregion

	/// <summary>
	/// Gets or Sets the type of the <see cref="User"/>.
	/// </summary>
	public UserType UserType { get; set; }

	#region [ Trainer ]

	public Nullable<Guid> TrainerId { get; set; }

	public Trainer Trainer { get; set; }

	#endregion

	/// <summary>
	/// Gets or Sets the collection of <see cref="Session"/>'s belonging to the <see cref="User"/>.
	/// </summary>
	public ICollection<Session> Sessions { get; set; }
}
```

My Session Model:
``` csharp
public class Session
	: Audit
{
	/// <summary>
	/// Gets or Sets the User Agent of the <see cref="Session"/>.
	/// </summary>
	public string UserAgent { get; set; }

	/// <summary>
	/// Gets or Sets the Ip Address of the <see cref="Session"/>.
	/// </summary>
	public string IpAddress { get; set; }

	/// <summary>
	/// Gets or Sets if the <see cref="Session"/> has been Revoked.
	/// </summary>
	public bool Revoked { get; set; }

	/// <summary>
	/// Gets or Sets the <see cref="TokenPair"/>'s that belong to the <see cref="Session"/>.
	/// </summary>
	public ICollection<TokenPair> TokenPairs { get; set; }

	#region [ User ]

	/// <summary>
	/// Gets or Sets the Id of the User this <see cref="Session"/>. belongs to.
	/// </summary>
	public Nullable<Guid> UserId { get; set; }

	/// <summary>
	/// Gets or Sets the User this <see cref="Session"/>. belongs to.
	/// </summary>
	public User User { get; set; }

	#endregion
}
```

My TokenPair Model:
``` csharp
public class TokenPair
	: Audit
{		
	/// <summary>
	/// Gets or Sets the Access Token of the <see cref="TokenPair"/>.
	/// </summary>
	public string AccessToken { get; set; }

	/// <summary>
	/// Gets or Sets the Refresh Token of the <see cref="TokenPair"/>.
	/// </summary>
	public string RefreshToken { get; set; }

	/// <summary>
	/// Gets or Sets the time that the <see cref="AccessToken"/> expires.
	/// </summary>
	public DateTime AccessExpiresAt { get; set; }

	/// <summary>
	/// Gets or Sets if the <see cref="TokenPair"/> has been revoked.
	/// </summary>
	public bool Revoked { get; set; }

	#region [ Session ]

	/// <summary>
	/// Gets or Sets the Id of the <see cref="Session"/> that the <see cref="TokenPair"/> belongs to.
	/// </summary>
	public Nullable<Guid> SessionId { get; set; }


	/// <summary>
	/// Gets or Sets the <see cref="Database.Session"/> that the <see cref="TokenPair"/> belongs to.
	/// </summary>
	public Session Session { get; set; }

	#endregion
}
```

The relevant relations in my Context
``` csharp
// Users have many Sessions
modelBuilder.Entity<User>()
	.HasMany(u => u.Sessions)
	.WithOne(s => s.User)
	.ForeignKey(s => s.UserId);

// Sessions have many TokenPairs
modelBuilder.Entity<Session>()
	.HasMany(s => s.TokenPairs)
	.WithOne(t => t.Session)
	.ForeignKey(t => t.SessionId);
```

**Comment by 0xdeafcafe** [comment] 2015-03-14 16:20
I profiled the database while executing the query, and this is what it's trying to execute:
```sql
SELECT [s].[CreatedAt], [s].[DeletedAt], [s].[Id], [s].[IpAddress], [s].[IsDeleted], [s].[Revoked], [s].[UpdatedAt], [s].[UserAgent], [s].[UserId]
FROM [Session] AS [s]
INNER JOIN (
    SELECT DISTINCT [u].[Id]
    FROM [User] AS [u]
) AS [u] ON [s].[UserId] = [u].[Id]
ORDER BY [u].[Id], [s].[Id] AS [Id0]
go
```

**Comment by maumar** [comment] 2015-03-16 18:48
Seems similar to https://github.com/aspnet/EntityFramework/issues/1452
This should be fixed in beta3, so the fix might not be complete. Will investigate

**Comment by 0xdeafcafe** [comment] 2015-03-16 21:25
I'm running the latest version of beta3 from aspnetmaster. Is there anything else you'd like me to provide to help investigation?

**Comment by maumar** [comment] 2015-03-16 21:29
Sample data that you used when running this query could be useful, but I should be able to reproduce the big without it. I will follow up on this thread if I have any problems. Thanks for your help!

**Comment by 0xdeafcafe** [comment] 2015-03-18 13:12
Here are SQL inserts of the data in the specified call. Some items are there that are not in the model, as I removed them from the model, but not the SQL insert.

user:
``` sql
INSERT INTO [dbo].[User] ([Id], [CreatedAt], [EmailAddress], [FacebookAccessToken], [FirstName], [IsAdmin], [LastName], [PasswordHash], [PasswordIterations], [PasswordSalt], [PhoneNumber], [PhoneNumberCountryCode], [UpdatedAt], [Username], [UserType], [ImageId], [TrainerId], [DeletedAt], [IsDeleted], [GenderType]) VALUES (N'059fcd4b-b6e6-4580-56a2-08d225e7b68d', N'2015-03-06 05:44:14', N'alexreed@outlook.com', NULL, N'Alex', 1, N'Forbes-Reed', N'redacted', 1087, N'redacted', N'redacted', 44, N'2015-03-17 05:03:43', N'0xdeafcafe', 0, N'abdc3099-c3bc-4bf1-071d-08d22dc9c67e', NULL, N'1969-01-01 00:00:00', 0, 0)
```

session:
``` sql
INSERT INTO [dbo].[Session] ([Id], [CreatedAt], [IpAddress], [Revoked], [UpdatedAt], [UserAgent], [UserId], [DeletedAt], [IsDeleted]) VALUES (N'7f73e45b-2531-4e8b-e93c-08d22b585b55', N'2015-03-13 04:18:40', N'localhost:4000', 0, N'2015-03-13 04:18:40', N'redacted', N'059fcd4b-b6e6-4580-56a2-08d225e7b68d', N'1969-01-01 00:00:00', 0)
```

token pair:
``` sql
INSERT INTO [dbo].[TokenPair] ([Id], [AccessExpiresAt], [AccessToken], [CreatedAt], [RefreshToken], [Revoked], [UpdatedAt], [SessionId], [DeletedAt], [IsDeleted]) VALUES (N'ebeafb3a-b646-4eef-e6b0-08d22b585b69', N'2016-03-13 04:18:40', N'XkxalksP0tAfyflW473HZ30kdYXhg7T83akKfjdcLx/QG17j+unubY+a/6ZSdtdL', N'2015-03-13 04:18:40', N'VhDnaY5XCi9/+hSIJQrqpE2xLvLFKRLDrcuGt4HStw6XXwuK3YKyYFbr+2CF1BDV8cIZfP/ckAu7je72XZuQbGGwJPMx', 0, N'2015-03-13 04:18:40', N'7f73e45b-2531-4e8b-e93c-08d22b585b55', N'1969-01-01 00:00:00', 0)
```

**Comment by maumar** [comment] 2015-03-20 20:11
duplicate of https://github.com/aspnet/EntityFramework/issues/1460

**Comment by maumar** [comment] 2015-03-23 21:24
this is actually different issue than #1460, reopening

**Comment by maumar** [comment] 2015-03-23 22:29
I was able to repro this on beta-3 from Nuget, but it works as expected in current bits. My guess is that original fix was correct but just didn't get to beta3 (and I thought it did).

New query would look something like:

```
SELECT [s].[CreatedAt], [s].[DeletedAt], [s].[Id], [s].[IpAddress], [s].[IsDeleted], [s].[Revoked], [s].[UpdatedAt], [s].[UserAgent], [s].[UserId]
FROM [Session] AS [s]
INNER JOIN (
    SELECT DISTINCT [u].[Id]
    FROM [User] AS [u]
    WHERE [u].[IsDeleted] = 0
) AS [u] ON [s].[UserId] = [u].[Id]
ORDER BY [u].[Id], [s].[Id]
```

**Closed by maumar** 2015-03-23 22:29 UTC
Labels: bug, pri0
