### ISSUE TITLE
Left Outer Join Exceptions

### ISSUE THREAD

**Issue by brent-russell** [aspnet/EntityFramework#3582] opened 2015-10-28 00:25 UTC
I'm unclear on the status of left outer join functionality as of *beta8*. Is it supposed to be complete? (Also looking at #2809, #2310, #1232)

Some queries I write work fine with LOJ, and I can use the joined object (or null reference) just fine. Other queries throw various exceptions when attempting to do anything with the LOJ data, with the underlying cause appearing to be the same. I'm noticing this particularly with a sufficiently complex query and model, where ultimately what I want is to select an object from the left of the query where the right of the query does not exist.

```C#
//left hand side of query... w/ LOJ below
	into AnsweredQuestions
from qAnswered in AnsweredQuestions
	.DefaultIfEmpty()
where qRoot.RootQuestionId == null
	&& qAnswered == null // EF is buggy with outer join reference
select qRoot;
```

I've experimented with various different tricks and syntax, but the result is the same although the specific exception varies based on the LINQ syntax.

Exceptions:
`Unable to cast object of type 'System.Int32' to type '<MyEntityType>'`
`Object reference not set to an instance of an object.`
`Argument types do not match`
```
Expression of type '<MyEntityType>' cannot be used for parameter of type 'Microsoft.Data.Entity.Storage.ValueBuffer' of method 'System.Collections.Generic.IEnumerable[Microsoft.Data.Entity.Storage.ValueBuffer] DefaultIfEmpty[ValueBuffer] (System.Collections.Generic.IEnumerable[Microsoft.Data.Entity.Storage.ValueBuffer], Microsoft.Data.Entity.Storage.ValueBuffer)'
```

It seems like maybe something on the entity materialization side, where the test field value from the SQL query is trying to be converted into an entity object directly.

If you're not still working on LOJ and want to treat this as a bug, I can provide a more complete set of test code.

Thanks

**Comment by rowanmiller** [comment] 2015-10-30 18:16
@maumar possibly a dupe of something you are already tracking?

**Comment by maumar** [comment] 2015-11-02 21:17
@brent-russell  @rowanmiller the basic support is in, but some more complex cases are still broken. The plan is to address/fix them as we find them. Just today I found another one - https://github.com/aspnet/EntityFramework/issues/3629

@brent-russell please provide all info/test code you can - we will treat this as one of the LOJ bugs

**Comment by brent-russell** [comment] 2015-11-04 08:16
@maumar xunit test project running some sample queries here: https://github.com/brent-russell/ef7-beta8-loj-test

**Comment by maumar** [comment] 2016-03-09 22:40
poaching this

**Comment by maumar** [comment] 2016-03-10 02:31
I went through the tests provided by @brent-russell and based on them I identified 2 specific issues related to joins (#4748 and #4749). Basic LOJ functionality now works so I will close this issue and track the opened ones separately

**Closed by maumar** 2016-03-10 02:31 UTC
Labels: bug, pri0
