### ISSUE TITLE
Server-side evaluation fails if query modifiers precede condition

### ISSUE THREAD

**Issue by breyed** [aspnet/EntityFramework#7560] opened 2017-02-06 23:07 UTC
The warning RelationalEventId.QueryClientEvaluationWarning is issued if `Include` precedes a condition when queries are chained. Code like this will trigger the warning:

    IQueryable<Customer> subQuery = ...
    var query = subQuery.AsTracking().Include(...).Single(condition)

By contrast, code like this does not:

    IQueryable<Customer> subQuery = ...
    var query = subQuery.Where(condition).AsTracking().Include(...).Single()

**Comment by smitpatel** [comment] 2017-02-06 23:15
Can you post the warning text also?

**Comment by breyed** [comment] 2017-02-07 00:02
> Warning as error exception for warning 'RelationalEventId.QueryClientEvaluationWarning': The LINQ expression '([c].AccountNumber == __accountNumber_2)' could not be translated and will be evaluated locally. To suppress this Exception use the DbContextOptionsBuilder.ConfigureWarnings API. ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.

**Comment by tuespetre** [comment] 2017-02-07 17:06
@breyed I wonder if this has more to do with the call to `Single(predicate)`. Does it work if you put `Where(predicate)` after the `AsTracking()` and `Include()` but before `Single()`?

**Comment by breyed** [comment] 2017-02-08 03:18
IQueryable<Customer> subQuery =
        from c in Db.Customers
        where c.BranchId == branchId
        orderby c.LastName, c.FirstName
        select c;

**Comment by smitpatel** [comment] 2017-02-14 23:59
@breyed - Which version of EF are you using?
I tried reproducing this, I received warning in both cases. In one it says cannot translate the equality (which is inside `Single()`) and in second it says cannot translate `Single()`. The cause is `Single` call which needs client evaluation to throw exception.
Can you share your full queries and model classes for reproduction of the issue?

**Comment by smitpatel** [comment] 2017-02-15 00:53
The subquery has an orderby clause. In Sql you cannot have orderby inside a subquery. Therefore it fails to translate outer query and shows client eval warning.
In the case when where is before as tracking, the Re-Linq query parser flattens out the whole model so there is nothing other than `Single()` outside the subquery. If Where comes after AsTracking it cannot translate it to server.

**Comment by smitpatel** [comment] 2017-02-15 01:04
Verify this is fixed when #7613 is closed.

**Comment by smitpatel** [comment] 2017-04-04 00:44
@maumar - Assigning this should be fixed with lifting of order by.

**Comment by maumar** [comment] 2017-04-05 02:14
Fixed in f022d66bc3a461851a6250536399cd3b8f8bf8d2

**Closed by maumar** 2017-04-05 02:14 UTC
Labels: type-enhancement
