### ISSUE TITLE
InMemory fails on nested Query

### ISSUE THREAD

**Issue by glatzert** [aspnet/EntityFramework#3741] opened 2015-11-13 06:44 UTC
The InMemory Database fails on a specific subquery with an Error like Ef.Property<T> may only be called in a LinQ Statement.

```csharp
_dbContext.Persons
                .Where(p => skipFilter || 
                    p.Surname.StartsWith(query.PersonFilter) ||
                    p.GivenName.StartsWith(query.PersonFilter))
                .Where(p => p.Memberships
                    .Any(m =>
                        m.StartDate <= now && m.EndDate > now)
                .OrderBy(p => p.Surname).ThenBy(p => p.GivenName)
```

`Person` is a simple (strong) Entity and `Membership` another (weak) Entity

**Comment by mikary** [comment] 2016-04-27 17:08
@glatzert I've attempted to reproduce the exception you described in this issue with the InMemory provider on current dev, 7.0.0-RC1-final, and 7.0.0-beta8 but I have not seen a case where an exception is thrown by this query. Could you provide additional details about the model and data involved in this issue?

Here is the source for an attempted reproduction of the issue:
```cs
class Program
{
    static void Main(string[] args)
    {
        var skipFilter = false;
        var query = new Query();
        var now = DateTime.Now;

        using (var _dbContext = new MyContext())
        {
            _dbContext.Database.EnsureDeleted();
            _dbContext.Database.EnsureCreated();

            var person = new Person { GivenName = "Filter" };

            var membership1 = new Membership { Person = person };
            var membership2 = new Membership { Person = person };

            _dbContext.AddRange(person);
            _dbContext.AddRange(membership1, membership2);
        }
        using (var _dbContext = new MyContext())
        {
            _dbContext.Persons
                .Where(p => skipFilter ||
                            p.Surname.StartsWith(query.PersonFilter) ||
                            p.GivenName.StartsWith(query.PersonFilter))
                .Where(p => p.Memberships
                    .Any(m =>
                        m.StartDate <= now && m.EndDate > now))
                .OrderBy(p => p.Surname).ThenBy(p => p.GivenName);
        }
    }
}

public class Query
{
    public string PersonFilter = "Filter";
}

public class MyContext : DbContext
{
    public DbSet<Person> Persons { get; set; }
    public DbSet<Membership> Memberships { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseInMemoryDatabase();
    }
}

public class Person
{
    public int Id { get; set; }
    public string Surname { get; set; }
    public string GivenName { get; set; }

    public List<Membership> Memberships { get; set; }
}

public class Membership
{
    public int Id { get; set; }

    public DateTime StartDate { get; set; }
    public DateTime EndDate { get; set; }

    public int PersonId { get; set; }
    public Person Person { get; set; }
}
```

**Comment by glatzert** [comment] 2016-04-28 08:09
Hm.. I do not see much difference to my model (except I have more properties).
I will have spare time next week an can try to reproduce it again in my environment

**Comment by rowanmiller** [comment] 2016-05-04 18:54
*EF Team Triage:* Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

**Closed by rowanmiller** 2016-05-04 18:54 UTC
Labels: bug, pri0

**Comment by glatzert** [comment] 2016-05-09 17:00
Besides the upper full repo code lacking a `ToListAsync()` or `FirstAsync()`, I was not able to produce that bug anymore in my environment. Unfortunately we removed the code at some point in time, and I have no idea where I could be looking for the code in TFS ... Sorry that I wasted your time.
