### ISSUE TITLE
Error on code-first migration with EntityFrameworkCore.Sqlite

### ISSUE THREAD

**Issue by yeasin90** [aspnet/EntityFramework#5969] opened 2016-07-04 11:43 UTC
I am using Visual Studio Community 2015 with Update 3. I did the below :
1. Created a UWP class library : "EF.Data2"
2. Updated the : **"Microsoft.NETCore.UniversalWindowsPlatform"** from 5.1.0 to 5.2.0 (my VS Community Update 3 has 5.1.0 as default template)
3. Installed nuget package : **"Install-Package Microsoft.EntityFrameworkCore.Sqlite"** from package manager console
4. Installed nuget package : **Install-Package Microsoft.EntityFrameworkCore.Tools –Pre**
5. Now, I tried to create my first migration with command : **Add-Migration MyFirstMigration**. But got the below error : 
![1](https://cloud.githubusercontent.com/assets/8789577/16559196/fbf9371a-420c-11e6-9d79-888cc91a3930.JPG)
6. Then following [this](http://ef.readthedocs.io/en/latest/platforms/uwp/getting-started.html), added a App.Config file. But still getting the same error : 
![2](https://cloud.githubusercontent.com/assets/8789577/16559218/44ccbb9c-420d-11e6-9a76-6bddd9c7cbac.JPG)
7. As the error is giving due to the dependency of : Microsoft.EntityFrameworkCore.Design.Core, I later installed it in my UWP class library, but still getting the error on creating migration file.

This is my project.json file : 
```
{
  "dependencies": {
    "Microsoft.EntityFrameworkCore.Design.Core": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Sqlite": "1.0.0",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.0"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

**Comment by natemcmaster** [comment] 2016-07-08 18:27
Running tooling commands on a **UWP class library** is not currently supported (tracking support for that in #6029).

We will add a more helpful error message to make this clearer.  Closing as a duplicate of https://github.com/aspnet/EntityFramework/issues/5878

@yeasin90 you can workaround this by running commands on a UWP app instead.

**Closed by natemcmaster** 2016-07-08 18:27 UTC
Labels: bug, closed-duplicate

**Comment by yeasin90** [comment] 2016-07-09 04:09
@natemcmaster  OK, thanks for suggesting the workaround, I will do with that. In that case, all my EF nuget packages and POCO, DbContext have to be inside UWP app?

**Comment by yeasin90** [comment] 2016-07-09 04:43
@natemcmaster Thanks for the workaround. In that case, i think My DbContext class has to be inside UWP app right (and POCO classes can be in UWP class library)?

**Comment by yeasin90** [comment] 2016-07-09 13:56
Yes. Finally got it working. Did the below steps : 
1. All my POCO classes and DbContext are in UWP class library with Microsoft.EntityFrameworkCore.Sqlite installed
2. Added app.config file in UWP app following #5471 and set it as startup project
3. From Package Manager Console, select UWP class library and executed migration command
4. Migration files were created in UWP class library and subsequent migrations are also applied with context.Database.Migrate().

**Comment by rubgithub** [comment] 2016-09-14 02:22
@yeasin90  Can you share your project or a simple project working?
I'm stuck on this for a week.

**Comment by yeasin90** [comment] 2016-09-14 08:54
@rubgithub : yes sure :) .. not at my desk right now, will upload the sample asap

**Comment by yeasin90** [comment] 2016-09-14 17:18
@rubgithub : created a [repo](https://github.com/yeasin90/EFCore_UWP) with my sample app. Have a look

**Comment by rubgithub** [comment] 2016-09-15 02:16
Thanks @yeasin90
