### ISSUE TITLE
EF Core 1.1 IsModified is not working

### ISSUE THREAD

**Issue by JulienM28** [aspnet/EntityFramework#7227] opened 2016-12-10 23:59 UTC
I have an issue updating my datas on an entity.

Before Updating to EF Core 1.1.0 it worked fine.

### Steps to reproduce

This one worked before but no more now. The property is not updated
```
 using (ApplicationDbContext Ctx = new ApplicationDbContext())
                    {
                        Ctx.Entry(_dico[id]).Property(key).IsModified = true;
                        Ctx.SaveChanges();
                    }
```

Here the property is correctly updated in de database.
```
 using (ApplicationDbContext Ctx = new ApplicationDbContext())
                    {
                        Ctx.Update(_dico[id]);
                        Ctx.SaveChanges();
                    }
```
Thanks for your help.

EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 64 bits
IDE: Visual Studio 2015 Update 3

**Comment by ajcvickers** [comment] 2016-12-12 17:43
@JulienM28 Could you provide more complete steps to reproduce this issue. The code you posted causes the updated value of the property to be saved in the tests I have run. Could you create a simple console app that reproduces the issue?

**Comment by JulienM28** [comment] 2016-12-13 11:45
Here is the complete method.
It's part of an Asp.Net Core Website using .net 4.6 Framework for things like System.Drawing


`public static void Update(string type, int id, string key, string value)
        {

            if (!key.Contains('.'))
            {
                if (value == "on") value = "true";
                if (value == "off") value = "false";
                Type typeObjet = Type.GetType("BookStarter.Models." + type);
                if (typeObjet == null) typeObjet = Type.GetType("BookStarter.Models.Books." + type);
                if (typeObjet == null) return;
                PropertyInfo prop = typeObjet.GetProperty(key);
                Type t = Nullable.GetUnderlyingType(prop.PropertyType) ?? prop.PropertyType;
                object nullableValue = (string.IsNullOrEmpty(value) || value == null) ? null : Convert.ChangeType(value, t);

                PropertyInfo[] containers = typeof(MemoryCache).GetProperties();
                foreach (PropertyInfo dictionary in containers)
                {
                    Type[] arguments = dictionary.PropertyType.GetGenericArguments();
                    Type valueType = arguments[1];
                    if (valueType == typeObjet)
                    {
                        var dico = typeof(MemoryCache).GetProperty(dictionary.Name).GetValue(null);
                        IDictionary _dico = dico as IDictionary;
                        prop.SetValue(_dico[id], nullableValue, null);

                        using (ApplicationDbContext Ctx = new ApplicationDbContext())
                        {
                            Ctx.Entry(_dico[id]).Property(key).IsModified = true; //This one doesn't work
                            //Ctx.Update(_dico[id]); // This does
                            Ctx.SaveChanges();
                        }
                        return;
                    }
                }
            }
            else
            {
                string[] keys = key.Split('.');

                if (keys[0] == "BookProperty")
                {
                    Book _book = Books[id];
                    foreach (BookProperty prop in _book.properties)
                    {
                        string _propName = prop.type.name;
                        if (_propName == keys[1])
                        {
                            prop.value = value;
                            using (ApplicationDbContext Ctx = new ApplicationDbContext())
                            {
                                //Ctx.Entry(prop).Property("value").IsModified = true; //This one doesn't work
                                Ctx.Update(prop); // This does
                                Ctx.SaveChanges();
                                return;
                            }
                        }
                    }

                }

            }
        }`

**Comment by ajcvickers** [comment] 2016-12-13 17:28
@JulienM28 I was able to repro this. When the entity is detached, then setting one property to modified does not change the state of the entity to Modified. As a workaround you can call `Ctx.Attach(prop);` before setting IsModified to true. This will preserve the behavior of only marking the single property as modified.

Note for triage: looks like a 1.1 regression; we should patch in 1.1.1.

**Comment by JulienM28** [comment] 2016-12-13 17:37
Thank you for your help.

**Comment by divega** [comment] 2016-12-13 19:54
Agreed we need to address this in 1.1.1. @ajcvickers let me know if you think this should be assigned to someone else.

**Comment by ajcvickers** [comment] 2017-01-05 21:54
This is fixed and merged. Leaving bug open until it is approved.

**Comment by JulienM28** [comment] 2017-01-06 08:56
Thanks.

**Comment by ajcvickers** [comment] 2017-01-13 01:17
Justification: This is a break from 1.0 where the entity would become attached to the context. Existing apps may depend on this behavior.
Risk: Low--Fix is small and constrained to this case.

**Comment by Eilon** [comment] 2017-01-19 19:55
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.

**Closed** 2017-01-19 20:23 UTC
Labels: closed-fixed, patch-approved, type-bug

**Comment by AndriySvyryd** [comment] 2017-02-24 00:29
✅ Verified

**Comment by ShaZeh** [comment] 2017-04-23 17:03
I am unsure if this is just me, but I was using EF Core 1.1.0 and was getting the same issue, I have updated all of my nuget packages to the latest, which mean EF Core 1.1.1 and I am observing the exact same issue.

If another entity was being added, the property isModified was taken into account. However if the only change to be done was the property marked as modified, nothing occurs. I have the same logic except that it is wrapped in a transaction which is commited after the SaveChangesAsync.

**Comment by ajcvickers** [comment] 2017-04-23 17:14
@ShaZeh Please open a new issue with a complete project or code listing that reproduces what you are seeing.
