### ISSUE TITLE
Apply Migrations in EF Database error page does not work

### ISSUE THREAD

**Issue by rustd** [aspnet/EntityFramework#4742] opened 2016-03-09 19:42 UTC
- Create an ASP.NET RC2 Web template
- Register a user. you will get the database error page
- Apply Migrations does not apply the migration but results in an error
![applymigrations](https://cloud.githubusercontent.com/assets/1132652/13648137/0f0246b2-e5ec-11e5-84c7-45f86050d722.PNG)

**Comment by rustd** [comment] 2016-03-09 19:43
@rowanmiller FYI

**Comment by rowanmiller** [comment] 2016-03-09 19:45
Waiting on https://github.com/aspnet/EntityFramework/pull/4733 to be merged/built so that we can debug this one further.

**Comment by divega** [comment] 2016-04-07 18:44
My understanding is that this is also blocked on #4953. I will assign it to @natemcmaster while we wait for that one to be addressed.

**Comment by natemcmaster** [comment] 2016-04-12 18:44
@rustd do you have a version of templates and a recent version of dotnet-cli that work together? I'm trying to reproduce with dotnet-cli 1.0.0-beta-002351

**Comment by rustd** [comment] 2016-04-12 20:28
@phenning?

**Comment by phenning** [comment] 2016-04-12 20:43
You should be able to repro with the latest bundle build.

**Comment by natemcmaster** [comment] 2016-04-13 00:20
The source of the bug is two fold.

1. The error is triggered because there is not database. In the error above, there is no DB yet, which is why "login failed".
2. The apply migration button executes a command that returns HTTP 404. 

![image](https://cloud.githubusercontent.com/assets/2696087/14479400/d7d6afaa-00d2-11e6-821c-c00f5bfdc9fd.png)

**Comment by natemcmaster** [comment] 2016-04-13 00:27
cc @JunTaoLuo @Tratcher are there known issues in diagnostics.entityframework?

**Comment by Tratcher** [comment] 2016-04-13 17:18
There's nothing filed.

**Comment by natemcmaster** [comment] 2016-04-13 20:31
@Tratcher @rustd my guess is the bug here is in Diagnostics.EF, not EF itself. It looks like the "Apply Migrations" button never reaches EF. The request gets lost in middleware.

**Comment by rustd** [comment] 2016-04-13 20:40
@divega who owns Diagnostics.EF and who can fix this?

**Comment by divega** [comment] 2016-04-13 22:46
This is @rowanmiller's. Will ask @smitpatel to look at it if @rowanmiller cannot do it tomorrow.

**Closed** 2016-04-18 21:13 UTC
Labels: 1 - Working, bug, pri0
