### ISSUE TITLE
Model with nullable FK fails parent child query with "Argument Types do not match"

### ISSUE THREAD

**Issue by brianro** [aspnet/EntityFramework#5522] opened 2016-05-25 20:19 UTC
**When doing this, also make sure the scenario from #5883 is taken care of - dotting thru an optional nav to get a value**

If you have a model (see attached project) with class A with a nullable id field for child class E - int? EId, querying A->E fails with "argument types do not match" error.

```c#
            var item =
                (from a
                     in db.As
                 select new A
                 {
                     Id = a.Id,
                     EId = a.EId,
                     E = new E
                     {
                         Id = a.E.Id
                     }
                 }
                     ).First();
```

In attached project query_ef_test_ac fails with the following information:

Test Name:	BugDemoEF.EFTest.query_ef_test_ae
Test FullName:	BugDemoEF.EFTest.query_ef_test_ae
Test Source:	C:\Code\General\BugDemo\src\BugDemoEF\EFTests.cs : line 205
Test Outcome:	Failed
Test Duration:	0:00:01.976

Result StackTrace:	
at System.Linq.Expressions.Expression.Bind(MemberInfo member, Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at Remotion.Linq.Clauses.SelectClause.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at BugDemoEF.EFTest.query_ef_test_ae() in C:\Code\General\BugDemo\src\BugDemoEF\EFTests.cs:line 208
Result Message:	Argument types do not match

[BugDemo.zip](https://github.com/aspnet/EntityFramework/files/282885/BugDemo.zip)

**Comment by maumar** [comment] 2016-05-27 00:57
the problem is in here

```
                     E = new E
                     {
                         Id = a.E.Id
                     }
```

Because a.E is optional navigation, a.E.Id can potentially be null. To compensate we convert the calls to int? and now we are trying to fit int? into int column.

Workaround is to use anonymous type instead:

```
            var item =
                (from a
                     in db.As
                 select new
                 {
                     Id = a.Id,
                     EId = a.EId,
                     E = new
                     {
                         Id = (int?)a.E.Id
                     }
                 }
                     ).First();
```

**Comment by divega** [comment] 2016-05-27 01:25
Talking to @maumar and @ajcvickers, we don't feel like this is RTM, because of the workaround and it doesn't seem to be that common. Thoughts?

cc @rowanmiller @anpete

**Comment by brianro** [comment] 2016-05-27 13:04
But E.Id is nullable, so why do we have to add the conversion?
What am I missing?

**Comment by smitpatel** [comment] 2016-05-27 19:21
Try this solution:
```
var item =
    (from a
            in db.As
        select new A
        {
            Id = a.Id,
            EId = a.EId,
            E = new E
            {
                Id = (int)((int?)a.E.Id ?? 0)
            }
        }
            ).First();
```
Generates following query
```
SELECT [a].[Id], [a].[CId], [a].[DId], [a].[EId], [a.E].[Id], 0
FROM [As] AS [a]
LEFT JOIN [Es] AS [a.E] ON [a].[EId] = [a.E].[Id]
ORDER BY [a].[EId]
```
And does not throw above exception. `ToList()` version runs without any exception. (`First()` fails for me because my database doesn't have any data.)

**Comment by brianro** [comment] 2016-05-27 19:35
Nope – the moment I add in the additional fields, it fails with the same error. The problem seems to be a lot deeper than just the key field and it applies to any model that has a parent with an optional child.

B.

**Comment by smitpatel** [comment] 2016-05-27 20:09
As @maumar described above
`A.E` is option navigation. (due to `Int32?` a nullable type being FK property). Therefore `A.E.Id` can have null value and the result value is nullable type of whatever is type of `A.E.Id`. And that applies to all the properties of `E`.
Therefore based on what you want, 
This should be the work-around.
```
var item =
    (from a
            in db.As
        select new A
        {
            Id = a.Id,
            EId = a.EId,
            E = a.EId.HasValue ?
            new E
            {
                Id = (int)a.E.Id
// if you add more property which are of non-nullable type, then explicit cast is needed
            }: null
        }
            ).ToList();
```
For further properties added inside `new E` you need to cast the properties if they are of non-nullable type since `a.E.Property` is still nullable type. That should work properly. (I tested above code in the project you provided and it works fine).
We can still do something about explicit cast not being required but work-around should be good enough for now.

**Comment by brianro** [comment] 2016-06-01 20:03
@smitpatel - this solutions works thanks ... uglifies my code but its functional.

**Comment by maumar** [comment] 2016-06-01 22:37
@brianro with https://github.com/aspnet/EntityFramework/commit/a24f9bc12c549d03499c2524fe2e3c57a4832c73 checked in, you should be able to just use coalesce, without any casting or HasValue checks. This is currently available in out nightly builds and will also be available in the next release

**Comment by brianro** [comment] 2016-06-01 22:40
Super news - thank you so much for getting that knocked out.
As always, I appreciate your attentiveness and dedication.
B.

**Comment by rowanmiller** [comment] 2016-06-30 17:58
When doing this, also make sure the scenario from https://github.com/aspnet/EntityFramework/issues/5883 is taken care of - dotting thru an optional nav to get a value

**Comment by maumar** [comment] 2016-07-11 19:42
fixed in 7d359abdca1046a41c1cdffed1a88d80af99fed1

**Closed by maumar** 2016-07-11 19:42 UTC
Labels: type-bug

**Comment by DmsChrisPena** [comment] 2016-07-22 04:49
I'm running into a similar problem and I've tried all the workarounds and fixes but none of them worked. Here is my code and bear in mind I'm getting the same error.

https://gist.github.com/DmsChrisPena/a8bfa560f5c2bd2565a778a67018dcd1

**Comment by rowanmiller** [comment] 2016-07-22 17:34
@DmsChrisPena the issue being tracked here is fixed. If you are still seeing the failure on our nightly builds, then please open a new issue with details.
