### ISSUE TITLE
GroupBy needs a ToList before to work

### ISSUE THREAD

**Issue by mdmoura** [aspnet/EntityFramework#7943] opened 2017-03-21 15:54 UTC
I am getting an error when using a Select after a GroupBy.

```
Exception message:
{System.ArgumentNullException: Value cannot be null.    
    
Stack trace:
{System.ArgumentNullException: Value cannot be null.
Parameter name: querySource
   at Remotion.Utilities.ArgumentUtility.CheckNotNull[T](String argumentName, T actualValue)
   at Remotion.Linq.Clauses.Expressions.QuerySourceReferenceExpression..ctor(IQuerySource querySource)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.RewriteNavigationProperties(List`1 properties, IQuerySource querySource, Expression declaringExpression, String propertyName, Type propertyType, Func`2 propertyCreator, Func`2 conditionalAccessPropertyCreator)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.<>c__DisplayClass20_0.<VisitMember>b__0(IEnumerable`1 ps, IQuerySource qs)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindPropertyExpressionCore[TResult](Expression propertyExpression, IQuerySource querySource, Func`3 propertyBinder)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindNavigationPathPropertyExpression[TResult](Expression propertyExpression, Func`3 propertyBinder)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Clauses.ResultOperators.GroupResultOperator.TransformExpressions(Func`2 transformation)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.NavigationRewritingQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitResultOperators(ObservableCollection`1 resultOperators, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel, QueryModel parentQueryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Clauses.FromClauseBase.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel, QueryModel parentQueryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, ILogger logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

### Steps to reproduce
The code is the following:

```c#

        List<OrganizationEnrolment> organizationEnrolments = 
          context.Organizations.SelectMany(x => 
          context.Users.SelectMany(y => 
          context.EnrolmentTypes.Select(z => 
            new OrganizationEnrolment {
              EnrolmentType = z,
              Organization = x,
              User = y
            })))       
          .GroupBy(u => u.Organization)          
          .Select(v => v..FirstOrDefault())
          .ToList(); 

```
If I add `ToList()` before `GroupBy` I don't get an error (but I loaded everything into memory).

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio Code

**Comment by maumar** [comment] 2017-04-01 01:07
@mdmoura  can you also post your model? (entities and dbcontext)

**Comment by ajcvickers** [comment] 2017-04-17 21:08
Removing "punt" so we can re-triage as normal.

**Comment by ajcvickers** [comment] 2017-04-19 18:14
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by maumar** [comment] 2017-05-10 20:02
This works in current bits. We produce the following query plan:

```
(QueryContext queryContext) => IEnumerable<OrganizationEnrolment> _InterceptExceptions(
    source: IEnumerable<OrganizationEnrolment> _Select(
        source: IEnumerable<IGrouping<Organization, OrganizationEnrolment>> _GroupBy(
            source: IEnumerable<TransparentIdentifier<TransparentIdentifier<Organization, User>, EnrolmentType>> _ShapedQuery(
                queryContext: queryContext, 
                shaperCommandContext: SelectExpression: 
                    SELECT [x0].[Id], [y0].[Id], [z0].[Id]
                    FROM [Organizations] AS [x0]
                    CROSS JOIN [Users] AS [y0]
                    CROSS JOIN [EnrolmentTypes] AS [z0], 
                shaper: TypedCompositeShaper<TypedCompositeShaper<BufferedOffsetEntityShaper<Organization>, Organization, BufferedOffsetEntityShaper<User>, User, TransparentIdentifier<Organization, User>>, TransparentIdentifier<Organization, User>, BufferedOffsetEntityShaper<EnrolmentType>, EnrolmentType, TransparentIdentifier<TransparentIdentifier<Organization, User>, EnrolmentType>>), 
            keySelector: (TransparentIdentifier<TransparentIdentifier<Organization, User>, EnrolmentType> t1) => new OrganizationEnrolment{ 
                EnrolmentType = t1.Inner, 
                Organization = t1.Outer.Outer, 
                User = t1.Outer.Inner 
            }
            .Organization, 
            elementSelector: (TransparentIdentifier<TransparentIdentifier<Organization, User>, EnrolmentType> t1) => new OrganizationEnrolment{ 
                EnrolmentType = t1.Inner, 
                Organization = t1.Outer.Outer, 
                User = t1.Outer.Inner 
            }
        ), 
        selector: (IGrouping<Organization, OrganizationEnrolment> v) => OrganizationEnrolment FirstOrDefault(v)), 
    contextType: Repro7943.MyContext, 
    logger: DiagnosticsLogger<Query>, 
    queryContext: queryContext)
```

**Closed by maumar** 2017-05-10 20:02 UTC
Labels: type-bug, type-investigation

**Comment by zelathon** [comment] 2017-05-17 11:31
I've also got this issue. 

```csharp
var evts =
	ctx.Set<KalisEvent>()
	   .AsNoTracking()
	   .Include(o => o.User)
			.ThenInclude(o => o.GroupRelations)
			.ThenInclude(g => g.UserGroup)
	   //
	   .GroupBy(o => o.User,
				(key, list) => new
				{
					User = key,
/*--->	*/				Groups = key.GroupRelations.Select(o => o.UserGroup.Name), //<--- This line breaks it
					Count = list.Count()
				})
	   .ToList();
```

**Comment by ErikEJ** [comment] 2017-05-17 11:36
@zelathon  EF Core version? please

**Comment by zelathon** [comment] 2017-05-17 13:07
@ErikEJ I'm using 1.1.1
