### ISSUE TITLE
Migration fails for class with multiple self references 

### ISSUE THREAD

**Issue by nooxnet** [aspnet/EntityFramework#4069] opened 2015-12-14 12:55 UTC
I have a class with two self references. Like this one:

	public class AClass
	{
		public int Id { get; set; }

		public string Name { get; set; }

		public AClass AClassFirst { get; set; }

		public AClass AClassPrevious { get; set; }
	}

when I call "dnx ef database update" I get:

	The navigation property '' cannot be added to the entity type 
	'AocSample.Models.AClass' because a navigation property with 
	the same name already exists on entity type 'AocSample.Models.AClass'.

This does not occur if there is only one self reference or if I reference another class two times. This happens with RC1 and with the source I fetched yesterday. Call Stack with line numbers attached:
[ef-error-multiple-self-references.txt](https://github.com/aspnet/EntityFramework/files/61166/ef-error-multiple-self-references.txt)

PS: First, I'm new to EF, .NET 5, etc. So I hope I do not oversee something. Second I do not know if the following is also considered an issue I should post somewhere: I had big troubles with dnvm/dnx/dnu and building EF from the source because of charset issues. Although I do not even use blanks and German umlauts in file and folder names I had chosen a Windows user name with accents in it (about 15 years ago and kept it). The problem is that cmd is not unicode aware. So the path dnvm adds (including the user directory name with the special characters) cannot be found later. I switched to PowerShell so I could executed the database migrations. But when I wanted to build EF from the source this did not work because the build script calls cmd (with dnu) multiple times. I found a hack to change the cmd charset to one which is unicode aware. I tried to set the path globally. Did not help. Finally I found that the runtimes can be installed machine wide (global). Then I could build EF with the latest runtime. But Visual Studio installed the runtime (older versions) again in the user directory. I did no try any further but finally changed my user name.

**Comment by smitpatel** [comment] 2015-12-14 17:50
dupe of #3911 ?

**Comment by nooxnet** [comment] 2015-12-15 18:08
I also found #3911 when I searched for the error. But as the staring points (as seen from the "end users" perspective) to get this error are quite different I thought to open another issue.

**Comment by smitpatel** [comment] 2015-12-15 18:36
Stack trace for both throws at same place. So likely to be same. Can you verify with latest bits if it is resolved or not?

**Comment by nooxnet** [comment] 2015-12-15 22:02
I hope I've done this correctly. I followed the instructions here: https://github.com/aspnet/EntityFramework/wiki/Getting-and-Building-the-Code
I did this already  on Sunday as I wrote above. Now I got the source again but regarding the stack trace only EntityFramework.Commands\Commands\Program.cs has changed. The error still occurs.

**Comment by rowanmiller** [comment] 2015-12-23 20:21
Confirmed that this still reproduces on latest bits (I tested against 7.0.0-rc2-16619).

Here is the code I used to reproduce. It's a console app, and you see the same behavior from `Add-Migration Test` followed by `Update-Database` as from the dnx commands (no surprise there).

```c#
using Microsoft.Data.Entity;

namespace Console
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new MyContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

            }
        }
    }

    public class MyContext : DbContext
    {
        public DbSet<AClass> AClasses { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=MyDatabase;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
        }
    }

    public class AClass
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public AClass AClassFirst { get; set; }

        public AClass AClassPrevious { get; set; }
    }
}
```

The exception comes from this line of code that is generated in the `BuildTargetModel` method of the migrations code behind file (same code is also generated for the model snapshot).

```c#
            modelBuilder.Entity("Console.RC1.AClass", b =>
                {
                    b.HasOne("Console.RC1.AClass")
                        .WithOne()
                        .HasForeignKey("Console.RC1.AClass", "AClassFirstId");
                });
```

**Closed** 2016-01-07 19:53 UTC
Labels: bug, pri0
