### ISSUE TITLE
RC2 EF LINQ Query exception

### ISSUE THREAD

**Issue by miworx** [aspnet/EntityFramework#5664] opened 2016-06-06 01:53 UTC
I have an EF7 LINQ query on RC2 that throws the following exception.   This query worked perfectly in RC1

Exception message:

```
An exception of type 'System.InvalidCastException' occurred in mscorlib.ni.dll but was not handled in user code

Additional information: Unable to cast object of type 'System.Linq.Expressions.Expression`1[System.Func`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[MIREQ_Portal.Models.ScreeningQuestionBlock,System.Collections.Generic.IEnumerable`1[MIREQ_Portal.Models.SiteService]],MIREQ_Portal.Models.SiteService],System.Nullable`1[System.Int32]]]' to type 'System.Linq.Expressions.ConstantExpression'.
```

EF Core version: 1.0.0-rc2-3002702

**Comment by divega** [comment] 2016-06-06 02:30
@miworx please provide repro model and query.

**Comment by miworx** [comment] 2016-06-06 10:45
```
@divega 
Query:
```
            var screeningblocks = (from sb in db.ScreeningQuestionBlock
                                   join ss in db.SiteService on sb.SiteService.ID equals ss.ID
                                   where ss.Site.SiteName == pSiteName &&
                                         ss.Service.ServiceName == pServiceName
                                   orderby sb.Sequence
                                   select new { sb });
```

The exception occurs on the following line attempting to process the query results:
`            foreach (var block in screeningblocks) {
`
Models:
    public class ScreeningQuestionBlock
    {
        public int ID { get; set; }
        public int Sequence { get; set; }
        [Display(Name = "Header Text")]
        public string Block_Text { get; set; }
        public virtual Site Site { get; set; }
        public virtual Service Service { get; set; }
        public virtual SiteService SiteService { get; set; }
        public virtual ICollection<ScreeningQuestion> ScreeningQuestion { get; set; }
    }

    public class SiteService
    {
        public int ID { get; set; }
        public int SiteID { get; set; }
        public virtual Site Site { get; set; }
        public int ServiceID { get; set; }
        public virtual Service Service { get; set; }
    }

    public class Site
    {
        public int ID { get; set; }
        [Required, Display(Name ="Site")]
        public string SiteName { get; set; }

        public virtual ICollection<SiteService> SiteServices { get; set; }

    }

    public class Loc
    {
        public enum LocationRequirement {None, Left_Or_Right, Both}
    }
    public class Service
    {
        public int ID { get; set; }
        [Required, Display(Name = "Service")]
        public string ServiceName { get; set; }
        [Required, Display(Name ="Body Part")]
        public string BodyPart { get; set; }
        [Display(Name = "Specificity")]
        public string Specificity { get; set; }
        [Required, Range(0,2, ErrorMessage="Must be None, Left_Or_Right, or Both") Display(Name = "Location Requirement")]
        public Loc.LocationRequirement Locationrequirement { get; set; }
        public virtual ReferralType Referral_Type { get; set; }
    }

```

**Comment by divega** [comment] 2016-06-06 18:54
@maumar @anpete does this look familiar? Have we fixed a bug like this recently?

**Comment by anpete** [comment] 2016-06-06 18:59
@divega Don't think so. Looks like complex navs.

**Comment by maumar** [comment] 2016-06-06 19:26
might be related to https://github.com/aspnet/EntityFramework/issues/4539

**Comment by miworx** [comment] 2016-06-28 00:55
@anpete Is there any update on this?   Without a fix, I'm having to remain on RC1 and feeling a little handcuffed!    If there's a workaround available, that would help.   Thanks!

**Comment by Xipooo** [comment] 2016-07-08 20:23
This is happening in RTM as well.  I can provide an example if needed but only real difference between  miworx and mine is I'm using Lambda joins.

**Comment by flipchart** [comment] 2016-07-28 17:39
Not sure if the same root cause, but I'm getting the same error message when using `.OfType` in a `.Select`. See gist for full repo: https://gist.github.com/flipchart/d44ae65458a845cd9e173b92df2f1c6d

**Comment by maumar** [comment] 2016-10-06 01:06
This is fixed in current bits

**Closed by maumar** 2016-10-06 01:06 UTC
Labels: type-bug, type-investigation
