### ISSUE TITLE
CLI throws:  Unable to retrieve project metadata. 

### ISSUE THREAD

**Issue by julielerman** [aspnet/EntityFramework#9127] opened 2017-07-08 20:58 UTC
This just popped up when I migrated a project on preview2-final to rtm-26180.
dotnet --info
```
Version:            2.0.0-preview3-006694
OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0-preview3-006694/
Microsoft .NET Core Shared Framework Host
  Version  : 2.0.0-preview3-25507-02
  Build    : cb31faee171130d052245748e11e96b27fd8d00c
```

dotnet ef runs, but dotnet ef migrations/dbcontext/database all throw this error:

```
/Users/julialerman/Dropbox/ConferenceStuff/DevTeach/2017/Share/EFCore2Previe
wWebApi/App.WebApi/obj/App.WebApi.csproj.EntityFrameworkCore.targets(20,5):
error MSB3491: Could not write lines to file "/var/folders/8w/97pyy4fd71l1gs
9hl6k4qgmc0000gn/T/ydymgqln.wey". The process cannot access the file '/var/f
olders/8w/97pyy4fd71l1gs9hl6k4qgmc0000gn/T/ydymgqln.wey' because it is being
 used by another process. [/Users/julialerman/Dropbox/ConferenceStuff/DevTea
ch/2017/Share/EFCore2PreviewWebApi/App.WebApi/App.WebApi.csproj]
Unable to retrieve project metadata. Ensure it's an MSBuild-based .NET Core
project. If you're using custom BaseIntermediateOutputPath or MSBuildProject
ExtensionsPath values, Use the --msbuildprojectextensionspath option.

```

I do not have any custom msbuild values that I know of.
I removed bin & obj folders, restored & rebuilt but still get this error.

I am also able to reproduce it on this solution: https://github.com/julielerman/OwnedEntityStoreToDbProblem

**Comment by julielerman** [comment] 2017-07-08 22:14
More data for you:
while stayin on the same version of the SDK, I reverted EF Core to preview3-* and had the same problem. Then to preview2-* and the CLI tools worked as expected.
Here is the csproj file (after I downgraded to preview2):
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <UserSecretsId>aspnet-App.WebApi-7913C0F3-3B1F-4506-9C1E-9F5ECE9BABFD</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.0-preview2-*" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.0-preview2-*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.0-preview2-*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.0-preview2-*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.0-preview2-*" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0-preview2-*" />
  </ItemGroup>
  
</Project>
```

**Comment by julielerman** [comment] 2017-07-10 12:00
Couldn't help myself and did some more experimentation. Checking assets, i noticed that I didn't always have the version of EFCore packages that I thought I was getting when fiddling with preview3 version numbers in csproj. So  setting the packagerefers all to rtm-* makes no difference. It's the Tools package that is creating the problem. Anything higher than preview3-* causes the problem. I started explicitly with the first version of the rtm packages: 2.0.0-rtm-26151 and it's failing there.

**Comment by smitpatel** [comment] 2017-07-10 16:56
Investigating this. I hit the issue with rtm-16182.
preview3 worked fine (gave error on DiagnosticSource though)

**Comment by bricelam** [comment] 2017-07-10 16:57
#8963 (Remove GetTempFileName) appears to have regressed this

cc @jbagga @Eilon @ajcvickers

**Comment by smitpatel** [comment] 2017-07-10 17:04
It is indeed culprit. I checked out packages before that commit went in (from aspnetci since the myget feed does not have packages).
It works when we generated .tmp files. It fails with above error when we started generating using tempfilename api.

**Comment by bricelam** [comment] 2017-07-10 17:06
Bummer. Let's revert it.

**Comment by smitpatel** [comment] 2017-07-10 17:53
Fixed via #9131 
I manually verified with locally built package that it works now.

**Closed by smitpatel** 2017-07-10 17:53 UTC
Labels: type-bug

**Comment by Eilon** [comment] 2017-07-18 04:56
What was the actual cause of this? That is, why did changing the temp file break?

**Comment by ajcvickers** [comment] 2017-07-19 02:40
@smitpatel @bricelam I think it's clear that the change caused the regression, but I don't know why. 🐑 Can one of you explain to us mere managers. 😉

**Comment by smitpatel** [comment] 2017-07-19 02:47
Perhaps...
From https://msdn.microsoft.com/en-us/library/d62kzs03(v=vs.110).aspx
File.Create(string) method Remarks
> The FileStream object created by this method has a default FileShare value of None; no other process or code can access the created file until the original file handle is closed.
