### ISSUE TITLE
Migrations generates invalid Guid Add column

### ISSUE THREAD

**Issue by martinKupec** [aspnet/EntityFramework#3265] opened 2015-09-29 19:47 UTC
Let's have simple code using Beta7:
```
using System;
using Microsoft.Data.Entity;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Microsoft.Framework.Logging;
using Microsoft.Data.Entity.Infrastructure;

namespace EFtest
{
	public class TestEntiy
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public virtual long Id { get; set; }
		//Add in second Migration
		public virtual Guid Problem { get; set; }
	}

	public class TestContext : DbContext
	{
		public TestContext()
		{
			var loggerFactory = this.GetService<ILoggerFactory> ();
			loggerFactory.AddConsole (LogLevel.Verbose);
		}

		protected override void OnConfiguring (DbContextOptionsBuilder optionsBuilder)
		{
			optionsBuilder.UseSqlite ("Data Source=test.s3db");
			base.OnConfiguring (optionsBuilder);
		}

		public DbSet<TestEntiy> Test { get; set; }
	}

	class Startup {
		public void Configure()
		{
		}
	}

	class MainClass
	{
		
		public static void Main (string[] args)
		{
			using (var context = new TestContext ()) {	
				context.Database.Migrate();
				context.Test.Load ();

			}
		}
	}
}
```
The marked part will be added after initial migration is created.
It than generates following script:
```
CREATE TABLE IF NOT EXISTS "__MigrationHistory" (
    "MigrationId" TEXT NOT NULL CONSTRAINT "PK_HistoryRow" PRIMARY KEY,
    "ProductVersion" TEXT NOT NULL
);

CREATE TABLE "TestEntiy" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_TestEntiy" PRIMARY KEY AUTOINCREMENT
);
INSERT INTO "__MigrationHistory" ("MigrationId", "ProductVersion")
VALUES ('20150929193348_Initial', '7.0.0-beta7-15540');;

ALTER TABLE "TestEntiy" ADD "Problem" BLOB NOT NULL DEFAULT 00000000-0000-0000-0000-000000000000;
INSERT INTO "__MigrationHistory" ("MigrationId", "ProductVersion")
VALUES ('20150929193400_Error', '7.0.0-beta7-15540');;
```
Problem is, that the "0000000-..." part is invalid. Is should probably be in quotes.
I get error: `SQLite Error 1: 'near "-": syntax error'`

**Comment by bricelam** [comment] 2015-09-30 22:09
It [looks like](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Relational/Storage/RelationalSqlGenerator.cs#L113-L114) this may be fixed in the nightly builds.

**Comment by mikary** [comment] 2015-10-16 16:21
Confirmed this has been fixed in beta8 for both Sqlite and SqlServer

**Closed** 2015-10-16 16:21 UTC
Labels: pri0, task
