### ISSUE TITLE
insertion with invalid foreign key throws no exception:

### ISSUE THREAD

**Issue by kennywangjin** [aspnet/EntityFramework#3168] opened 2015-09-18 02:02 UTC
I tried to add an entity with invalid foreign key, after save changes, no exception was thrown and no data was inserted. like below:

```c#
public class CostCenter
{
     public int Id { get; set;}
     public string Name { get; set;}
}

public class Computer
{
     public int Id { get; set;}
     public string Name { get; set; }
     public int CostCenterId { get; set;}

    public virtual CostCenter CostCenter {get; set; }
}
```

```
dbContext.Computer.Add( new Computer { Name="John's Computer", CostCenterId=100});
dbContext.SaveChanges();
```

there is no CostCenter with id of 100, but entity framework throws no exception and indicates that the operation is successfully done. however, I found no record inserted in database.

**Comment by rowanmiller** [comment] 2015-09-18 18:42
@kennywangjin the database should enforce this, is there a reason the database is allowing this data to be saved?

**Comment by kennywangjin** [comment] 2015-09-19 01:35
i let conventions to build the database, and the table foreign keys are well configured. If i set the foreign key with a valid id, item will be saved. if with a invalid id, no data is saved, and NO exception! That's the point. Normally it should throw some exception to inform the invalid exception.

**Comment by rowanmiller** [comment] 2015-10-14 18:37
@mikary can you test the repro code.

**Comment by mikary** [comment] 2015-10-19 16:11
I attempted to reproduce the issue with EntityFramework.SqlServer 7.0.0-beta8 and I did not see the described issue.

Here is the full source for what I ran:
```cs
using System;
using System.Data.SqlClient;
using Microsoft.Data.Entity;

namespace ForeignKeyRepro
{
    public class Program
    {
        public void Main(string[] args)
        {
            using (var dbContext = new ReproContext())
            {
                dbContext.Database.EnsureDeleted();
                dbContext.Database.EnsureCreated();

                try
                {
                    dbContext.Computer.Add(new Computer { Name = "John's Computer", CostCenterId = 100 });
                    dbContext.SaveChanges();
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                    Console.WriteLine(ex.StackTrace);
                }
            }
        }
    }

    public class ReproContext : DbContext
    {
        public DbSet<CostCenter> CostCenter { get; set; }
        public DbSet<Computer> Computer { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var connectionString = new SqlConnectionStringBuilder
            {
                DataSource = @"(localdb)\MSSQLLocalDB",
                MultipleActiveResultSets = true,
                InitialCatalog = "FKRepro",
                IntegratedSecurity = true,
                ConnectTimeout = 30
            }.ConnectionString;

            optionsBuilder.UseSqlServer(connectionString);
        }
    }

    public class CostCenter
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public class Computer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int CostCenterId { get; set; }

        public virtual CostCenter CostCenter { get; set; }
    }
}
```

The only way I can produce something similar to the described behavior is to use Sqlite with explicitly suppressed FK enforcement `optionsBuilder.UseSqlite("Data Source=fkRepro.db").SuppressForeignKeyEnforcement()`

@kennywangjin is there anything I'm missing in the setup for this issue? If you are still encountering this issue and can provide us with complete source code to reproduce the issue it would be very helpful in diagnosing the issue.

**Comment by kennywangjin** [comment] 2015-10-20 02:24
I have three projects: DataModels for database models, WebApi for web api and WebApp for application.
In webapi, I use SaveChangesAsync to save entity. 
In web app, I use httpclient to send request to webapi in async mode. 
Normally, if the foreign key invalid, web api should return 500 error to the app and then the app return 500 error to the client browser. But in my app, there is nothing happened and app returns 200 result without content.
Maybe it is not the bug of EF, but the webapi or the async thread aborted.
Thanks for the support.

**Comment by mikary** [comment] 2015-10-20 16:16
I double checked the `SaveChangesAsync()` code path to be sure it was behaving properly and it also appears to be behaving properly. It looks like there isn't anything actionable that I can do for this issue at the moment, so I'm going to go ahead and close it out.

@kennywangjin if you continue to experience this issue and are able to produce a standalone reproduction of the problem, please feel free to open a new issue so we can look into it.

**Closed by mikary** 2015-10-20 16:16 UTC
Labels: bug, pri0
