### ISSUE TITLE
GroupBy multiple keys throws exception in 1.0.1

### ISSUE THREAD

**Issue by StefH** [aspnet/EntityFramework#6620] opened 2016-09-27 18:39 UTC
### GroupBy multiple keys throws exception

Example code

``` c#
var expected = _context.Posts
  .GroupBy(x => new { x.BlogId, x.PostDate })
  .OrderBy(x => x.Key.PostDate)
  .ToArray();
```
### Exception + StackTrace is like:

```
Test Name:  System.Linq.Dynamic.Core.Tests.EntitiesTests.Entities_GroupBy_MultiKey
Test FullName:  System.Linq.Dynamic.Core.Tests.EntitiesTests.Entities_GroupBy_MultiKey
Test Source:    C:\Projects\GitHub\System.Linq.Dynamic.Core\test\System.Linq.Dynamic.Core.Tests\EntitiesTests.GroupBy.cs : line 46
Test Outcome:   Failed
Test Duration:  0:00:00,097

Result StackTrace:  
at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0, Expression arg1, Expression arg2, Expression arg3)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.TrackEntitiesInResults[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Linq.Dynamic.Core.Tests.EntitiesTests.Entities_GroupBy_MultiKey() in C:\Projects\GitHub\System.Linq.Dynamic.Core\test\System.Linq.Dynamic.Core.Tests\EntitiesTests.GroupBy.cs:line 48
Result Message: Expression of type 'System.Collections.Generic.List`1[System.Func`2[System.Linq.IGrouping`2[<>f__AnonymousType2`2[System.Int32,System.DateTime],System.Linq.Dynamic.Core.Tests.Helpers.Entities.Post],System.Object]]' cannot be used for parameter of type 'System.Collections.Generic.IList`1[System.Func`2[System.Linq.Dynamic.Core.Tests.Helpers.Entities.Post,System.Object]]' of method 'System.Collections.Generic.IEnumerable`1[System.Linq.IGrouping`2[<>f__AnonymousType2`2[System.Int32,System.DateTime],System.Linq.Dynamic.Core.Tests.Helpers.Entities.Post]] _TrackGroupedEntities[<>f__AnonymousType2`2,Post](System.Collections.Generic.IEnumerable`1[System.Linq.IGrouping`2[<>f__AnonymousType2`2[System.Int32,System.DateTime],System.Linq.Dynamic.Core.Tests.Helpers.Entities.Post]], Microsoft.EntityFrameworkCore.Query.QueryContext, System.Collections.Generic.IList`1[Microsoft.EntityFrameworkCore.Query.Internal.EntityTrackingInfo], System.Collections.Generic.IList`1[System.Func`2[System.Linq.Dynamic.Core.Tests.Helpers.Entities.Post,System.Object]])'
```
### Further technical details

EF Core version: 1.0.1
Operating system: Windows 10
Visual Studio version: (VS 2015)

Other details about my project setup:
https://github.com/StefH/System.Linq.Dynamic.Core/blob/_reproduce_EF_GroupByError/test/System.Linq.Dynamic.Core.Tests/EntitiesTests.GroupBy.cs#L43

**Comment by maumar** [comment] 2016-09-27 19:59
@StefH did it work for you in 1.0.0

**Comment by StefH** [comment] 2016-09-27 20:43
This specific test worked fine in 1.0.0

**Comment by maumar** [comment] 2016-09-27 20:46
assigning for investigation for 1.0.2 since it seems to be a regression introduced in 1.0.1

**Comment by maumar** [comment] 2016-09-27 22:42
Confirmed this is a regression, introduced in bd1aa144442e0463b9d4e0eb33ce0897a728126c

**Comment by maumar** [comment] 2016-09-28 22:02
fixed in 24e5c2d7ef93683bbc184b9e6d050e7fdbfda42b

**Comment by divega** [comment] 2016-10-12 14:45
Reopening to go through proper approval process.

**Comment by Eilon** [comment] 2016-11-01 05:55
This patch is **approved**, please ensure it is merged into the correct branch and building as part of the patch train.

**Comment by maumar** [comment] 2016-11-01 23:13
checked into dev and ported to feature/1.2.0, closing

**Comment by Eilon** [comment] 2016-11-02 06:10
@maumar this needs to be in the **patch** branch, which is neither `dev` nor `feature/1.2.0` - was this merged into the correct place?

**Comment by maumar** [comment] 2016-11-02 18:01
its in the patch branch also, closing

**Closed by maumar** 2016-11-02 18:01 UTC
Labels: closed-fixed, patch-approved, type-bug
