### ISSUE TITLE
Failure when adding migration: Value cannot be null, parameter name: builder

### ISSUE THREAD

**Issue by haydenmc** [aspnet/EntityFramework#5657] opened 2016-06-04 06:29 UTC
### Steps to reproduce
1. Clone [this commit](https://github.com/haydenmc/TheoremSlackBot/tree/5607b0fb5502fd7eb894d89810bb9eb578ca3b34)
2. Run `dotnet restore`, `dotnet ef migrations add Initial`

I suspect the failure has to do with the inherited fields in `EventModel.cs`, `MessageEventModel.cs`, and `PresenceChangeEventModel.cs` (and perhaps their relationships with `UserModel.cs`, `ChannelModel.cs`).

### The issue
Failure with the following stack trace
```
System.ArgumentNullException: Value cannot be null.
Parameter name: builder
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity(Type type)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.FindSets(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.RelationalModelSource.FindSets(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.Execute(CommonOptions commonOptions, String name, String outputDir, String context, String environment, Action`1 reporter)
   at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
Value cannot be null.
Parameter name: builder
```

### Further technical details

EF Core version: 1.0.0-rc2-3002702
Operating system: RS1 14359
Visual Studio version: n/a

**Comment by JosephGarrone** [comment] 2016-06-06 00:55
Having same issue with RC1-Update1. (Exact same stacktrace from `Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)` onwards. Occurs during my startup seeding process.

**Comment by smitpatel** [comment] 2016-06-06 21:21
Confirmed repro in RC2-final but fixed in latest dev.
Tested using night packages.
Root cause was same as #5547

**Closed by smitpatel** 2016-06-06 21:21 UTC
Labels: investigation-needed

**Comment by JosephGarrone** [comment] 2016-06-07 01:53
Thanks @smitpatel. Sadly can't update to RC2 atm so thanks for linking the root cause!
