### ISSUE TITLE
Memory leak after Dispose and SaveChanges

### ISSUE THREAD

**Issue by tedypranolo** [aspnet/EntityFramework#4369] opened 2016-01-22 05:07 UTC
In ```7.0.0-rc1-final``` this simple model
```cs
public class SimpleContext:DbContext
{
    public DbSet<Person> Persons { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=localhost;Database=SimpleTest;integrated security=True;");
    }
}
public class Person
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```
tested using
```cs
using (var ctx = new SimpleContext())
{
    ctx.Database.EnsureDeleted();
    ctx.Database.EnsureCreated();
    for (int i = 0; i < 1000; i++)
    {
        ctx.Add(new Person());
    }
    ctx.SaveChanges();
}
GC.Collect();
GC.WaitForPendingFinalizers();
```
With the Memory Usage tool in Visual Studio 2015, I can see that outside of the ```using``` block all entities are retained in memory. Even after ```GC.Collect()``` all 1000 Persons including their ChangeTracking are still in memory.
However if the ```SaveChanges()``` line is taken out, the entities are released outside of the using block as expected.
Am I doing something wrong?

**Comment by ajcvickers** [comment] 2016-02-04 21:24
Disposing the context is not enough for entities that are tracked by the context to be garbage collected. To get the entities to be garbage collected the context instance must also go out of scope so that it can be collected. It would be extra work to free up all references to entities as part of dispose when the application can instead allow or force the context to go out of scope, since it is unusable after dispose anyway.

I have been unable to reproduce the issue where calling SaveChanges changes this behavior. I get no entities collected in either case if the context is still in scope, and all entities collected in either case when the context is out of scope.

**Comment by tedypranolo** [comment] 2016-02-05 06:19
My mistake was assuming that ```ctx``` is out of scope as soon the execution exits the using block. When in fact, it has to exit its outer block ```SomeMethod``` before it can be garbage collected.
```cs
public void SomeMethod() {
    using (var ctx = new SimpleContext())
   {
       ...
   }
   //ctx is still not yet released at this point
}
```

Now that I know where I made the mistake, this point is moot. But the SaveChanges difference I was referring to is this:
#### With Savechanges()
```cs
        public static void Add()
        {
            using (var ctx = new SimpleContext())
            {
                for (int i = 0; i < 1000; i++)
                {
                    ctx.Add(new Person());
                }
                ctx.SaveChanges();
            }
           Debugger.Break();
        }
``` 
Snapshot at Debugger.Break()
![withsavechanges](https://cloud.githubusercontent.com/assets/3522930/12839120/bccd2d0c-cc10-11e5-9dbb-fd0998aa441f.png)
---
#### Without SaveChanges()
```cs
        public static void Add()
        {
            using (var ctx = new SimpleContext())
            {
                for (int i = 0; i < 1000; i++)
                {
                    ctx.Add(new Person());
                }
                //ctx.SaveChanges();
            }
           Debugger.Break();
        }
``` 
Snapshot at Debugger.Break()
![withoutsavechanges](https://cloud.githubusercontent.com/assets/3522930/12839121/bcd3e25a-cc10-11e5-8a71-e871d494f97d.png)

Thank you for your help.

**Closed** 2016-02-05 21:05 UTC
Labels: bug, pri0
