### ISSUE TITLE
Remove AsMigrationsEnabled (consolidate on AsRelational)

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#1525] opened 2015-02-02 23:32 UTC
Possible now that migrations is merged into relational

**Comment by bricelam** [comment] 2015-02-02 23:40
Dupe of #1149?

**Comment by rowanmiller** [comment] 2015-02-02 23:42
Yes... will close the other one since this is more specific :smile:

**Closed** 2015-02-05 20:05 UTC
Labels: 2 - Done
