### ISSUE TITLE
when i have 2 counts in a select statement, only the last one gets executed

### ISSUE THREAD

**Issue by xrkolovos** [aspnet/EntityFramework#4076] opened 2015-12-14 20:10 UTC
From this row the sql statement that's created has only count for the last one. 

```c#
var q = (from u in cntx.Partners
                     select new
                     {
                         u.Id,
                         u.Title,
                         u.Email,
                         u.Phone,
                         Customers_Count = u.Customers.Count(x => x.PartnertId == u.Id),
                         Contracts_Count = u.Contracts.Count(x => x.PartnerId == u.Id)
                     });
```

SQL

```SQL
SELECT (
    SELECT COUNT(*)
    FROM [Contracts] AS [e]
    WHERE [s].[Id] = [e].[PartnerId]
), [s].[Id], [s].[Title], [s].[Email], [s].[Phone]
FROM [Partners] AS [s]
ORDER BY [s].[Title]
OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY
```

if i remove the last one i get this

```SQL
SELECT (
    SELECT COUNT(*)
    FROM [Customers] AS [e]
    WHERE [s].[Id] = [e].[PartnerId]
), [s].[Id], [s].[Title], [s].[Email], [s].[Phone]
FROM [Partners] AS [s]
ORDER BY [s].[Title]
OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY
```

**Comment by rowanmiller** [comment] 2015-12-22 22:47
@maumar expect this is a dupe of one you are already tracking for rc2. Feel free to close if it is.

**Comment by xrkolovos** [comment] 2016-04-06 15:43
hello, any news on this?

**Comment by maumar** [comment] 2016-04-06 17:54
@xrkolovos sorry for the late reply. This issue is now fixed and will be available in RC2 release.
When run on our current bits, the following query is produced:

```
SELECT [u].[Id], [u].[Title], [u].[Email], [u].[Phone], (
    SELECT COUNT(*)
    FROM [Customers] AS [x1]
    WHERE ([x1].[PartnertId] = [u].[Id]) AND ([u].[Id] = [x1].[PartnerId])
), (
    SELECT COUNT(*)
    FROM [Contracts] AS [x2]
    WHERE ([x2].[PartnerId] = [u].[Id]) AND ([u].[Id] = [x2].[PartnerId])
)
FROM [Partners] AS [u]
```

**Closed by maumar** 2016-04-06 17:54 UTC
Labels: bug, pri0

**Comment by xrkolovos** [comment] 2016-04-07 14:37
nice work. thank you for your reply
