### ISSUE TITLE
Using Include in GraphUpdatesTestBase throws 

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#3283] opened 2015-09-30 20:39 UTC
The current code uses multiple queries to load a full graph into memory. Changing the code to use include causes exception below to be thrown.

```C#
protected static Root LoadFullGraph(GraphUpdatesContext context, Expression<Func<Root, bool>> predicate = null)
{
    var query = context.Roots
        .Include(e => e.RequiredChildren).ThenInclude(e => e.Children)
        .Include(e => e.OptionalChildren).ThenInclude(e => e.Children)
        .Include(e => e.RequiredSingle).ThenInclude(e => e.Single)
        .Include(e => e.RequiredNonPkSingle).ThenInclude(e => e.Single)
        .Include(e => e.OptionalSingle).ThenInclude(e => e.Single)
        .Include(e => e.RequiredChildrenAk).ThenInclude(e => e.Children)
        .Include(e => e.OptionalChildrenAk).ThenInclude(e => e.Children)
        .Include(e => e.RequiredSingleAk).ThenInclude(e => e.Single)
        .Include(e => e.RequiredNonPkSingleAk).ThenInclude(e => e.Single)
        .Include(e => e.OptionalSingleAk).ThenInclude(e => e.Single);

    var loadedGraph = predicate == null
        ? query.Single()
        : query.Single(predicate);

    return loadedGraph;
}
```

```
Test 'Microsoft.Data.Entity.SqlServer.FunctionalTests.GraphUpdatesWithSequenceSqlServerTest.Required_one_to_one_are_cascade_deleted' failed:
	System.Data.SqlClient.SqlException : Invalid column name 'AlternateId'.
	at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
	at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
	at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
	at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
	at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
	at System.Data.SqlClient.SqlDataReader.get_MetaData()
	at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
	at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
	at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
	at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
	at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
	at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
	at System.Data.Common.DbCommand.ExecuteReader()
	Query\Internal\QueryingEnumerable.cs(71,0): at Microsoft.Data.Entity.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	Extensions\EnumerableExtensions.cs(15,0): at Microsoft.Data.Entity.EnumerableExtensions.<Finally>d__0`1.MoveNext()
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	Extensions\EnumerableExtensions.cs(15,0): at Microsoft.Data.Entity.EnumerableExtensions.<Finally>d__0`1.MoveNext()
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	Extensions\EnumerableExtensions.cs(15,0): at Microsoft.Data.Entity.EnumerableExtensions.<Finally>d__0`1.MoveNext()
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	Extensions\EnumerableExtensions.cs(15,0): at Microsoft.Data.Entity.EnumerableExtensions.<Finally>d__0`1.MoveNext()
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	Extensions\EnumerableExtensions.cs(15,0): at Microsoft.Data.Entity.EnumerableExtensions.<Finally>d__0`1.MoveNext()
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	Extensions\EnumerableExtensions.cs(15,0): at Microsoft.Data.Entity.EnumerableExtensions.<Finally>d__0`1.MoveNext()
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	Extensions\EnumerableExtensions.cs(15,0): at Microsoft.Data.Entity.EnumerableExtensions.<Finally>d__0`1.MoveNext()
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	Extensions\EnumerableExtensions.cs(15,0): at Microsoft.Data.Entity.EnumerableExtensions.<Finally>d__0`1.MoveNext()
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	Extensions\EnumerableExtensions.cs(15,0): at Microsoft.Data.Entity.EnumerableExtensions.<Finally>d__0`1.MoveNext()
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	Extensions\EnumerableExtensions.cs(15,0): at Microsoft.Data.Entity.EnumerableExtensions.<Finally>d__0`1.MoveNext()
	at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
	at lambda_method(Closure )
	Query\LinqOperatorProvider.cs(132,0): at Microsoft.Data.Entity.Query.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
	at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
	Query\QueryCompiler.cs(121,0): at Microsoft.Data.Entity.Query.QueryCompiler.<>c__DisplayClass16_1`1.<CompileQuery>b__1(QueryContext qc)
	Query\QueryCompiler.cs(67,0): at Microsoft.Data.Entity.Query.QueryCompiler.Execute[TResult](Expression query)
	Query\Internal\EntityQueryProvider.cs(37,0): at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
	at System.Linq.Queryable.Single[TSource](IQueryable`1 source)
	GraphUpdatesTestBase.cs(2554,0): at Microsoft.Data.Entity.FunctionalTests.GraphUpdatesTestBase`2.LoadFullGraph(GraphUpdatesContext context, Expression`1 predicate)
	GraphUpdatesTestBase.cs(1967,0): at Microsoft.Data.Entity.FunctionalTests.GraphUpdatesTestBase`2.Required_one_to_one_are_cascade_deleted()
```

**Comment by maumar** [comment] 2015-10-28 21:19
the issue is now fixed, most likely either due to 41ad57ad2f3755c5e35b51d939fab52b489ce738 or 0e0793b6b98cbbcd3c2ea52409b5e465aa81f1d7

**Closed** 2015-10-29 21:08 UTC
Labels: bug, pri0
