### ISSUE TITLE
Include work incorrectly when it comes with OrderByDescending and Skip together

### ISSUE THREAD

**Issue by sgjsakura** [aspnet/EntityFramework#3524] opened 2015-10-23 09:02 UTC
The following code can demostrate this problem:
```C#

// Sample database with object relations.
public class TestDataModel : DbContext
{
	public virtual DbSet<Picture> Pictures { get; set; }
	public virtual DbSet<PicturePackage> PicturePackages { get; set; }
}

public class Picture
{
	public int PackageId { get; set; }

	[Required]
	[ForeignKey(nameof(PackageId))]
	public PicturePackage Package { get; set; }

	[Key]
	public int Id { get; set; }

}

public class PicturePackage
{
	[InverseProperty(nameof(Picture.Package))]
	public virtual ICollection<Picture> Pictures { get; set; }

	[Key]
	public int Id { get; set; }
}

// Querys
var result = Sql.PicturePackages.Include(p => p.Pictures).OrderByDescending(i => i.Id).Skip(2);

```
In the above case, some item in `result` will incorrectly report its `Pictures` collection is empty (However they own at least one picture indeed). This problem never occurs when removing `Skip` or changing `OrderByDescending` into `OrderBy`. The problem seems has been there since Beta4, please fix it asap and many thanks!

**Comment by sandorfr** [comment] 2015-10-29 14:14
I can confirm the issue and it also happens with orderBy on beta8

**Comment by mikary** [comment] 2015-12-15 21:55
Attempting to reproduce this issue, the query executes two commands:
```sql
SELECT [p].[Id]
FROM [PicturePackage] AS [p]
ORDER BY [p].[Id] DESC
OFFSET @__p_0 ROWS


SELECT [p].[Id], [p].[PackageId]
FROM [Picture] AS [p]
INNER JOIN (
    SELECT DISTINCT [t0].*
    FROM (
        SELECT [p].[Id]
        FROM [PicturePackage] AS [p]
        ORDER BY [p].[Id] DESC
        OFFSET @__p_0 ROWS
    ) AS [t0]
) AS [p0] ON [p].[PackageId] = [p0].[Id]
```

I attempted to reproduce on both Sqlite and SqlServer, both with sequential and somewhat scrambled `Picture` Id values. Each time it appeared the expected number of `PicturePackage` and `Picture` instances were materialized.

```cs
    public class Program
    {
        public void Main(string[] args)
        {
            using (var Sql = new TestDataModel())
            {
                Sql.Database.EnsureDeleted();
                Sql.Database.EnsureCreated();

                for (var index = 0; index < 5; index++)
                {
                    var package = new PicturePackage { Pictures = new List<Picture>() };
                    Sql.PicturePackages.Add(package);
                    Sql.SaveChanges();
                }

                for (var index = 0; index < 5; index++)
                {
                    foreach (var package in Sql.PicturePackages)
                    {
                        var picture = new Picture();
                        package.Pictures.Add(picture);
                        Sql.Pictures.Add(picture);
                    }
                }

                Sql.SaveChanges();
            }

            using (var Sql = new TestDataModel())
            {
                // Querys
                var result = Sql.PicturePackages.Include(p => p.Pictures).OrderByDescending(i => i.Id).Skip(2).ToList();

                // (5 - 2) * 5 = 15
                var count = result.SelectMany(package => package.Pictures).Distinct().Count();
            }
        }
    }
```

This looks similar to #4083 which fails because the ordering expectations of the `IncludeCollectionIterator`. This could also relate to  #4085 if the second query results are not in the expected order due to indexes or provider implementation details.

**Comment by mikary** [comment] 2015-12-15 22:06
@rowanmiller Closing this one as a duplicate of #4083 because they appear to have the same root cause.

**Closed by mikary** 2015-12-15 22:06 UTC
Labels: bug, pri0
