### ISSUE TITLE
OrderBy & ThenBy Throws Error

### ISSUE THREAD

**Issue by LorenDorez** [aspnet/EntityFramework#4480] opened 2016-02-03 22:16 UTC
When i try and use an OrderBy and ThenBy on my EF IQueryable i get an error

InvalidCastException: Unable to cast object of type 'System.Linq.Expressions.FieldExpression' to type 'System.Linq.Expressions.ParameterExpression'

Below is the Code 

```
            IQueryable<PropertyViolation> result = _db.PropertyViolation;
            result = result.Include(x => x.Property);
            result = result.Include(x => x.Violation).ThenInclude(x => x.ViolationType);

            result = result.OrderBy(x => x.Property.Name).ThenBy(q => q.Violation.Name);

            return await result.ToListAsync();
```

If i removed the ThenBy on the OrderBy Statement the error disappears. Below is also how the SQL Query looks as well. When i add the Order By it adds an Additional JOIN even though i have already joined the Property Table

```
SELECT [x].[PropertyViolationId], [x].[CreatedDate], [x].[CreatedUserId], [x].[LastUpdatedDate], [x].[LastUpdatedUserId], [x].[PropertyId], [x].[ViolationId], [v].[ViolationId], [v].[CreatedDate], [v].[CreatedUserId], [v].[LastUpdatedDate], [v].[LastUpdatedUserId], [v].[Name], [v].[ViolationCategoryId], [v].[ViolationTypeId], [v0].[ViolationTypeId], [v0].[CreatedDate], [v0].[CreatedUserId], [v0].[LastUpdatedDate], [v0].[LastUpdatedUserId], [v0].[Name], [p].[PropertyId], [p].[AutoEmailReport], [p].[City], [p].[CreatedDate], [p].[CreatedUserId], [p].[IsActive], [p].[LastUpdatedDate], [p].[LastUpdatedUserId], [p].[Name], [p].[ParkingGuidelines], [p].[ParkingRecordEditingPM], [p].[ParkingTarget], [p].[PermitDeliveryTypeId], [p].[PermitPayByHOA], [p].[PermitPerAddress], [p].[PermitPerHOA], [p].[PermitPrice], [p].[PermitValidityPeriodId], [p].[PermitVehicleAssigned], [p].[PropertyManagementCompanyId], [p].[State], [p].[StreetAddress], [p].[UseParking], [p].[UsePermit], [p].[ViolationWorkflowPeriodId], [p].[ViolationWorkflowUseTime], [p].[Zip]
FROM [PropertyViolation] AS [x]
INNER JOIN [Property] AS [x.Property] ON [x].[PropertyId] = [x.Property].[PropertyId]
INNER JOIN [Violation] AS [v] ON [x].[ViolationId] = [v].[ViolationId]
INNER JOIN [ViolationType] AS [v0] ON [v].[ViolationTypeId] = [v0].[ViolationTypeId]
INNER JOIN [Property] AS [p] ON [x].[PropertyId] = [p].[PropertyId]
ORDER BY [x.Property].[Name]
```

**Comment by rowanmiller** [comment] 2016-02-05 19:22
@maumar if this isn't covered by your current work then let us know

**Comment by maumar** [comment] 2016-02-05 19:24
@rowanmiller it is not, but looks like my area so I can work on it once I'm done with LOJ

**Comment by maumar** [comment] 2016-03-05 00:06
Per @mikary request, reassigning to him

**Comment by mikary** [comment] 2016-03-07 18:55
Attempted to reproduce the issue on current dev (with a rough approximation of the model) and did not observe the exception being thrown.

Generated SQL:
```SQL
SELECT [x].[PropertyViolationId], [x].[PropertyId], [x].[ViolationId], [v].[ViolationId], [v].[Name], [v].[ViolationTypeViolationTypeId], [v0].[ViolationTypeId], [p].[PropertyId], [p].[Name]
FROM [PropertyViolation] AS [x]
INNER JOIN [Violations] AS [x.Violation] ON [x].[ViolationId] = [x.Violation].[ViolationId]
INNER JOIN [Properties] AS [x.Property] ON [x].[PropertyId] = [x.Property].[PropertyId]
INNER JOIN [Violations] AS [v] ON [x].[ViolationId] = [v].[ViolationId]
LEFT JOIN [ViolationTypes] AS [v0] ON [v].[ViolationTypeViolationTypeId] = [v0].[ViolationTypeId]
INNER JOIN [Properties] AS [p] ON [x].[PropertyId] = [p].[PropertyId]
ORDER BY [x.Property].[Name], [x.Violation].[Name]
```

Note: If the navigations for property or violation are optional, the order by is evaluated on the client #4588.

SQL for optional navigations:
```SQL
SELECT [x].[PropertyViolationId], [x].[PropertyId], [x].[ViolationId], [x.Violation].[ViolationId], [x.Violation].[Name], [x.Violation].[ViolationTypeViolationTypeId], [v].[ViolationId], [v].[Name], [v].[ViolationTypeViolationTypeId], [v0].[ViolationTypeId], [p].[PropertyId], [p].[Name]
FROM [PropertyViolation] AS [x]
LEFT JOIN [Violations] AS [x.Violation] ON [x].[ViolationId] = [x.Violation].[ViolationId]
LEFT JOIN [Violations] AS [v] ON [x].[ViolationId] = [v].[ViolationId]
LEFT JOIN [ViolationTypes] AS [v0] ON [v].[ViolationTypeViolationTypeId] = [v0].[ViolationTypeId]
LEFT JOIN [Properties] AS [p] ON [x].[PropertyId] = [p].[PropertyId]
ORDER BY [x].[ViolationId]
```

This issue appears to have been resolved by other recent fixes.

**Closed by mikary** 2016-03-07 18:55 UTC
Labels: bug, pri0
