### ISSUE TITLE
Error when specifying AttachDbFileName in connection string

### ISSUE THREAD

**Issue by XiaoweiJia** [aspnet/EntityFramework#2810] opened 2015-08-10 19:49 UTC
_Edit: look at https://github.com/aspnet/EntityFramework/issues/2810#issuecomment-243402108 for details on the bug._

When specifying AttachDbFileName in connection string, the following error appear: Unable to Attach database file as database xxxxxxx. 
Please advise.

Thanks

**Comment by natemcmaster** [comment] 2015-08-11 17:04
Please provide [more details](https://github.com/aspnet/Home/blob/dev/CONTRIBUTING.md#filing-issues) about your issue.

**Comment by XiaoweiJia** [comment] 2015-08-11 18:55
I am trying to use migration commands to generate database: "dnx . ef migration apply". I get an error saying the database file cannot be attached as database xxxx but if I remove the "AttachDbFileName" section, it works fine and the database file is created in default location.
Please see my code in ConfigureServices.
public void ConfigureServices(IServiceCollection services)
        {
            var connection = @"Data Source=(LocalDB)\mssqllocaldb;Integrated Security=True;Initial Catalog=SampleDb;AttachDbFileName=D:\SampleDb.mdf";
            services.AddEntityFramework().AddSqlServer().AddDbContext<ApplicationDbContext>(options => options.UseSqlServer(connection));
        }

**Comment by natemcmaster** [comment] 2015-08-11 19:01
Thanks for updating. This is not a bug in EF 7. We pass-through the connection string to SqlClient. There may be a problem with your localdb setup.

**Comment by bricelam** [comment] 2015-08-12 22:14
Cross-reference: [Cannot attach database file when using Entity Framework 7 Migration commands](http://stackoverflow.com/q/31928014/475031) (on StackOverflow)

**Comment by axelheer** [comment] 2016-08-30 10:46
I still think this is a bug, or a missing feature compared to EF6. It's quite annoying anyway.

* `EnsureDeleted` changes the database name to *master* but keeps any *AttachDbFileName* value, which leads to an error since we cannot attach the *master* database to another file.
* `EnsureCreated` opens a connection using the provided *AttachDbFileName* value, which leads to an error since the file of the database we want to create does not yet exist.

EF6 seems to have some logic to handle this stuff, see `SqlProviderServices.DbCreateDatabase`. And working with *Local DB* requires using *AttachDbFileName* if we don't want to bloat our user profile (as far as I know). Maybe updating `SqlServerConnection.CreateMasterConnection` to remove *AttachDbFileName* would be the first step to resolve this?

I posted a hacky workaround for this at the [stackoverflow question](http://stackoverflow.com/q/31928014/2347790) linked by @bricelam...

**Comment by bricelam** [comment] 2016-08-30 16:10
@axelheer That sounds like a bug. Could you [submit a new issue](https://github.com/aspnet/EntityFramework/issues/new)?

**Comment by divega** [comment] 2016-08-30 17:52
It seems the original report might have just missed a few details, but it could have been the same issue that @axelheer is describing from the beginning. I will just reactivate for now.

**Comment by bricelam** [comment] 2016-08-30 18:41
Beside not stripping AttachDBFileName, we also don't support creating new attached databases. We'll need to produce DDL like the following.
```SQL
CREATE DATABASE [MyDatabase]
ON (NAME = 'MyDatabase.mdf', FILENAME = 'C:\Path\To\MyDatabase.mdf')
LOG ON (NAME = 'MyDatabase_log.ldf', FILENAME = 'C:\Path\To\MyDatabase_log.ldf');
```

**Comment by axelheer** [comment] 2016-08-30 18:58
Yeah, makes sense. Thus, we need already three things:

* Remove `AttachDBFilename` when connecting to master (#6435)
* Accept error 1832 within `SqlServerDatabaseCreator.Exists` or check via `dbo.sysdatabases` or via `db_id(.)`
* Add file name to `SqlServerCreateDatabaseOperation` or the like

I've already looked into your tests, but I've no idea how to write some kind of integration test to play through this whole scenario.

**Comment by bricelam** [comment] 2016-08-30 19:39
FYI, all the logic for resolving paths was in [SqlProviderServices.GetOrGenerateDatabaseNameAndGetFileNames](https://github.com/aspnet/EntityFramework6/blob/master/src/EntityFramework.SqlServer/SqlProviderServices.cs#L1039) for EF6.

**Comment by axelheer** [comment] 2016-08-31 16:24
I may be able to solve that. Should I dive into it and prepare a PR?

**Comment by bricelam** [comment] 2016-08-31 16:38
That would be awesome if you're willing!

**Comment by axelheer** [comment] 2016-08-31 17:34
Okay, I'll give it a try then.

**Comment by divega** [comment] 2016-08-31 18:27
**Triage:** if we don't take a PR to have proper support in 1.1, the scope for the EF team would be to try to throw a better error.

**Closed** 2016-09-15 20:58 UTC
Labels: type-bug, up-for-grabs

**Comment by efidiles** [comment] 2018-01-04 14:23
Hey guys,

We just ran into this ourselves; looks like relative paths aren't supported with `AttachDbFileName`.  

```
System.Data.SqlClient.SqlException (0x80131904): Cannot attach the file '.\OurDbName.mdf' as database 'OurDbName'.
```

Just wanted to express that here for other people who might be bumping into this.  The "fix" is use absolute paths.

**Comment by axelheer** [comment] 2018-01-04 19:36
@efidiles You can use the mighty `|DataDirectory|` placeholder too (see [here](https://github.com/aspnet/EntityFrameworkCore/blob/a588722e10f34a12b9cea3d655fd26aafd91051b/src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs#L669-L685)).
