### ISSUE TITLE
Navigaton property not work whe used OfType

### ISSUE THREAD

**Issue by genusP** [aspnet/EntityFramework#3962] opened 2015-12-03 11:14 UTC
This code raise error
```C#
public class NavPropertyError
    {
        class TestEntity
        {
            public int Id { get; set; }
            public string Field1 { get; set; }
        }

        class TestEntityDetail
        {
            public int Id { get; set; }
            public TestEntity TestEntity { get; set; }
        }

        class Context: DbContext
        {
            public DbSet<TestEntity> Entities { get; set; }
            public DbSet<TestEntityDetail> EntityDetails { get; set; }
        }

        [Fact]
        public void MyTestMethod()
        {
            var serviceCollection = new ServiceCollection();
            serviceCollection
                .AddEntityFramework()
                .AddInMemoryDatabase()
                .AddDbContext<Context>(o => o.UseInMemoryDatabase());

            var serviceProvider = serviceCollection.BuildServiceProvider();
            var context = serviceProvider.GetRequiredService<Context>();
            var target = context.EntityDetails;

            target
                .OfType<TestEntityDetail>()
                .Select(ed => ed.TestEntity.Field1)
                .ToArray();
        }
}
```
If remove call OfType, then no error.

**Comment by rowanmiller** [comment] 2015-12-08 19:39
Possibly a dupe of #3235

**Comment by mikary** [comment] 2015-12-17 23:54
This query results in a null value being passed from the `NavigationRewritingExpressionVisitor` in `CreateEntityQueryable`. The value is supposed to be an `IAsyncQueryProvider` that is in the query itself. This value is passed down into subqueries as their expressions are visited, however, this query results in the `IQueryable` / `IAsyncQueryProvider` being nested in a subquery in the original `Expression`. As a result, the top level visitor's reference is never updated.

**Closed** 2015-12-18 18:14 UTC
Labels: 2 - Done, bug, pri0
