### ISSUE TITLE
Tools.CLI is 64 bit architecture

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#5285] opened 2016-05-06 19:40 UTC
Not an error just a warning but this came up while using rev eng on win7 32 bit machine

C:\Program Files\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Microsoft.EntityFrameworkCore.Tools.Cli, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60, processorArchitecture=AMD64", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.

**Comment by natemcmaster** [comment] 2016-05-09 18:47
This is essentially a duplicate of https://github.com/aspnet/EntityFramework/issues/5273. With "Tools.CLI" as a dependency of "Tools", users will get this error. We can fix this by splitting packages or preventing Tools.CLI from installing in csproj type projects. 

The error thrown by MSBuild is valid because Tools.CLI ships a "exe", not a "dll" in the nupkg to support CLI commands on desktop .NET. Cref https://github.com/dotnet/cli/issues/2020

**Comment by natemcmaster** [comment] 2016-05-13 16:58
@piotrpMSFT is it possible to compile an "anycpu" exe with dotnet cli?

**Comment by NTaylorMullen** [comment] 2016-05-13 17:10
@natemcmaster in order to do this we have to do the following:

https://github.com/dotnet/coreclr.xunit/blob/master/src/dotnet-test-xunit/project.json#L23-L34
https://github.com/dotnet/coreclr.xunit/blob/master/build.ps1

**Comment by natemcmaster** [comment] 2016-05-13 17:17
Is there documentation for what "buildOptions" > "platform" can be set to? 

So, following dotnet-test-xunit's example, our nupkg needs to look like this:
```
Microsoft.EntityFrameworkCore.Tools.Cli/
    lib/net451/dotnet-ef.exe  <-- what's this then?
    runtimes/win7-x64/lib/net451/dotnet-ef.exe (64bit version)
    runtimes/win7-x86/lib/net451/dotnet-ef.exe (32bit versinon)
```
Questions: with this structure, what is lib/net451/dotnet-ef.exe? 64, 32? Can it be excluded if .NET CLI will find and run from runtimes/ anyways?

**Comment by pranavkm** [comment] 2016-05-13 17:22
The file under `lib` is used as a reference assembly for unit testing the runner. It doesn't have much use outside of it.

**Comment by natemcmaster** [comment] 2016-05-19 16:40
Fixed in https://github.com/aspnet/EntityFramework/commit/3c575741a9bffe57c08a70e7fa2fc1655be51833

**Closed by natemcmaster** 2016-05-19 16:40 UTC
Labels: bug, pri0
