### ISSUE TITLE
ChangeTracker :: Sequence contains more than one element, when inserting multiple entities to a model with two OneToOne mappings

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#1285] opened 2014-12-12 22:19 UTC
Repro:

```
       public class Soldier
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public Weapon PrimaryWeapon { get; set; }
        public Weapon SecondaryWeapon { get; set; }
    }

    public class Weapon
    {
        public int? Id { get; set; }
        public string Name { get; set; }
        public int Damage { get; set; }
        public int SecondaryOwnerId { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Soldier> Soldiers{ get; set; }
        public DbSet<Weapon> Weapons { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Weapon>().Property(typeof(int), "ShadowKey");
            modelBuilder.Entity<Soldier>(m =>
            {
                m.OneToOne(s => s.PrimaryWeapon).ForeignKey(typeof(Weapon), "ShadowKey");
                m.OneToOne(s => s.SecondaryWeapon).Required(false).ForeignKey<Weapon>(w => w.SecondaryOwnerId);
            });

            modelBuilder.Entity<Weapon>().Key(w => w.Id);
        }

        protected override void OnConfiguring(DbContextOptions options)
        {
            options.UseSqlServer(new SqlConnectionStringBuilder { DataSource = ".", InitialCatalog = "IncludeBash", IntegratedSecurity = true }.ToString());
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var assaultRifle = new Weapon
                {
                    Name = "Assault Rifle",
                    Damage = 4,
                };

                var battleRifle = new Weapon
                {
                    Name = "Battle Rifle",
                    Damage = 5,
                };

                var infantry1 = new Soldier
                {
                    Name = "Infantry1",
                    PrimaryWeapon = assaultRifle,
                };


                var infantry2 = new Soldier
                {
                    Name = "Infantry2",
                    PrimaryWeapon = battleRifle,
                };

                ctx.Weapons.Add(assaultRifle, battleRifle);
                ctx.Soldiers.Add(infantry1, infantry2);

                ctx.SaveChanges();
            }
        }
    }
```

this throws the following:

Unhandled Exception: System.InvalidOperationException: Sequence contains more th
an one element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.ChangeTracking.NavigationFixer.DoFixup(IEnumerable`1
 navigations, StateEntry principalEntry, StateEntry[] dependentEntries)
   at Microsoft.Data.Entity.ChangeTracking.NavigationFixer.InitialFixup(StateEnt
ry entry, EntityState oldState)
   at Microsoft.Data.Entity.ChangeTracking.NavigationFixer.<>c__DisplayClass26.<
StateChanged>b__27()
   at Microsoft.Data.Entity.ChangeTracking.NavigationFixer.PerformFixup(Action f
ixupAction)
   at Microsoft.Data.Entity.ChangeTracking.NavigationFixer.StateChanged(StateEnt
ry entry, EntityState oldState)
   at Microsoft.Data.Entity.ChangeTracking.StateEntryNotifier.<>c__DisplayClass2
.<StateChanged>b__3(IEntityStateListener l)
   at Microsoft.Data.Entity.ChangeTracking.StateEntryNotifier.Dispatch(Action`1
action)
   at Microsoft.Data.Entity.ChangeTracking.StateEntryNotifier.StateChanged(State
Entry entry, EntityState oldState)
   at Microsoft.Data.Entity.ChangeTracking.StateEntry.SetEntityState(EntityState
 oldState, EntityState newState)
   at Microsoft.Data.Entity.ChangeTracking.StateEntry.SetEntityState(EntityState
 entityState)
   at Microsoft.Data.Entity.ChangeTracking.StateEntry.set_EntityState(EntityStat
e value)
   at Microsoft.Data.Entity.ChangeTracking.EntityEntry.set_State(EntityState val
ue)
   at Microsoft.Data.Entity.DbContext.SetEntityStates[TEntity](TEntity[] entitie
s, EntityState entityState)
   at Microsoft.Data.Entity.DbContext.Add[TEntity](TEntity[] entities)
   at Microsoft.Data.Entity.DbSet`1.Add(TEntity[] entities)
   at IncludeBashing.Program.Main(String[] args) in D:\Projects\IncludeBashing\I
ncludeBashing\Program.cs:line 249

**Comment by mikary** [comment] 2015-01-09 00:29
Repro runs without issue with the following corrections:

Move Required call to follow ForeignKey call
```cs
m.OneToOne(s => s.SecondaryWeapon)
    .ForeignKey<Weapon>(w => w.SecondaryOwnerId)
    .Required(false);
```

Make Id non-nullable (not necessary)
Make SecondaryOwnerId nulable
```cs
 public class Weapon
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Damage { get; set; }
        public int? SecondaryOwnerId { get; set; }
    }
```

Effectively a duplicate of #1314

Clearing flags for re triage.

**Comment by rowanmiller** [comment] 2015-01-09 19:44
Already covered by https://github.com/aspnet/EntityFramework/issues/1286

**Closed by rowanmiller** 2015-01-09 19:44 UTC
Labels: 0 - Backlog
