### ISSUE TITLE
Query: Provide DbFunctions class to define methods that correspond to standard SQL operations

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFramework#2850] opened 2015-08-15 11:14 UTC
Not sure whether this has already been discussed (or makes sense).

There are some standard SQL operations that don't correspond to an already-existing .NET method; the example that comes to mind is LIKE. It seems that up to now, each provider invented its own way to allow users to specify these in LINQ to Entities - SqlClient has [SqlFunctions](https://msdn.microsoft.com/en-us/library/system.data.objects.sqlclient.sqlfunctions%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) and [SqlMethods](https://msdn.microsoft.com/en-us/library/system.data.linq.sqlclient.sqlmethods%28v=vs.110%29.aspx).

It seems to makes sense to pull the standard SQL functions and methods out of these SQL Server-specific classes and place them in the generic EF7 code, this way the same LINQ can be used across different providers...

**Comment by ErikEJ** [comment] 2015-08-15 11:19
I think it is already there: https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Relational/Query/Methods/ContainsTranslator.cs

**Comment by divega** [comment] 2015-08-19 00:17
@roji This does make sense in general although it is probably worth digging more into what "standard SQL operations" means :smile:

We have talked within the EF team about the need to have a way to represent any standard relational functions as well as provider specific functions that aren't well represented by LINQ operators or by standard method calls in .NET BCL classes. We came up with a pattern we decided to try in EF7 that we believe can be better than what we had in the past. We just haven't found an opportunity to start using it, but would look similar to this:

``` C# 
var legalMinors = context.People.Where(p => 
    EF.Functions.DiffYear(p.BirthDate, DateTime.Now) - 
    DateTime.Now.DayOfYear < p.BirthDate.DayOfYear ? 1 : 0 
    < legalAge);
```

The idea is to add a new `Functions` property to the static [EF class](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Core/EF.cs) (the same class where we put the `Property` method you can use to access shadow state properties in LINQ). Then EF and providers as well can define extension methods for the type of the `Functions` property. 

Here are a few (subject to change) rules for these:

1. In general, EF and providers should use a high bar for adding methods here. If there is a reasonable pattern that can be represented with LINQ operators or standard .NET BCL method calls we should enable the translation of that pattern instead.

2. When we consider adding any new function to the set of "standard SQL functions" (i.e. if we put it in our base relational provider as opposed to a specific relational provider) or even as a standard "EF function" (in EF core, if we ever decide to do that) we should first ponder the burden added on providers to support it. Although it seems nice to have a good set of standard functions that enables customers to write common LINQ query code that works across different providers, it wouldn't be good if a significant number of these functions ended up triggering client evaluation on many providers because they aren't actually supported. 

3. We will recommend that provider specific functions use prefixing to avoid collisions when multiple providers are in scope. E.g. define `EF.Functions.SqlHostName()` as opposed to `EF.Functions.HostName()`. 

@ErikEJ It is true that `String.Contains()` and more importantly `String.StartsWith()` leverages LIKE in a very valuable usage case, and that makes having a way to express LIKE directly in LINQ less important. However I don't think it is true that everything that you can express with LIKE is covered in existing .NET BLC methods so we don't discard adding support for it in the future.

**Comment by divega** [comment] 2015-08-19 00:19
Clearing up this for triage. I think we can choose having this issue in the backlog and up-for-grabs, or we can wait until the concrete need arises to have specific functions added.

**Comment by roji** [comment] 2015-08-24 22:07
Sorry for disappearing for a while.

@ErikEJ, Contains provides only a subset of what can be done with SQL LIKE (consider 'a%b%c')

**Comment by roji** [comment] 2015-08-24 22:13
@divega, the approach looks great.

Regarding rule 2, it might be acceptable for some methods to throw NotSupportedException rather than trigger client evaluation which if they aren't supported by a specific provider. This may encourage more unportable code, but would be more fail-fast (i.e. an exception is better than hard-to-detect slowdown due to client evaluation).

Regarding rule 3, it seems cleaner for provider-specific functions to be defined in a provider-specific static class rather than have provider-specific prefixes on the EF.Functions class (i.e. Npgsql.EF.Functions.HostName() rather than EF.Functions.NpgsqlHostName()).

**Comment by divega** [comment] 2015-08-25 00:09
@roji Re rule 2 (client evaluation vs. throwing not supported for performance reasons), client evaluation is actually one of the value adds of EF7 and I don't think we can always assume that evaluating something on the client is going to be so expensive than it is better not to do it. It will most likely depend heavily on how many rows will be returned that wouldn't if the function had been evaluated on the server, but in many cases it should be ok.

For lack of a better strategy I think it is desirable to leave the decision to the application developer, e.g. think about having a simple `ClientEvaluationEnabled` flag or perhaps the opposite `StrictServerEvaluationEnabled` (and I just made up these names :smile:) that would control if doing client evaluation on constructs that are outside the top most projection is ok or whether it should throw. I believe we have an issue tracking this idea but I couldn't find it easily right now (@anpete do you know?).

Besides that, there is a class of functions that only have a real meaning on the server, e.g. the `HostName` function we mentioned above, so for those it might make more sense to throw `NotSupportedException` for those, although throwing always makes simple testability scenarios a pain. 

Re rule 3 (having `Npgsql.EF.Functions.HostName()` rather than `EF.Functions.NpgsqlHostName()`) that is a very valid point. What I really like about `EF.Functions` (and makes me still prefer it) is that it represents a single API entry point you need to learn about when using EF so it improves discoverability for all functions. But arguably it does make the names of the individual functions worse. Others in the thread might have thoughts on this.

**Comment by ErikEJ** [comment] 2015-08-25 10:50
+1 for the EF.Functions! Great discoverability, and no need to learn a new namespace

**Comment by Daniel-Svensson** [comment] 2015-11-04 17:49
Please consider making these methods (or at least most of them) work even at runtime if executed in a where statement for a mock database or in-memory one. 

The old approach with throwing as in DbFunctions has forced us to write our own wrapper where we have to duplicate all methods we use such as TruncateTime. 

+1 for trying to use BCL class calls instead of methods where possible so we for example might be able to write `(DateTime.Now.Year -  p.BirthDate.Year)` instead of / as alternative to `EF.Functions.DiffYear(p.BirthDate, DateTime.Now)`

**Comment by xrkolovos** [comment] 2015-12-18 09:41
Any news with this feature? We are also forced to write our own wrapper where we have to duplicate all methods we use such as TruncateTime.

**Comment by rowanmiller** [comment] 2015-12-22 19:14
It's not something our team will be tackling before the 7.0.0 release (purely due to time constraints). We haven't done any planning of what order we will tackle features after that release yet. We will do that planning (and share it publically) closer to the 7.0.0 release.

**Comment by rjperes** [comment] 2016-07-04 21:47
Any news on this?

**Comment by rowanmiller** [comment] 2016-07-05 21:36
@rjperes  Nothing as yet. We have some higher priority features on the backlog, so this probably wont be in the first round of things we implement.

**Comment by rjperes** [comment] 2016-07-05 22:04
Thanks, Rowan! See you in November, hopefully with EF Core 1.1 out! ;-)

**Comment by Serjster** [comment] 2016-11-07 09:44
I am also very interested in having this implemented.

**Comment by joshmouch** [comment] 2016-11-08 21:04
I'd love to see TruncateTime implemented.

**Comment by rowanmiller** [comment] 2016-11-22 18:47
Note to self: leaving unassigned as we will prioritize as part of 1.2 planning next week

**Comment by matgr1** [comment] 2016-11-23 01:09
I've been playing around with this for a couple of days and I've come up with something that may be useful:

An attribute that can be applied to a function that will then invoke the specified database function when the expression is translated; if the expression cannot be translated for any reason, it will instead call the CLR function that the attribute is applied to:

```C#
[EF.Function("DATEDIFF", new[] { 0 }, new[] { "year" })]
private static int DateDiffYear(DateTime? startDate, DateTime? endDate)
{
    // CLR implementation (or throw if you don't need to support a fallback)...
}
```

```C#
DateTime dt = DateTime.Now;
List<Order> resultSql = context.Orders.Where(o => DateDiffYear(o.OrderDate, dt) >= 20).ToList();
```

The attribute allows you to specify static arguments (which is required for DATEDIFF since using dynamic user parameters is not allowed for datepart).  The syntax is a little messy due to the requirements of parameters passed to attributes, but perhaps there's a better way that I'm missing?

I've also implemented EF.Functions.Like with a CLR fallback (which probably needs a little work!) that supports the wildcards '%' and '_' (no character classes yet, although I'm not entirely sure what to do about those since other providers don't necessarily support this, eg. Sqlite).  And I've added the ESCAPE parameter to LikeExpression which is useful if you want to search for, say, percentages!

I need to clean a few things up and add some more tests, but I'd be happy to make a pull request if any of this is useful!

My changes are here: https://github.com/aspnet/EntityFramework/compare/dev...matgr1:dev

**Comment by xrkolovos** [comment] 2016-12-19 17:17
PLease plan this feature. espectially TruncateTime

**Comment by roji** [comment] 2017-02-08 12:58
Design note for LIKE and portability:
* SqlServer's pattern has no escaping by default (optional ESCAPE clause has to be used)
* PostgreSQL's pattern uses backslash as the default delimiter, and it can be changed (or disabled) via an optional ESCAPE clause.

There is [a report](https://github.com/aspnet/EntityFramework/issues/7429#issuecomment-277827978) of the ESCAPE clause being bad for performance on SqlServer, but this needs to be verified.

**Comment by roji** [comment] 2017-02-11 11:37
@divega, @rowanmiller,

@rwasef1830 is looking into adding [full-text support for PostgreSQL](https://www.postgresql.org/docs/current/static/textsearch.html) to the Npgsql provider for 1.2. This would very probably require a place to define LINQ methods such as described in this issue (`EF.Functions`). This issue hasn't made much progress yet, but I'm wondering if we can at least lock down the shape of the API so that we'd be able to move forward... In other words, I'm not asking to implement any specific methods (e.g. for LIKE), but rather simply to add `EF.Functions` so that would be able to define extension methods on it.

This should be relatively straightforward - mainly design decisions about how to deal with provider-specific methods (i.e. `Npgsql.EF.Functions.HostName()` vs. `EF.Functions.NpgsqlHostName()`).

**Comment by rowanmiller** [comment] 2017-02-13 21:44
Clearing milestone so that we can discuss in triage

**Comment by rowanmiller** [comment] 2017-02-14 19:15
@roji we're good with the `EF.Functions.NpgsqlHostName()` approach. Do you want to send a PR to add it to core?

**Comment by roji** [comment] 2017-02-14 20:15
Sure, will take a look.

**Comment by pmiddleton** [comment] 2017-02-17 06:46
@roji I added support for this as well as user defined functions in a fork.  See #7368  

Any feedback you have on that change would be appreciated.  

It was tagged as 2.0 so hopefully the change will be considered by the team in the next release.

**Comment by roji** [comment] 2017-02-17 10:10
@pmiddleton damn, too bad we both attacked the same thing... Wasn't aware of your efforts.

What you're doing obviously goes farther than what I've done, which was merely to support extensions on `EF.Functions` (i.e.  no attempt to support user-defined functions). I guess the EF Core team need to review and decide what they want to do here.

Some minor comments
* I'd personally break up the work into chunks - there's lots of things merged into one commit (e.g. the infrastructure for supporting the functions vs. the actual implementation of some of them, etc.). This would make it much easier to review and understand what's going on.
* There's lots of indentation changes (because of curly braces after case) that probably need to be cleaned up. Again, it makes it difficult to review.
* It seems your code adds functions such as `EF.Functions.AddYears()` accepting DateTime. IMHO if a standard method already exists in the CLR - in this case [`DateTime.AddYears()`](https://msdn.microsoft.com/en-us/library/system.datetime.addyears%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) - then it doesn't make sense to have an `EF.Functions` method for it. Methods in `EF.Functions` should only exist for operations which really have no CLR counterpart (if I'm not mistake a translator for `DateTime.Add*()` actually exists in EF Core).
* I'm not sure if your code is still in progress, but in some comments methods are referred to under `EF.Functions`, but there's also a static class called `DbFunctionsExtensions`

**Comment by pmiddleton** [comment] 2017-02-21 07:04
@roji - Thanks for the feedback.  

I agree that the changes are too large right now and it needs to be broken up.  

The problem is finding the right spot to break it up.  Like you said a large part of the code change is from converting the existing function translators from the way they are currently implemented to the new way I came up with.

I originally tried mixing the existing function translators with my approach for UDFs to avoid changing as much code.  This lead to edge cases where translations failed due to such things as function nesting when combined with client side evaluation fallback.  I went with common translation to avoid the edge cases, but that lent itself to way more code changes.  

Per your third bullet point - I debated adding the duplicate methods as well.  Is it better to provide easier code migration from EF 6 by supplying the same DbFunctions, or is it better to dump the ones which can be replaced by BCL methods such as the DateTime.Addxxx method family.  I can honestly see it going either way.  In the end I added some of the EF6 DbFunction methods and decided to wait and see what the feedback was.

**Comment by roji** [comment] 2017-02-21 14:28
@pmiddleton I guess someone from the EF Core team needs to start looking at this.

Regarding the third point (duplicate methods), I don't think exact code compatibility with EF6 (i.e. easy porting) is (nor should be) a top priority of EF Core... IMHO in cases where an idiomatic BCL method such as `DateTime.Add*` exists the `EF.Functions` equivalent should be dumped as it provides no value, and does the same thing in a less idiomatic way. And having two ways to do something is always confusing. Just my 2 cents on the question...

**Comment by divega** [comment] 2017-02-22 05:05
Incidentally the same idea was considered when the feature was added in previous versions of EF:
- only add methods for "canonical" (i.e cross-provider) functions if there is no equivalent BCL pattern that we can translate
- only add methods for provider specific functions if there is no canonical function

So any redundancy in functions available in EF6 should be the consequence of a gap in what BCL patterns we supported, an oversight, or an explicit decision.

If we apply a similar criteria in EF Core we should land on something quite similar and better.

**Comment by divega** [comment] 2017-02-22 05:13
BTW @pmiddleton are you planning to send a PR so we can proceed reviewing your changes?

**Comment by pmiddleton** [comment] 2017-02-24 02:27
@divega I do plan on submitting a pull request shortly.  I am taking another look at the code to figure out what I can split out into separate PRs.

**Comment by divega** [comment] 2017-02-24 17:46
Great to hear @pmiddleton! Ilooking forward to it! 

If the split isn't obvious feel free to send the whole set of changes as a PR and we can help find ways to separate it. FWIW, reading your previous comments it sounds like you could at least do a PR for adding `EF.Functions` and some simple function (very similar to what @roji did?) and then another one that contains the rest of your changes. Or perhaps we could take @roji's PR and then you could do a PR rebased on that? Whatever works best.

**Comment by jemiller0** [comment] 2017-03-03 16:14
I would very much like to see standard methods for performing full-text searches for those databases that support them. I.e. it would be nice if the function calls were the same across SQL Server, PostgreSQL, MySQL, etc. and not have one method with one syntax in one provider and another syntax in another. In my case, I would mainly just like a way to do a substring search that is efficient using an index. I don't really even need word breaking and what not. Just an efficient way to do a substring search.

**Comment by roji** [comment] 2017-03-04 10:11
@jemiller0, full-text searching specifically probably deserves its own issue and discussion. The most important question is obviously to what extend the full-text searching capabilities of different databases overlap, similar to the spatial support discussion.

Obviously if you just want to do a substring search, you don't necessary need "full-text search" (`String.Substring()` should b emapped to SQL for all providers). The interesting questions begin with the more advanced capabilities.

**Comment by jemiller0** [comment] 2017-03-04 16:51
What I would like is a Contains() search, but, one that operates in an efficient manner. I.e. doesn't have to do a brute force search/table scan. I'm assuming that would need a full-text index. I don't know how that works internally, just that it's functionality that would be useful for the applications I've been developing. I've been assuming I would need to use full-text search for that. I'm actually kind of surprised that SQL databases in general don't have a way of handling this. I.e. an efficient way to do a LIKE '%value%' search. For my purposes, I think I would really even need work breaking and all that. I just need to be able to search for literal text as is. Or, it seems that full-text search is part of the SQL standard.

**Comment by roji** [comment] 2017-03-04 16:58
@jemiller0, I think this really belongs in an issue of its own, where we'd discuss the least common (but still useful) denominator of database full-text search. This issue is already far too overloaded for that.

**Comment by roji** [comment] 2017-03-04 17:00
One last note re full text search - this would probably go beyond simply providing querying capabilities (i.e. providing something like DbFunctions), since the proper indices must be set up for efficient searching.

**Comment by jemiller0** [comment] 2017-03-05 00:33
@roji No problem. I was just making a comment. Not really asking for anything concrete on this issue specifically. Just saying that I've been hoping for something like that for years. Unfortunately, completely re-writing EF has slowed down developing more advanced features. But hopefully now that EF Core is nearing a usable state, things like that could be tackled.

**Comment by divega** [comment] 2017-05-09 19:19
@anpete @ajcvickers Thinking we may mark this as fixed in preview1. I believe we only have `Like()` there now but from now one we can track specific functions in individual issues. Thoughts?

**Comment by ajcvickers** [comment] 2017-05-09 21:35
@divega Sounds good to me.

**Closed** 2017-05-10 01:05 UTC
Labels: closed-fixed, type-enhancement, up-for-grabs

**Comment by divega** [comment] 2017-05-10 01:08
Closing this as we have added the `EF.Functions` property of type `DbFunctions` as part of the implementation of the `Like()` method. Additional Core, Relational and provider specific functions can be mapped to extension methods for `DbFunctions` and we will use separate issues for those.

**Comment by ryanelian** [comment] 2017-05-23 16:10
Can we have `EF.Functions.Contains` and `EF.Functions.FreeText` for performing full-text search against SQL Server?

https://docs.microsoft.com/en-us/sql/t-sql/queries/freetext-transact-sql

https://docs.microsoft.com/en-us/sql/t-sql/queries/contains-transact-sql

**Comment by MikeDempseyFL** [comment] 2018-07-02 21:00
I am trying to add an 'int Random(int, int)' function to EF.Functions but it looks like it is trying to evaluate it on the client rather than calling Random(int, int) on the DBS.
I assume this is because there are no objects from the model referenced in a call to Random.

I have added other database specific functions to EF.Functions and they work fine.
Those all take at least one object reference in their arguments.

Is there a way to tell EF to ALWAYS pass an extension function to the database?

Someone above mentioned HostName as a potential extension function for PostgreSql. That would have the same issue so was that done/solved? 

(I understand there is a Random() function available in CLR but I need a random number generated for each row in the result set, so it must be executed on the database.)

**Comment by rwasef1830** [comment] 2018-07-02 21:06
@MikeDempseyFL You can force EF to always send a function to the database by overriding the `IEvaluatableExpressionFilter` service.

```
.TryAdd<IEvaluatableExpressionFilter, YourEvaluatableExpressionFilter>()
```

In your filter class inherit from `RelationalEvaluatableExpressionFilter` and override the `IsEvaluatableMethodCall` method. It should return true if the method can be evaluated on the client and false if it should always be evaluated on the server.

**Comment by pmiddleton** [comment] 2018-07-02 21:22
@MikeDempseyFL Are you implementing a provider or are you just using EF Core in a project?

**Comment by MikeDempseyFL** [comment] 2018-07-02 22:28
I am implementing a provider.
I think someone pointed me to the solution using IEvaluatableExpressionFilter service.

Thanks
Mike

**Comment by SunflowerPKU** [comment] 2019-05-31 03:28
> @divega I do plan on submitting a pull request shortly. I am taking another look at the code to figure out what I can split out into separate PRs.

Hi @pmiddleton ,

I am a Ph.D. student. I am doing research about **helping newcomers participate in OSS projects**. I noticed that many projects are using labels such as 'good first issue/bug, help wanted' for issues to recommend that newcomers start from these tasks. 

I noticed that you tried to solve this issue, but unfortunately, you had not contributed successfully. I also found there are many newcomers feel difficult when submitting their first pr. Therefore, I want to optimize this mechanism, which needs your help. I have some questions and wish your valuable feedback.

**1. What problems did you meet when solving this issue? 
2. Do you think it is appropriate to recommend newcomers to solve this issue?  and why?
3. How do you think of the existing mechanism that adding certain labels to issues for helping newcomers participate in open source projects?**

I am looking forward to hearing from you soon. Thank you very much!

**Comment by cyptus** [comment] 2019-06-07 08:58
It is possible to make use of the SQL functions by wrapping it with the DbFunctionAttribute.
For example for the datepart function:
Tricky part here is to tell ef core not to handle the datepart type parameter as a string.

DbContext:
```csharp
public int? DatePart(string datePartArg, DateTime? date) => throw new Exception();

public void OnModelCreating(DbModelBuilder modelBuilder) {
    var methodInfo = typeof(DbContext).GetRuntimeMethod(nameof(DatePart), new[] { typeof(string), typeof(DateTime) });
    modelBuilder
        .HasDbFunction(methodInfo)
        .HasTranslation(args => new SqlFunctionExpression(nameof(DatePart), typeof(int?), new[]
                {
                        new SqlFragmentExpression(args.ToArray()[0].ToString()),
                        args.ToArray()[1]
                }));
}
```

Query:
```csharp
repository.GroupBy(x => dbContext.DatePart("week", x.CreatedAt));
```

some more info: https://github.com/aspnet/EntityFrameworkCore/issues/10404

**Comment by onitecsoft** [comment] 2020-01-07 11:33
for EF core 3 is little different solution:

```
modelBuilder.HasDbFunction(methodInfo, b => b.HasTranslation(e =>
{
	var ea = e.ToArray();
	var args = new[]
	{
		new SqlFragmentExpression((ea[0] as SqlConstantExpression).Value.ToString()),
		ea[1]
	};
	return SqlFunctionExpression.Create(nameof(DatePart), args, typeof(int?), null);
}));
```

**Comment by rangelier** [comment] 2020-05-05 10:43
> for EF core 3 is little different solution:
> 
> ```
> modelBuilder.HasDbFunction(methodInfo, b => b.HasTranslation(e =>
> {
> 	var ea = e.ToArray();
> 	var args = new[]
> 	{
> 		new SqlFragmentExpression((ea[0] as SqlConstantExpression).Value.ToString()),
> 		ea[1]
> 	};
> 	return SqlFunctionExpression.Create(nameof(DatePart), args, typeof(int?), null);
> }));
> ```

Tried this implementation on EF Core 3.1.3 but it doesn't work:

```
The LINQ expression 'DbSet<Reading>
    .Where(r => r.StructureId == __structureId_0)
    .Where(r => r.From >= __AddDays_1 && r.From <= __now_2)
    .GroupBy(
        source: r => __context_3.DatePart(
            datePartArg: "weekday", 
            date: (Nullable<DateTime>)r.From.DateTime), 
        keySelector: r => r)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

**Comment by roji** [comment] 2020-05-05 10:47
@rangelier can you please open a new issue and include a minimal, runnable code sample? The actual LINQ query is missing from the above.

**Comment by rangelier** [comment] 2020-05-05 11:39
yes, need to some time to prepare though. 

The original query looks like this:

```
 var weekResult = query.Where(c => c.From >= now.AddDays(-28) && c.From <= now)
                        .GroupBy(c => context.DatePart("weekday", c.From.DateTime))
                        .Select(c => new
                        {
                            Week = c.Key,
                            Total = query.Sum(c => c.Value)
                        });
```

**Comment by Astenna** [comment] 2020-11-09 23:19
anything new on this issue?
tried the same solution as @rangelier mentioned, but it doesn't work.
I'm using EF Core 3.1.9

**Comment by cyptus** [comment] 2020-11-10 12:45
this works fine for us, even on v3.1.9
please provide a minimal example that demonstrate your issue with this logic.

**Comment by marchy** [comment] 2021-01-02 14:21
> Closing this as we have added the `EF.Functions` property of type `DbFunctions` as part of the implementation of the `Like()` method. Additional Core, Relational and provider specific functions can be mapped to extension methods for `DbFunctions` and we will use separate issues for those.

@divega The repeatedly requested TruncateTime methods have not been implemented in DbFunctions, despite it being mentioned repeatedly above: https://github.com/dotnet/efcore/issues/2850#issuecomment-259259028, https://github.com/dotnet/efcore/issues/2850#issuecomment-153807325, https://github.com/dotnet/efcore/issues/2850#issuecomment-165730348, https://github.com/dotnet/efcore/issues/2850#issuecomment-268022596

How can you compare a date to the start/end of the day?
(ie: previously achieved with TruncateTime in EF6)

[This issue](https://github.com/dotnet/efcore/issues/3554) which explicitly requested the TruncateTime functions got marked as closed/dupe, even though the implementation did NOT resolve it. Can you please re-open so we don't have to re-file another one for the exact same thing?
