### ISSUE TITLE
The Type "IEnumerable<>" is defined in an unreferenced assembly

### ISSUE THREAD

**Issue by SharpNoiZy** [aspnet/EntityFramework#4047] opened 2015-12-11 08:51 UTC
Hi,

I added EntityFramework.Core to an RC1 lib project.
And as soon I do this, I can't compile the project anymore because the second line of code is underlined:
```
List<string> test = new List<string>(); 
test.Where(x => x == "");
```

With the message:
```
Error   CS0012  The Type "IEnumerable<>" is defined in an unreferenced assembly. Add an reference on the Assembly "System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
```

As soon as I remove the EF reference, code is perfectly compilable.

Any ideas?

Kind regards

**Comment by SharpNoiZy** [comment] 2015-12-14 06:21
Nobody?

**Comment by rowanmiller** [comment] 2015-12-15 18:29
I'm not able to reproduce this issue (using a .NET 4.5.1 Console Application). What type of project are you creating and what version of .NET?

**Comment by SharpNoiZy** [comment] 2015-12-16 04:51
Like I wrote it on my first post "RC1 lib project", I thought it would be clear that it is an .Net Core RC1 Library project with EF 7 Core lib.

**Comment by SharpNoiZy** [comment] 2015-12-16 10:50
Here my project.json

```
{
	"version": "1.0.0-*",
	"description": "MFT.Core Class Library",
	"authors": [ "cneuss" ],
	"tags": [ "" ],
	"projectUrl": "",
	"licenseUrl": "",
	"frameworks": {
		"net451": {

		},
		"dotnet5.4": {
			"dependencies": {
				"Microsoft.CSharp": "4.0.1-beta-23516",
				"System.Collections": "4.0.11-beta-23516",
				"System.Linq": "4.0.1-beta-23516",
				"System.Runtime": "4.0.21-beta-23516",
				"System.Threading": "4.0.11-beta-23516"
			}
		}
	},
	"dependencies": {
		"Microsoft.Extensions.DependencyInjection.Abstractions": "1.0.0-rc1-final",
		"EntityFramework.Core": "7.0.0-rc1-final"
	}
}
```

**Comment by rowanmiller** [comment] 2015-12-23 20:38
Thanks, confirmed that I can reproduce this on RC1. The issue is compiling against net451, it compiles fine against dotnet5.4 (removing net451 from the frameworks allows it to compile).

Looks like it is resolved in our working code base. The following project.json works (pulling packages from https://www.myget.org/F/aspnetcidev/api/v3/index.json). 

@bricelam do you think there is anything we need to follow up on here? Or are we confident that things are now correct?

```json
{
  "version": "1.0.0-*",
  "description": "ClassLibrary2 Class Library",
  "authors": [ "" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",
  "frameworks": {
    "net451": { },
    "dotnet5.4": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-*",
        "System.Collections": "4.0.11-*",
        "System.Linq": "4.0.1-*",
        "System.Runtime": "4.0.21-*",
        "System.Threading": "4.0.11-*"
      }
    }
  },
  "dependencies": {
    "EntityFramework.Core": "7.0.0-rc2-*"
  }
}
```

**Comment by bricelam** [comment] 2015-12-24 01:42
I don't think so, I know CLI also plans to fix some of the quirks around design-time facades.

**Comment by davidfowl** [comment] 2015-12-24 10:13
Actually we're planning to make a fix to nuget to not fail on older projects when facades are declared as framework assemblies.

**Closed** 2015-12-28 19:14 UTC
