### ISSUE TITLE
Query : SqlServerMathRoundTranslator wrong argument index results in returning incorrect data or throwing InvalidCastException

### ISSUE THREAD

**Issue by rpawlaszek** [aspnet/EntityFramework#7600] opened 2017-02-12 19:29 UTC
Trying to use ```Math.Round``` in the query gives ```InvalidCastException```

```
Exception message: An exception occurred in the database while iterating the results of a query.
Stack trace:
System.InvalidCastException: Specified cast is not valid..
   w lambda_method(Closure , ValueBuffer )
   w System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   w Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
```

### Steps to reproduce
Follow [Entity Framework Core docs](https://docs.microsoft.com/en-us/ef/core/), build the model, populate Blogs table with few entities and then used this to query:

```c#
            using (var db = new BloggingContext())
            {
                LogToConsole(db);
                var query = db.Blogs
                            .Select(b => Math.Round(Math.PI, b.Rating));
                            
                foreach (var item in query)
                {
                    Console.WriteLine($"RESULT is {item}");
                }
            }
```
The console logging shows what went wrong:

```
select double Round(
    value: 3,14159265358979,
    digits: b.Rating
)
'
TRACKED: False
(QueryContext queryContext) => IEnumerable<double> _Select(
    source: IEnumerable<ValueBuffer> _ShapedQuery(
        queryContext: queryContext,
        shaperCommandContext: SelectExpression:
            SELECT ROUND([b].[Rating], [b].[Rating])
            FROM [Blogs] AS [b]
        ,
        shaper: ValueBufferShaper
    )
    ,
    selector: (ValueBuffer b) => (double) object b.get_Item(0)
)
```
The line 
```
SELECT ROUND([b].[Rating], [b].[Rating])
```
should be 
```
SELECT ROUND(3.14159265358979, [b].[Rating])
```

and is there because of a bug in [```SqlServerMathRoundTranslator.cs```#L34](https://github.com/aspnet/EntityFramework/blob/c9b5916a4e0fff763febea00da793ebd4113632d/src/Microsoft.EntityFrameworkCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerMathRoundTranslator.cs#L34). There should be

```c#
: new[] { methodCallExpression.Arguments[0], methodCallExpression.Arguments[1] })
```

I did that as I wanted to check whether mathemathical functions are run on the server side. And actually ```Math.Round``` wasn't the one I was looking for, but checked them all. I guess I should create another Issue with this, but could you implement trigonometric functions + ```Math.Sqrt```, ```Math.Log```, ```Math.Log10```, ```Math.Exp``` as well? 

### Further technical details
EF Core version: 1.1.0 (but present in all, as I see)
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro
IDE: Visual Studio 2015

**Comment by maumar** [comment] 2017-02-12 20:22
@rpawlaszek yes, please open new bug for the missing math functions.

**Comment by maumar** [comment] 2017-02-13 21:48
Justification for 1.1.1

Impact: Medium. Issue was found by a customer and it may cause incorrect results for simple queries. Severity is mitigated by the fact that scope of the issue is quite narrow (only one method is affected).
 
Risk: None - fix is one-character change (correcting of a typo), scoped to only one method call (Math.Round)

**Comment by Eilon** [comment] 2017-02-15 22:43
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.

**Closed** 2017-02-16 00:14 UTC
Labels: patch-approved, type-bug

**Comment by smitpatel** [comment] 2017-02-23 22:02
✅ Verified
