### ISSUE TITLE
Reverse engineer model from database

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#830] opened 2014-10-08 23:13 UTC
Looks like we didn't have a work item tracking this. We need tooling to reverse engineer a model from a database. For the initial cut this should include the functionality from EF6.x (ability to select tables etc.).

This does not include the ability to incrementally update the model based on changes to the database, https://github.com/aspnet/EntityFramework/issues/831 tracks that.

**Comment by lajones** [comment] 2015-07-01 00:33
See #2465. 

From @ErikEJ: Is this a good time to start investigating using Reverse Engineering with SQLCE, or is it too early?

From @divega: @ErikEJ I personally believe it is a good time for you to get started with it. If you hit issues or have any feedback we can make adjustments.

From ErikEJ: @divega Sounds great, is there some docs/design specs? Or a drawing? :smile:

 I have a few questions:
 1: Does this info still apply: https://stackoverflow.com/questions/29300777/is-there-an-entity-framework-7-database-first-poco-generator? 
 2: If so, how does the command know which provider to use?
 3: Is the rev-eng package simply installed as needed? (EntityFramework.SqlServer.Design)
 4: Will I "simply" implement the equivalent of EntityFramework.SqlServer.Design ?

**Comment by lajones** [comment] 2015-07-01 00:42
@ErikEJ @divega 

1. The commands listed in https://stackoverflow.com/questions/29300777/is-there-an-entity-framework-7-database-first-poco-generator are still accurate.
2. That's the problem - at the moment it's hard-coded to use EntityFramework.SqlServer.Design. @rowanmiller are you ok if I add back in the --provider flag to pass in the name of the RevEng provider assembly? Also if the argument is not provided do you want to a) error or b) default to the existing value?
3. At the moment you must reference EntityFramework.SqlServer.Design in your project.json and hence it is installed when package restore is run on the project. For your new provider your new package should be referenced in project.json instead.
4. Yes. Hopefully simply :-). You must have a class that implements IDatabaseMetadataModelProvider. I'll write this up but in the meantime details below.

A) On IDatabaseMetadataModelProvider, GenerateMetadataModel(string connectionString) generates an IModel containing EntityTypes. DbContextTemplate() and EntityTypeTemplate() return the relevant templates as strings (you get to look them up however you want - however note #2418 where we'll be providing a way for customers to override the default templates).

B) First the DbContextTemplate template is executed being passed an instance of DbContextGeneratorModel. On DbContextGeneratorModel  you'll find a property MetadataModel - which is the model you generated in step A) above.

C) Then we loop over all EntityTypes in the MetadataModel and on each one execute the EntityTypeTemplate passing in an EntityTypeGeneratorModel. Note that on EntityTypeGeneratorModel you'll find a property EntityType which is the EntityType being processed (and which can refer to its parent - the metadata model - if needed).

D) Each Model passed in also has a Helper property - which is an instance of DbContextCodeGeneratorHelper or EntityTypeCodeGeneratorHelper respectively. These contain helpful methods for ordering the entities, setting up configuration for the DbContext based on the model etc. Feel free to inherit from these classes and override methods or provide new ones as you see fit (but bear in mind #2465).

**Comment by rowanmiller** [comment] 2015-07-01 01:08
I think we need to quickly discuss how we want the "provider invariant name" to work in EF7. My vote is that we just use the assembly/package name, but we should discuss this.

**Comment by ErikEJ** [comment] 2015-07-01 05:23
@lajones Thanks, that should be enough to get me going, will also await your "unblocking" of the hardcoded provider name. 
Re 3: - This is my understanding of the workflow, can you sanity check?

1: As a developer, I want to reverse engineeer my existing SQL CE database to use it with EF7.
2: In my project.json (if I have one) or using Package Manager Console, I add the 
EntityFramework7.SqlServerCompact40.Design package in my Data Access project
3: To use the Reverse-Engineer command from PMC I must also add the EntityFramework7.Commands package
4: I can now run the "Reverse-Engineer" command, specifying a connection string and the name of the design package (or dll) : EntityFramework7.SqlServerCompact40.Design

Is that just about correct?

**Comment by ErikEJ** [comment] 2015-07-01 08:21
Ouch: SqlServerMetadataModelProvider - 663 lines of code - more code than currently in the SQLCE provider itself.

**Comment by divega** [comment] 2015-07-01 15:41
@ErikEJ Feel free to propose refactorings. Perhaps it can be simplified, perhaps there are opportunities form code reuse. Keep un mind that this is going from having just one provider to having two, and SQL Server and SQL CE being relatively similar, some common functionality may emerge.

**Comment by divega** [comment] 2015-07-01 16:22
> My vote is that we just use the assembly/package name

Agreed. Would it be possible (as an option) to specify the value in the registration of the command in project.json so that you don't need to pass it every every time in the command line?

**Comment by ajcvickers** [comment] 2015-07-01 16:56
@divega @rowanmiller The InvariantName property of IDatabaseProviderServices currently returns the assembly/package name for our providers.

**Comment by lajones** [comment] 2015-07-01 17:21
The assembly name is easy - in fact it's what we already use - it's just that we pass it in hard-coded rather than reading the expected name from the command-line. It's easy to add an argument (say --provider) that passes it in.

@rowanmiller - need to know whether this is a required argument (command line will fail if it's not passed in) or optional (presumably with default of EntityFramework.SqlServer.Design if not passed).

**Comment by rowanmiller** [comment] 2015-07-01 21:12
A few of us just discussed and came up with the following:
* Providers are identified by their assembly name.
 * What is currently `ProviderInvariantName` becomes `ProviderAssemblyName`.
 * Given `-Provider EntityFramework7.SqlServer` in a command we just load that assembly as the provider.
* Provider assemblies contain an attribute that identifies what type can give you design time services (such as reverse engineer components).
 * This can be a type from another assembly. For example, our `EntityFramework7.SqlServer` provider will point to a type in the `EntityFramework7.SqlServer.Design` assembly.
* In the future we can add another attribute for runtime services when we support provider name being specified in config. This isn't needed yet because you have to specify the provider in code (i.e. `UseSqlServer`, etc.)

@lajones will work on implementing this

**Comment by rowanmiller** [comment] 2015-07-01 21:15
BTW another nice side effect of this is that we can be helpful when we have the runtime of the provider installed and there are design services in a separate assembly/package that is not installed. Something like:
> Hey, you're trying to reverse engineer using EntityFramework7.SqlServer. You probably want to install EntityFramework7.SqlServer.Design to get the design components for this provider.

**Comment by lajones** [comment] 2015-07-01 23:25
Just some notes on the above. The reference to the "type that can give you design time services" is not a hard reference to the type - it's a soft reference to the _names_ of the assembly and the type within it that provide those services.

Also we agreed that the --provider argument is required, not optional.

@ErikEJ  your a. thru e. steps above are correct except that with the new design above you'll want to reference the _runtime_ package (EntityFramework7.SqlServerCompact40) in step d. and we will use that to look up the design-time assembly/type using the attribute specified above.

**Comment by ErikEJ** [comment] 2015-07-02 09:01
@lajones Sounds great! I will await the changes to this before I begin coding the SQLCE design provider

**Comment by ErikEJ** [comment] 2015-07-02 11:48
@lajones Had a quick look, and it looks to me like these classes are not SQL Server specific, so could go in the base class (or somewhere else??):
CodeAnnotations.cs
LoggingExtensions.cs
SharedTypeExtensions.cs
StringBuilderExtensions.cs
Check.cs
SqlServerNameMapper.cs
SqlServerNavigationPropertyInitializer.cs
SqlServerNavigationProperty.cs

Wonder if the Model classes can be generalized, so each provider only has to supply the SQL statement for each model type?

**Comment by lajones** [comment] 2015-07-02 16:30
@erikej The first 5 already come from the src\Shared dir. But your comment on the other 3 is good. I'll move them.

Re the last comment I want to be careful to allow each provider as much flexibility as possible on how to load it's own metadata - as how providers do that can differ widely. But there may be a way to refactor it so that if you want to re-use much of the existing functionality you can do so without stopping providers loading metadata in a completely different way if they so wish.

**Comment by ErikEJ** [comment] 2015-07-02 16:38
@lajones Agree that it is a good thing to allow flexibilty in how metadata is obtained, so just keep the current Model in the SQL Server provider (for "inspiration"). 

Regarding these 5 files:
CodeAnnotations.cs
 LoggingExtensions.cs
 SharedTypeExtensions.cs
 StringBuilderExtensions.cs
 Check.cs

- please beware that I do not reference the source code, only the NuGet packages, meaning I have to copy these files (some I have copied already to the SQLCE provider code base) - and that seems anti-DRY.

Not sure how you can share these "Extensions" - maybe a separate project published as another NuGet package?

Doing that will shrink the codebase in both the SQLCE provider and the future SQLCE Design project - and the less code the better!

**Comment by lajones** [comment] 2015-07-02 20:23
@ErikEJ - the team discussed this and decided that, since they are small, internal classes (which we want to keep internal) and the current method of sharing works well for our hybrid csproj/project.net dev environment (among other things) - we would keep it as is. But for you - you may not need any of those files - for instance Check.cs has the NotNull() etc methods, CodeAnnotations.cs has the [NotNull] etc annotations. Feel free to copy what you need and to ignore the rest.

**Comment by lajones** [comment] 2015-07-07 23:37
Fixed above issue with commit  28c29a1. @ErikEJ stand by for another check in moving the 3 classes mentioned above.

**Comment by ErikEJ** [comment] 2015-07-10 13:03
@lajones @divega @rowanmiller Rev Eng now works for the SQLCE provider! Thanks for your timely support :smile:

**Comment by rowanmiller** [comment] 2015-07-10 16:31
Sweet :tada:

**Comment by divega** [comment] 2015-07-10 19:08
@ErikEJ not sure if I have said this before but... you rock! :simile:

**Comment by ErikEJ** [comment] 2015-07-10 20:00
@divega @lajones  Thanks to your excellent groundwork!

**Comment by lajones** [comment] 2015-07-10 20:02
@ErikEJ You're v welcome. Thanks for all your hard work!

**Comment by ErikEJ** [comment] 2015-07-11 10:21
@lajones And the E2E tests revealed a couple of small bugs in my SQL CE scripting engine: https://sqlcetoolbox.codeplex.com/SourceControl/changeset/96873 - thanks!

**Comment by lajones** [comment] 2015-07-11 16:14
@ErikEJ - Glad to help!

**Comment by lajones** [comment] 2015-07-30 18:43
Closing this over-arching issue for the whole of RevEng. Now we'll track each individual bug/feature as it comes up. Raised issue #2751 to track ability to select tables.

**Closed by lajones** 2015-07-30 18:43 UTC
Labels: 1 - Working, enhancement, pri0

**Comment by claysmith** [comment] 2015-09-04 00:17
How do you specify the output path for ef scaffold reverse engineering?

**Comment by lajones** [comment] 2015-09-04 00:32
A lot has changed since the above comments. If you do `dnx ef dbcontext scaffold --help` it will give you the options. Specifically there's a `-o` option on the command line to specify a sub-directory of whatever project you are in.

**Comment by claysmith** [comment] 2015-09-04 01:17
I am running CLR-x64-1.0.0-beta7-15532 and -o is not an option

**Comment by alfberga** [comment] 2015-09-04 10:28
And i'm running CLR-x64-1.0.0-beta7-15540 and -o is not an option too. 
And no DataAnnotation in reverse engineering generated models

**Comment by ErikEJ** [comment] 2015-09-04 12:17
You need to run a beta 8 daily build for that feature to work. And you need to customize the templates in order to force the tooling to use DataAnnotations (I am working on a blog post)

**Comment by lajones** [comment] 2015-09-04 16:08
@claysmith - that's correct - the `-o` option was checked in with commit 5b19fbb. Before that you could only output to the project path. You are of course free to move the files after they've been output.
@ErikEJ - don't work too hard on that blog post. Things have been churning a lot in this area (which is why I haven't written any docs about it). #2947 changes it so we no longer allow customizable templates.

**Comment by ErikEJ** [comment] 2015-09-04 16:59
@lajones  thanks for the heads up! How do you switch between attribute and fluent then?

**Comment by lajones** [comment] 2015-09-04 17:03
@ErikEJ Current plan is to have a command-line switch - see PR https://github.com/aspnet/EntityFramework/pull/3013

**Comment by alfberga** [comment] 2015-11-26 15:13
Sorry for an old question: when do you think to develop the reverse engineering of Views?

**Comment by rowanmiller** [comment] 2015-11-30 19:18
@alfberga that will happen after the initial RTM of EF7. 

@lajones is there any way to track reverse engineer into thinking a view is a table at the moment?

**Comment by lajones** [comment] 2015-11-30 20:42
You mean "trick" reverse engineering? No I'm afraid not. Each provider retrieves the corresponding metadata in their own `*DatabaseModelFactory` code. 

On the other hand it's not likely to be complicated to add it. We have an existing issue for this: #1679. It's been on the Backlog for a while - perhaps it's time to revisit it?

**Comment by roji** [comment] 2015-12-04 11:38
FYI everyone, I've just published the [Npgsql reverse engineering provider](https://www.nuget.org/packages/EntityFramework7.Npgsql.Design/). I've confirmed that the EF7 database-first tutorial works just fine with it.

**Comment by ErikEJ** [comment] 2015-12-04 14:28
Congrats!

**Comment by lajones** [comment] 2015-12-04 20:12
Yep congrats! Really cool!
