### ISSUE TITLE
Calling ICollection<>.Contains() with a nested propery throws an InvalidOperationException

### ISSUE THREAD

**Issue by MaxxDelusional** [aspnet/EntityFramework#4394] opened 2016-01-25 20:12 UTC
The following query will work

    long[] teacherIDs = new long[] { 123, 456 };    
    var query = from x in context.Students
                       where teacherIDs.Contains(x.TeacherID)
                       select x;

But this query will not

    long[] schoolIDs = new long[] { 789, 999 };    
    var query = from x in context.Students
                       where schoolIDs.Contains(x.Teacher.SchoolID)
                       select x;

It will throw an InvalidOperationException: Sequence contains more than one element.

Possibly the same as #153

**Comment by rowanmiller** [comment] 2016-01-25 21:38
@maumar is this covered by an issue you are working on?

**Comment by maumar** [comment] 2016-01-25 23:12
I'm working on optional navigation translation. However this scenario seems to be broken for both optional and required. @mikary fixed a bunch of issues around contains recently, and filed some new ones (eg, #4352, #4355). This might be the same root cause, even though exception is different.

**Comment by rowanmiller** [comment] 2016-02-02 19:25
@mikary can you see if this is fixed

**Comment by mikary** [comment] 2016-02-03 18:54
I tried to reproduce the issue with Northwind:
```cs
        [ConditionalFact]
        public virtual void ContainsRepro()
        {
            using(var context = CreateContext())
            {
                var orderIds = new int[] { 10248, 11077 };

                var query = from x in context.OrderDetails
                            where orderIds.Contains(x.Order.OrderID)
                            select x;

                var y = query.ToList();
            }
        }
```

It doesn't appear to throw, but it also doesn't use the code path for the issues around contains that I had fixed. This may have been fixed by a different change.

**Comment by divega** [comment] 2016-02-03 19:03
So we can close it?

**Comment by mikary** [comment] 2016-02-03 19:12
The repro looks pretty straight forward and I don't believe there's anything specific to the model that would cause this kind of error.

**Closed by mikary** 2016-02-03 19:12 UTC
Labels: bug, pri0

**Comment by sadjadbp** [comment] 2016-03-23 00:31
What is the alternative way to perform that query, since RC2 is not coming out soon?

**Comment by mikary** [comment] 2016-03-23 17:59
I wasn't able to reproduce the original issue, but it might work if you try with something like this:
```cs
long[] schoolIDs = new long[] { 789, 999 };    
var query = from x in context.Students
                   join t in context.Teachers on x.TeacherID equals t.TeacherID
                   where schoolIDs.Contains(t.SchoolID)
                   select x;
```

If you are still having problems, please provide a reproduction of the issue along with the model and full stack trace so we can better diagnose the problem

**Comment by sadjadbp** [comment] 2016-03-24 00:25
@mikart thanks. I'm sure the bug is there in rc1 so I wait for rc2 to test and repot again. For now I use another way.

**Comment by Thealexbarney** [comment] 2016-04-07 00:22
Here's a complete repro:

```
using Microsoft.Data.Entity;
using System.Collections.Generic;
using System.Linq;

namespace ContainsBugRepro
{
    class Program
    {
        static void Main(string[] args)
        {
            var ids = new List<int> {1,2,3};

            using (var db = new Context())
            {
                var goodQuery = db.Purchases
                    .Where(x => ids.Contains(x.ItemCount));

                goodQuery.ToList(); //success

                var badQuery = db.Purchases
                    .Where(x => ids.Contains(x.Customer.Age));

                badQuery.ToList(); //exception
            }
        }
    }

    public class Context : DbContext
    {
        public DbSet<Purchase> Purchases { get; set; }
        public DbSet<Customer> Customers { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseInMemoryDatabase();
        }
    }

    public class Purchase
    {
        public int Id { get; set; }
        public int ItemCount { get; set; }
        public int CustomerId { get; set; }
        public Customer Customer { get; set; }
    }

    public class Customer
    {
        public int Id { get; set; }
        public int Age { get; set; }
    }
}
```

**Comment by maumar** [comment] 2016-04-07 01:57
@Thealexbarney  thanks, I just verified this against our current dev branch and it works (no exception)
