### ISSUE TITLE
InvalidCastException when casting from one value type to another in a simple select statement

### ISSUE THREAD

**Issue by samb0t** [aspnet/EntityFramework#8652] opened 2017-05-31 19:55 UTC
[InvalidCastApp.zip](https://github.com/aspnet/EntityFramework/files/1045495/InvalidCastApp.zip)
When casting a property from a nullable double to a nullable int in a `Select` function, an InvalidCastException occurs. Likewise, the same exception occurs if the types are not nullable.

Attached is a working example of the issue. Just create the database and table first and then update the connection string in `Program.cs`.

The select looks like this:
```               
.Select(o => new DTO() {  
  Limit = o.Limit__c.HasValue ? (int?)o.Limit__c : null,   
  Slots = o.Slots__c.HasValue ? (int?)o.Slots__c : null  
  })  
  .Where(o => cIds.Contains(o.CId))  
  .ToListAsync());  
```
`Limit__c` and `Slots__c` are nullable doubles
The SQL profiler does not show any casting before the exception is thrown.
The same query was working in EF 6.x (Full Framework).
```
Exception message: Specified cast is not valid.
Stack trace:
<error errorId="7f262bc2-3b41-439b-be10-ed2c6e480a0f" application="/LM/W3SVC/2/ROOT" host="" type="System.InvalidCastException" message="Specified cast is not valid." source="Anonymously Hosted DynamicMethods Assembly" detail="System.InvalidCastException: Specified cast is not valid.;  
 at lambda_method(Closure , QueryContext , ValueBuffer );  
 at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer valueBuffer);  
 at Microsoft.EntityFrameworkCore.Query.AsyncQueryMethodProvider.&lt;&gt;c__DisplayClass3_0`1.&lt;_ShapedQuery&gt;b__0(ValueBuffer vb);  
 at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.&lt;MoveNextCore&gt;d__7.MoveNext();--- End of stack trace from previous location where exception was thrown ---;  
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task);  
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task);  
 at System.Linq.AsyncEnumerable.AsyncIterator`1.&lt;MoveNext&gt;d__10.MoveNext();--- End of stack trace from previous location where exception was thrown ---;  
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task);  
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task);  
 at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.&lt;MoveNext&gt;d__5.MoveNext();--- End of stack trace from previous location where exception was thrown ---;  
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task);  
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task);  
 at System.Linq.AsyncEnumerable.&lt;Aggregate_&gt;d__6`3.MoveNext();--- End of stack trace from previous location where exception was thrown ---;  
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task);  
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task);  
 at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult();  
 at --snip--.&lt;WithContext&gt;d__5`1.MoveNext();--- End of stack trace from previous location where exception was thrown ---;  
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task);  
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task);  
 at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult();  
 at --snip--.&lt;GetByContractIds&gt;d__13.MoveNext();--- End of stack trace from previous location where exception was thrown ---;  
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task);  
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task);  
 at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult();  
 at --snip--d__54.MoveNext() in 
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task);  
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task);  
 at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult();  
 at --snip--Load&gt;d__14.MoveNext() in 
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task);  
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task);  
 at System.Runtime.CompilerServices.TaskAwaiter.GetResult();  
 at --snip--Contract&gt;d__70.MoveNext() in 
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task);  
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task);  
 at System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult);  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.&lt;&gt;c__DisplayClass37.&lt;BeginInvokeAsynchronousActionMethod&gt;b__36(IAsyncResult asyncResult);  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult);  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.&lt;InvokeActionMethodFilterAsynchronouslyRecursive&gt;b__3d();  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.&lt;&gt;c__DisplayClass46.&lt;InvokeActionMethodFilterAsynchronouslyRecursive&gt;b__3f();  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult);  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.&lt;&gt;c__DisplayClass21.&lt;&gt;c__DisplayClass2b.&lt;BeginInvokeAction&gt;b__1c();  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.&lt;&gt;c__DisplayClass21.&lt;BeginInvokeAction&gt;b__1e(IAsyncResult asyncResult);  
 at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult);  
 at System.Web.Mvc.Controller.&lt;BeginExecuteCore&gt;b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState);  
 at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult);  
 at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult);  
 at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult);  
 at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult);  
 at System.Web.Mvc.MvcHandler.&lt;BeginProcessRequest&gt;b__5(IAsyncResult asyncResult, ProcessRequestState innerState);  
 at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult);  
 at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult);  
 at System.Web.HttpApplication.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar)" user="" time="2017-05-31T19:14:36.8015246Z">

```

### Steps to reproduce
1. Create a table with a column defined as `decimal(18,0),null` and an `int` primary key.
2. Use the project in the attached zip, first updating the connection string in `Program.cs`.
3. Running the application will give the invalid cast exception.
```
.Select(o => new DTO() {  
  ModelWithNullableInt = o.ModelWithNullableDecimal.HasValue ? (int?)o.ModelWithNullableDecimal: null})  
```

### Further technical details
EF Core version: Reproduced in 1.1.2 as well as 2.0.0-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 64-bit
IDE: Visual Studio 2017 - build 26510.0 Preview

**Comment by maumar** [comment] 2017-06-16 23:21
fixed in 44e73165c984fba71e227e4933be41cf1d2d213d

**Closed by maumar** 2017-06-16 23:21 UTC
Labels: type-bug

**Comment by natelaff** [comment] 2017-10-24 14:56
I'm seeing this in 2.0.3 preview. 

The following will throw an InvalidCastException. Worked fine in 1.1

        public async Task<decimal> GetSubtotalTotalAsync(string cartId)
        {
            return await _context.CartItems
                .Include(c => c.ProductVariant)
                .Where(c => c.CartId == cartId)
                .Select(c => c.ProductVariant.Price.GetValueOrDefault() * c.Quantity)
                .SumAsync();
        }

**Comment by ajcvickers** [comment] 2017-10-24 15:50
@natelaff Is this something that worked for you in 2.0.0 but is now failing in 2.0.3 preview? Can you post or link to a full project or code listing that demonstrates the issue so we can investigate it?

**Comment by natelaff** [comment] 2017-10-24 15:55
@ajcvickers I'm uncertain. There were so many regressions in 2.0 that I couldn't even get this far into migrating my app until now. I will try to repro in a clean project.

**Comment by ajcvickers** [comment] 2017-10-24 15:58
@maumar Can you please investigate this?

**Comment by maumar** [comment] 2017-10-24 19:21
I verified this is a bug in the current bits, but it's *not a regression*. The bug is not related to this one, so I will file a new issue to track this.

workaround is to perform the multiplication and sum on the client (it would be done so anyway, because we don't know how to translate GetValueOrDefault - will file an issue for this also)

here is the code that should work:

```
        public async Task<decimal> GetSubtotalTotalAsync(string cartId)
        {
            using (var ctx = new MyContext())
            {
                var result = await ctx.CartItems
                    //.Include(c => c.ProductVariant) - include was not needed here navigation access will do this automatically
                    .Where(c => c.CartId == cartId)
                    .Select(c => new { Price = c.ProductVariant.Price, c.Quantity })
                    .ToListAsync();

                return result
                    .Select(c => c.Price.GetValueOrDefault() * c.Quantity)
                    .Sum();
            }
        }
```

**Comment by maumar** [comment] 2017-10-24 19:37
filed https://github.com/aspnet/EntityFrameworkCore/issues/10152 and https://github.com/aspnet/EntityFrameworkCore/issues/10153
