### ISSUE TITLE
Reverse engineer bool column with default constraint to nullable bool property

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#8400] opened 2017-05-07 20:50 UTC
A default constraint on a bool column mapped to a bool property with ValueGenerated.OnAdd has no value in EF--see #7089 for discussion.

Instead, if the property is nullable, then:
* Not setting the property will result in the default constraint being used.
* Setting to either true or false will result in the correct value being inserted.

**Comment by popcatalin81** [comment] 2017-05-09 06:58
I really don't know if this is the correct solution, because after this change we will have to undo "two" changes made by scaffolding: 1) make the bool not nullable (as it was in DB) and 2) remove the HasDefaultValueSql, in order to have wanted behavior in the model: not nullable boolean colums with default value.

**Comment by ajcvickers** [comment] 2017-05-09 15:23
@popcatalin81 That's also a reasonable interpretation if the default constraint is simply "true", but the nullable property preserves the use of the constraint in the database, whether it generates true or false, including it sometimes generating true and sometimes false based on other conditions.

**Comment by ajcvickers** [comment] 2017-05-16 21:17
@lajones Is this a breaking change because it will generate different code than before? If so, then I don't think we need to track this as a breaking change.

**Comment by lajones** [comment] 2017-05-16 21:28
@ajcvickers Yes. And also I'm wondering about round-tripping. I.e. if I regen the DB using migrations from the model that scaffolding would produce would it produce the same DB?

**Comment by ajcvickers** [comment] 2017-05-16 22:03
@lajones Probably wouldn't create the same DB in this case, but I think that is okay. @divega?

**Comment by divega** [comment] 2017-05-18 06:18
I do think it is ok if roundtripping doesn't generate the same column type in this case. The wrinkle is in the fact that the default SQL value can be an any expression that returns a Boolean. We are optimizing reverse engineering for the common case in which it is just a constant and as @ajcvickers explained having the property as a non-nullable Boolean has very little value. But going in the opposite direction, at least in the general case the SQL default is opaque to us and we don't know for sure if it can't evaluate to null.

BTW, thinking about the original problem we are trying to solve here, I am thinking now that I would be ok if this was a warning (either in reverse engineering or in the runtime) rather than making a choice for the user to change the type. But I cannot remember if there was a reason we didn't want to do that.

**Comment by lajones** [comment] 2017-05-18 16:35
@divega
> But going in the opposite direction, at least in the general case the SQL default is opaque to us and we don't know for sure if it can't evaluate to null

... and the issue is that in the original database this would have caused an error when you try to use the default and the default evaluates to `NULL` (which presumably would make the DBA want to re-write the SQL default), whereas in the round-tripped database the value `NULL` would just be inserted and could then cause app logic problems when the app is expecting it to be only true or false?

#7163 is about the warning - it's currently assigned to @ajcvickers - so I'm guessing it would be a runtime warning. I think adding a reverse engineering warning as part of this work would be good too.

**Comment by ajcvickers** [comment] 2017-05-18 17:22
@divega As @lajones said, we are planning to warn for this in model validation anyway. The reason to change reverse engineering is that it creates a model that works, instead of one that doesn't really work and has a warning. Also, with regard to roundtripping, the database created will be different--will have a nullable column--but when accessed from EF it will work the same as before. When not accessed from EF, all positive cases will work the same. I honestly don't think that the roundtripping it a big factor here--I think it's better to create a model that works.

**Comment by ajcvickers** [comment] 2017-05-18 17:24
Also, removing the breaking change flag, because this isn't a runtime breaking change to any existing app, and as such isn't something that we should track here as a breaking change even though I can understand the case being made that it will create a different model now.

**Comment by divega** [comment] 2017-05-19 14:46
I am ok with the plan @ajcvickers.

**Comment by lajones** [comment] 2017-06-09 20:30
Fixed by PR #8777.

**Closed by lajones** 2017-06-09 20:30 UTC
Labels: type-enhancement
