### ISSUE TITLE
RC2. Bad SQL strategy when LINQ lambda where clause contains references hierarchy

### ISSUE THREAD

**Issue by AR1ES** [aspnet/EntityFramework#5457] opened 2016-05-21 15:22 UTC
I have a three models with one-to-one relationship. I need to use these relations in where clause. But instead of a single query EF executes multiple SQL statements.
Models (only relations):

```
	public class PlayerModel {
		public virtual PlayerOnlineModel PlayerOnline { get; set; }
	}
	
	public class PlayerOnlineModel {
		public virtual PlayerModel Player { get; set; }
	}
	
	public class AdminModel {
		public virtual PlayerModel Player { get; set; }
	}
```

My LINQ expression:
```
	var players = await _db.Admins
		.Where(p => p.Player != null && p.Player.PlayerOnline != null)
		.ToListAsync();
```

I expect SQL like this:
```
SELECT XXX
FROM [Admins] AS [p]
LEFT JOIN [Players] AS [p.Player] ON [p].[PlayerId] = [p.Player].[Id]
LEFT JOIN [PlayersOnline] AS [p.Player.PlayerOnline] ON [p.Player.PlayerOnline].[Id] = [p.Player].[Id]
WHERE [p.Player].[Id] IS NOT NULL AND [p.Player.PlayerOnline].[Id] IS NOT NULL
```

Or like this: 
```
SELECT XXX
FROM [Admins] AS [p]
JOIN [Players] AS [p.Player] ON [p].[PlayerId] = [p.Player].[Id]
JOIN [PlayersOnline] AS [p.Player.PlayerOnline] ON [p.Player.PlayerOnline].[Id] = [p.Player].[Id]
```

But real result contains two SQL statements:
```
SELECT XXX
FROM [PlayersOnline] AS [p.Player.PlayerOnline]


SELECT XXX
FROM [Admins] AS [p]
LEFT JOIN [Players] AS [p.Player] ON [p].[PlayerId] = [p.Player].[Id]
WHERE [p].[PlayerId] IS NOT NULL
```

**Comment by maumar** [comment] 2016-05-23 22:16
duplicate of https://github.com/aspnet/EntityFramework/issues/4588

**Closed by maumar** 2016-05-23 22:16 UTC
Labels: bug, pri0
