### ISSUE TITLE
Multiple problems with 13202

### ISSUE THREAD

**Issue by matthewDDennis** [aspnet/EntityFramework#2232] opened 2015-05-19 21:29 UTC
I have a Linq query
```c#
            var query = _contentDbContext.Articles.AsNoTracking()
                                        .Include(a => a.Authors)
                                        .ThenInclude(a => a.Member)
                                        .Where(a => a.PublishingStatusId == (byte)2 &&
                                                    a.ArticleTypeId == (byte)1
                                         );

            var articles = await query
                                .Select(a => new
                                {
                                    a.Id,
                                    a.ArticleTypeId,
                                    a.Posted,
                                    a.Updated,
                                    a.Title,
                                    a.Authors,
                                    a.Description,
                                    a.SubsectionId,
                                    a.TagIds,
                                    a.LicenseId,
                                    a.SourceUrl,
                                    a.BaseName,
                                    a.Slug,
                                    a.PageViews,
                                    a.DownloadCount,
                                    a.Thumbnail
                                })
                                .OrderByDescending(a => a.Updated)
                                .Skip((page.Value-1) * pageSize.Value)
                                .Take(pageSize.Value)
                                .ToListAsync()
                                .ConfigureAwait(false);

```
1 the result does not contain any of the included Authors
2 if I comment out the .Select(), the I get error complaining the a.PublishingStatusId and a.ArticleTypeId do not exist and that I need to run a migration

If I just ask for one Article, I get the Authors
```c#
            Article article = await _contentDbContext.Articles.AsNoTracking()
                                        .Include(a => a.Authors)
                                        .ThenInclude(a => a.Member)
                                        .Where(a => a.Id == articleId)
                                        .SingleOrDefaultAsync()
                                        .ConfigureAwait(false);
```

**Comment by maumar** [comment] 2015-05-19 21:32
Could you provide a repro project that we could use to investigate the issue?

**Comment by matthewDDennis** [comment] 2015-05-19 23:49
Will do on the morning.

-----Original Message-----

**Comment by matthewDDennis** [comment] 2015-05-20 17:26
You can get the repository with tests that recreate the issues at
https://github.com/matthewDDennis/E7Issue.git

**Comment by maumar** [comment] 2015-05-20 20:15
Thanks!

**Comment by matthewDDennis** [comment] 2015-05-21 02:05
I've updated the test repo to correctly use Identity Primary Keys.

**Comment by maumar** [comment] 2015-06-08 20:59
Simplified repro:

```
    public class Article
    {
        public int Id { get; set; }
        public byte ArticleTypeId { get; set; }

        public virtual IList<ArticleMember> Authors { get; } = new List<ArticleMember>();
    }

    public class ArticleMember
    {
        public int ArticleId { get; set; }
        public virtual Article Article { get; set; }
    }

    public class ArticleDbContext : DbContext
    {
        public DbSet<Article> Articles { get; set; }
        public DbSet<ArticleMember> ArticleMembers { get; set; }

        protected override void OnConfiguring(EntityOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=.;Database=Repro2232;Trusted_Connection=True;MultipleActiveResultSets=true");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Article>(b =>
            {
                b.Table("Article");
                b.Key(a => a.Id);
                b.Property(a => a.Id).Column("ArticleId").ForSqlServer().UseIdentity();
            });

            modelBuilder.Entity<ArticleMember>(b =>
            {
                b.Table("Article_Member");
                b.Key(am => am.ArticleId);
                b.Property(am => am.ArticleId).Column("ArticleId").ForSqlServer().UseNoValueGeneration();
                b.Reference(am => am.Article).InverseCollection(a => a.Authors)
                                              .ForeignKey(am => am.ArticleId)
                                              .PrincipalKey(a => a.Id);
            });
        }
    }


    class Program
    {
        static void Main(string[] args)
        {
            InitializeDatabase();

            using (var ctx = new ArticleDbContext())
            {
                int? page = 1;

                var articles = ctx.Articles
                    .Include(a => a.Authors)
                    .Where(a => a.ArticleTypeId == 1)
                    .Skip(page.Value)
                    .ToList();
            }
        }

        private static void InitializeDatabase()
        {
            using (var ctx = new ArticleDbContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                for (int i = 1; i <= 3; i++)
                {
                    ctx.Articles.Add(new Article { ArticleTypeId = 1, });
                }

                ctx.SaveChangesAsync();

                var articles = ctx.Articles.ToArray();

                for (int i = 0; i < 3; i++)
                {
                    ctx.ArticleMembers.Add(new ArticleMember { Article = articles[i], });
                }

                ctx.SaveChangesAsync();
            }
        }
    }
```

**Comment by maumar** [comment] 2015-06-08 21:00
Query that gets generated that causes the problem is as follows:

```
SELECT [a].[ArticleId]
FROM [Article_Member] AS [a]
INNER JOIN (
    SELECT DISTINCT [t0].*
    FROM (
        SELECT [a].[ArticleId], [a].[ArticleTypeId]
        FROM [Article] AS [a]
        ORDER BY [a].[ArticleId]
        OFFSET 1 ROWS
    ) AS [t0]
    WHERE [a].[ArticleTypeId] = 1
) AS [a0] ON [a].[ArticleId] = [a0].[ArticleId]
ORDER BY [a0].[ArticleId]
```

**Comment by maumar** [comment] 2015-08-19 23:32
This is fixed in the current bits. We produce the following TSQL now:

```
SELECT [a].[ArticleId]
FROM [Article_Member] AS [a]
INNER JOIN (
    SELECT DISTINCT [t0].*
    FROM (
        SELECT [a].[ArticleId], [a].[ArticleTypeId]
        FROM [Article] AS [a]
        WHERE [a].[ArticleTypeId] = 1
        ORDER BY [a].[ArticleId]
        OFFSET 1 ROWS
    ) AS [t0]
) AS [a0] ON [a].[ArticleId] = [a0].[ArticleId]
```

**Closed by maumar** 2015-08-19 23:32 UTC
Labels: bug, pri0
