### ISSUE TITLE
Projection with classes that have the same property name conflicts the results when using SKIP+TAKE

### ISSUE THREAD

**Issue by jsgoupil** [aspnet/EntityFramework#6456] opened 2016-09-02 05:58 UTC
When using a simple projection with .Skip().Take().Select() that joins another table, if the table contains the same ID they collapse and return incorrect results.

Example:
```
    public class TableA
    {
        public int Id { get; set; }
        public DateTime Date1 {get;set;}
        public TableB TableB { get;set;}
        public int? TableBId {get;set;}
    }

    public class TableB
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
```

This request:
```
            var result = dbContext.TableAs
                .OrderByDescending(m => m.Date1)
                .Skip(0)
                .Take(50)
                .Select(m => new
            {
                Id = m.Id,
                TableBName = m.TableB.Name,
            }).ToList();
```
Will result in 
```
exec sp_executesql N'SELECT [m.TableB].[Id], [m.TableB].[Name], [t].[Id]
FROM (
    SELECT [m0].*
    FROM [TableAs] AS [m0]
    ORDER BY [m0].[Date1] DESC
    OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY
) AS [t]
LEFT JOIN [Counties] AS [m.TableB] ON [t].[TableBId] = [m.TableB].[Id]
ORDER BY [t].[TableBId]',N'@__p_0 int,@__p_1 int',@__p_0=0,@__p_1=50
```
The ID of the class `TableB` ends up as the Id of the TableA.

If you remove the Skip/Take, the query becomes simple like this
```
SELECT [m].[Id], [m].[TableBId], [m].[Date1], [m.TableB].[Id], [m.TableB].[Name] FROM [TableAs] AS [m]
LEFT JOIN [Counties] AS [m.TableB] ON [m].[TableBId] = [m.TableB].[Id]
ORDER BY [m].[Date1] DESC, [m].[TableBId]
```

Visual Studio 2015 Update 3
"Microsoft.EntityFrameworkCore.SqlServer": "1.0.0"

**Comment by divega** [comment] 2016-09-02 18:31
**EF Team Triage:** We think this is probably fixed in our working code base. Would you be able to try our nightly builds and see if the issue is resolved for you. Nightly builds are available from https://dotnet.myget.org/Gallery/aspnetcore-ci-dev.

**Comment by divega** [comment] 2016-09-02 18:32
@smitpatel does this look like something we already fixed?

**Comment by smitpatel** [comment] 2016-09-06 18:25
> The ID of the class  TableB  ends up as the Id of the TableA.

Can you explain more what are the result you are seeing? I tried running above query with RTM release and results generated are as expected.

**Comment by jsgoupil** [comment] 2016-09-06 20:30
I definitely over simplified this code and my database changed quite a bit to go around this problem.
Basically, if the code is about to do a "exec sp_executesql" instead of a plain request, that's where it was causing a problem.
I'm able to repro if you do the Skip().Take BEFORE the Select() AND I think you need two columns projected with the same name.
Here is my raw code:
            var s = query
            .Skip(0).Take(100)
            .Select(m => new Common.Models.JSON.LicenseTransfer
            {
                Id = m.Id,
                CountyName = m.County.Name, // Issue
                LicenseType = m.LicenseType.Name, // Issue

            }).ToList();

If you tell me how I can try the latest in my project.json, I can give it a try.

**Comment by smitpatel** [comment] 2016-09-06 21:05
@jsgoupil - Can you share model classes relevant to above query? and what is `query`?

**Comment by jsgoupil** [comment] 2016-09-06 21:23
@smitpatel is your github name your microsoft alias? I could forward the two files to your e-mail. (I used to work at MS)

**Comment by jsgoupil** [comment] 2016-09-06 21:23
@smitpatel is your github name your microsoft alias? I could forward the two files to your e-mail. (I used to work at MS)

**Comment by smitpatel** [comment] 2016-09-06 21:42
alias: smpatel

**Comment by jsgoupil** [comment] 2016-09-06 21:43
@smitpatel perfect! I sent it

**Comment by smitpatel** [comment] 2016-09-06 23:17
I am not able to reproduce this.
Following is the repro code I used:
```c#
public class Program
{
    public static void Main(string[] args)
    {
        using (var db = new MyContext())
        {
            var serviceProvider = db.GetInfrastructure();
            var loggerFactory = serviceProvider.GetService<ILoggerFactory>();
            loggerFactory.AddConsole(LogLevel.Information);
        }

        using (var db = new MyContext())
        {
            db.Database.EnsureDeleted();
            db.Database.EnsureCreated();

            var county1 = new County { Name = "King" };
            var county2 = new County { Name = "Snohomish" };

            var type1 = new LicenseType { Name = "Learner" };
            var type2 = new LicenseType { Name = "Permanent" };

            db.AddRange(county1, county2, type1, type2);
            var rand = new Random();

            for (int i = 0; i < 20; i++)
            {
                var flag1 = rand.Next(0, 2) % 2 == 0;
                var flag2 = rand.Next(0, 2) % 2 == 0;
                var flag3 = rand.Next(0, 2) % 2 == 0;

                db.Add(new LicenseTransfer
                {
                    County = flag1 ? county1 : county2,
                    LicenseType = flag2 ? type1 : type2,
                    Valid = flag3
                });
            }

            db.SaveChanges();
        }

        using (var db = new MyContext())
        {
            var query = db.LicenseTransfers
                .Where(m => m.Valid)
                .Skip(0)
                .Take(100)
                .Select(m =>
                    new
                    {
                        Id = m.Id,
                        CountyName = m.County.Name, // Issue
                        LicenseType = m.LicenseType.Name, // Issue
                }).ToList();
        }
    }
}


public class MyContext : DbContext
{
    public DbSet<County> Counties { get; set; }
    public DbSet<LicenseTransfer> LicenseTransfers { get; set; }
    public DbSet<LicenseType> LicenseTypes { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;")
            .EnableSensitiveDataLogging();
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        foreach (var relationship in modelBuilder.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()))
        {
            relationship.DeleteBehavior = relationship.IsRequired ? DeleteBehavior.Restrict : DeleteBehavior.SetNull;
        }
        base.OnModelCreating(modelBuilder);
    }

}

public class County
{
    public int Id { get; set; }
    public string Name { get; set; }
    public List<LicenseTransfer> LicenseTransfers { get; set; }
}

public class LicenseTransfer
{
    public int Id { get; set; }
    public County County { get; set; }
    public int? CountyId { get; set; }
    public LicenseType LicenseType { get; set; }
    public int? LicenseTypeId { get; set; }
    public bool Valid { get; set; }
}

public class LicenseType
{
    public int Id { get; set; }
    public string Name { get; set; }
    public List<LicenseTransfer> LicenseTransfers { get; set; }
}
```
Using RTM release, 
It throws `InvalidCastException` while projecting out 2 `Name` properties.
If only `Id` & 1 `Name` is projected out then it gives incorrect results as per #6360.

Both the cases are generating correct results with nightly builds.
Our nightly builds are at https://dotnet.myget.org/Gallery/aspnetcore-ci-dev
Include above feed in nuget.config and then restore packages.
Nightly packages are versioned `1.1.0-*`

Alternatively, you can modify above code to reflect the behavior you are seeing.

**Comment by jsgoupil** [comment] 2016-09-08 16:25
@smitpatel Thank you for checking. I was trying to install 1.1.0-alpha1-22093 but I get infinite amount of dependency warnings. It tells me it reverted to 1.0.0. Not sure how to get this fixed easily so I will take your word for it.

I was getting the same errors as you mentioned.

**Closed** 2016-09-14 18:31 UTC
Labels: closed-fixed, type-investigation
