### ISSUE TITLE
EFCore 1.1 doesn't use an existing property for the FK if it's part of the primary key

### ISSUE THREAD

**Issue by gius** [aspnet/EntityFramework#7127] opened 2016-11-25 13:23 UTC
The problem occurs in much complicated entities setup but I have isolated the problem to the following.

### Steps to reproduce
Have entity whose primary key is also a reference:

```
public class OrderDetail
{
  public int OrderID { get; set; }
  public Order Order { get; set; }
  ...
}
```

```
// in DbContext.OnModelCreating

modelBuilder.Entity<OrderDetail>().HasKey(x => x.OrderID);
```

### The issue
Versions prior to EFCore version 1.1 created both, primary key as well as foreign key, all worked properly. After updating to version 1.1, SQL generated by EF is wrong - it expects a new column OrderID1.

Obviously the model is wrong - when adding a new migration (before the EF update, this migration would be empty), the migration tries to drop foreign key "FK_OrderDetail_Order_OrderID", drop index "IX_OrderDetail_OrderID", alter column "OrderID" to make it "SqlServerValueGenerationStrategy.IdentityColumn", add new column "OrderID1" (nullable), and create index and foreign key for the new column "OrderID1".

Note that the reference from OrderDetail to Order tables is not explicitly described, can be only inferred from OrderID and Order properties.

Is this expected?

### Further technical details

EF Core version: 1.1.0
Operating system: Windows 10
Visual Studio version: VS 2015

### Update 1
I've tried to explicitly set the reference as follows:
```
// in DbContext.OnModelCreating
modelBuilder.Entity<OrderDetail>().HasKey(x => x.OrderID);
modelBuilder.Entity<OrderDetail>().HasOne(x => x.Order).WithOne();
```
And it did not help. However, changing the order of the lines seems to have solved the problem:
```
// in DbContext.OnModelCreating
modelBuilder.Entity<OrderDetail>().HasOne(x => x.Order).WithOne();
modelBuilder.Entity<OrderDetail>().HasKey(x => x.OrderID);
```

### Update 2
It also seems that many of implicit indexes on foreign keys have been removed but explicit call to `.HasIndex` fixes this. Especially indexes on primary keys that are also foreign keys and indexes on the first column of composed primary keys.

**Comment by AndriySvyryd** [comment] 2016-12-08 19:36
@gius Could you provide a complete model and context? I am not able to repro the issue with just the above code.
Note that indexes being removed on the primary key is by design - they are redundant.

**Comment by AndriySvyryd** [comment] 2016-12-08 20:03
@gius Nevermind, I found the issue. It is still by design that EF doesn't use `OrderID` if the relationship haven't been specified because you only have one navigation property, so the relationship might be one-to-many. However adding
```
modelBuilder.Entity<OrderDetail>().HasOne(x => x.Order).WithOne();
```
should be enough, independently of the order.

**Comment by AndriySvyryd** [comment] 2016-12-08 21:27
Fixed in 16eb5b3

**Comment by Eilon** [comment] 2017-01-19 19:55
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.

**Closed** 2017-01-19 20:16 UTC
Labels: closed-fixed, patch-approved, type-bug

**Comment by anpete** [comment] 2017-02-23 23:32
✅ Verified
