### ISSUE TITLE
Entity Framework Memory Management

### ISSUE THREAD

**Issue by robbpriestley** [aspnet/EntityFramework#5473] opened 2016-05-23 20:18 UTC
This isn't so much of an issue as it is a request for information. I'm pretty new to EF, let alone EF Core so sorry if what I need is just plain obvious. But I do need a bit of help because either the documentation isn't complete or I'm not finding it on my own, despite my efforts.

I built a little logging routine that uses EF to publish log entries to my database. Sort of like this, called from a repository class:

```
WebLog log = new WebLog(source, path, message);
Context.WebLogs.Add(log);
Context.SaveChanges();
```
Where WebLog is a simple model class, Context.WebLogs is a DbSet<WebLog> collection, and Context is obviously the DbContext. I believe this is quite straightforward.

But my question is this: if I continue to add new log entries to the Context.WebLogs collection and I never do anything like reboot my server, isn't the collection just going to grow without bounds? Is there some kind of "purge" or "flush" action I can take periodically to manage memory usage (without affecting the committed rows in the database, of course--I want those to persist). Or is DbSet some sort of a special collection that won't do this?

This is is basically a cross-post with the original here: [http://stackoverflow.com/questions/37357018/entity-framework-memory-management-and-dispose](http://stackoverflow.com/questions/37357018/entity-framework-memory-management-and-dispose) and one gentleman commented saying:

> the action you are looking for is just detaching all entities that are in an Unchanged State

If this is the case, how do I do it? If it isn't, what do I do?

**Comment by divega** [comment] 2016-05-23 21:08
@robbpriestley in the comment you got in stackoverfow.com it also says:

> which is one of the reasons the context (entry) lifetime should be limited

That is actually the right way to think about it: We recommend that you limit the lifetime of the instances of the `DbContext` itself, e.g. in a Web application you typically use a `DbContext` instance per request. The closes thing to a "flush" operation is `SaveChanges()` that method will not try to remove references to tracked entities, as `DbContext` is designed to be reused after `SaveChanges()`.  

In previous versions of EF we had a `Detach()` API that you could use to get rid of an individual tracked reference but we don't have that API in `DbContext` or in general in EF Core.

BTW, having an instance that is shared between multiple requests is extremely problematic because `DbContext` is not thread safe.

**Comment by robbpriestley** [comment] 2016-05-23 21:21
@divega OK, in that case I should be good. But first, I feel like you actually meant "`DbContext` is **not** designed to be reused after `SaveChanges()`." Right? Because if a DbContext is transient and `SaveChanges()` occurs as a last step before the context disappears, why would you bother trying to remove references to tracked entities?

**Comment by divega** [comment] 2016-05-23 21:36
I meant to say what I said :smile: Although it is not the most common thing to do, you can call `SaveChanges()` multiple times in the same `DbContext` instance.

**Comment by robbpriestley** [comment] 2016-05-23 21:55
Sorry, my bad. I'm learning. :grin: 

Bear with me here if you can for a second and I'll also demonstrate my lack of expertise with ASP.NET MVC. In my ASP.NET Core project, I have a controller which responds to web requests (REST). That controller accepts an `IWebLogRepository` by DI, and the implementing `WebLogRepository` accepts a `DbContext` instance by DI. In the `DbContext` is a `DbSet<WebLog>`.

Does it sound like I have my design pattern OK (I followed the tutorials) such that, as you say, the lifetime of the DbContext instance is limited?

**Comment by djechelon** [comment] 2016-05-25 15:42
Hi,

I'd like to join the discussion as I am very interested in using EF7 for large-data management (not as large as `Big Data&trade;`).

In my everyday programming I often face a common pattern: inserting/manipulating 100k records without blowing up the application memory.

Apart the cases when I can successfully split the insert operation into multithread chunks of 500 elements each, I might need to do the operation from a single thread.

Using Hibernate/Nhibernate, a common pattern is:

```
int counter = 0;
foreach (var entity in list) {
    if (counter++ % 500 == 0) {
        session.Flush();
        session.Clear();
    }
    DoSomething(entity);
}
```
The above code assures that entities already processed and saved to DB will get garbage-collected as no session references them. I write such similar code daily with the amount of data we work with (and again, often I can do multithreaded inserts, but those are another story).

EF context is similar to NH session by design, as they implement the unit-of-work pattern.

Also [there are](https://stackoverflow.com/questions/27423059/how-do-i-clear-tracked-entities-in-entity-framework) [multiple](https://stackoverflow.com/questions/5599147/how-do-i-detach-objects-in-entity-framework-code-first) ways to detach entities from the context.

# Summarizing
It would be great to have an EF7 API that clears tracked entities from the context, to be used after flushing the context with `SaveOrUpdate`.

That was my 50 cents, please feel free to share ideas

**Comment by rowanmiller** [comment] 2016-05-27 16:12
@djechelon rather than flushing the existing context could you not just create a new context? This is likely going to give you better performance since detaching entities is an operation that takes time. We highly optimize the context creation code path.

**Comment by divega** [comment] 2016-05-27 16:32
> We highly optimize the context creation code path.

E.g. things that are expensive to compute but are not directly tied to a specific `DbContext` instance,  such as mappings, query translations and result materializers are computed once and cached outside the context so they can be shared with any subsequent instances.

**Comment by divega** [comment] 2016-05-27 16:48
@robbpriestley 

> Does it sound like I have my design pattern OK...? 

It sounds ok, as long as `WebLogRepository` is registered as a scoped service, so that its lifetime is also tied to the request.

**Comment by divega** [comment] 2016-05-27 16:51
Closing as I believe we have answered all questions. Feel free to create a new issue if you find any issues,  or to respond to this thread if something isn't clear in our answers.

**Closed by divega** 2016-05-27 16:51 UTC
Labels: investigation-needed, pri0

**Comment by robbpriestley** [comment] 2016-05-27 16:53
@divega yes, thanks, I believe it is. In `Startup.ConfigureServices(...)` I have `services.AddScoped<IWebLogRepository, WebLogRepository>();`

**Comment by afshan3** [comment] 2017-08-04 19:29
Hi,

I am facing an issue in my web API. I have added dbcontext inside UnitOfWork by AddScopped to the service. but I am doing multiple savechanges in UnitOfWork from multiple controllers, which causes an error bcs of 'disposed dbcontext'. It seems that after first _dbcontext.savechanges , _dbcontext.model & _dbcontext.Changetracker are being disposed.

**Comment by ajcvickers** [comment] 2017-08-15 23:34
@afshan3 This issue is closed and doesn't appear to be directly related to your question. Can you please file a new issue with full details of the versions you are using and the steps needed to reproduce the issue. Thanks!
