### ISSUE TITLE
The last removed migration name cannot be reused

### ISSUE THREAD

**Issue by rmja** [aspnet/EntityFramework#5066] opened 2016-04-14 08:05 UTC
rc2 latest dev bits

The following migration sequence does not work:
```
dotnet ef migrations add Initial
dotnet ef migrations remove
dotnet ef migrations add Initial
```

The last line throws:

> System.InvalidOperationException: The name 'Initial' is used by an existing migration.
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The name 'Initial' is used by an existing migration.

I can mitigate the problem by making any change in one of the project files, which causes the project to be rebuild, right before the second `dotnet ef migrations add Initial` call.

Btw. the following sequence does work:
```
dotnet ef migrations add Initial
dotnet ef migrations add SecondMigration
dotnet ef migrations remove
dotnet ef migrations add SecondMigration
```

**Comment by natemcmaster** [comment] 2016-04-18 18:34
@rmja what happens if you build after removing?
```
dotnet ef migrations add Initial
dotnet ef migrations remove
dotnet build
dotnet ef migrations add Initial
```

**Comment by rmja** [comment] 2016-04-18 19:06
@natemcmaster that works. That is what the "changing any file" implicitly means☺

**Comment by natemcmaster** [comment] 2016-04-18 20:53
The source of the issue is dotnet-build. This is a duplicate of https://github.com/dotnet/cli/issues/1440. I'll leave this open to track on our side.

**Comment by natemcmaster** [comment] 2016-04-26 00:22
Fixed by https://github.com/dotnet/cli/pull/2619

**Closed by natemcmaster** 2016-04-26 00:22 UTC
