### ISSUE TITLE
"Done" message was shown when running dotnet ef migrations script

### ISSUE THREAD

**Issue by bruceyclee** [aspnet/EntityFramework#5012] opened 2016-04-08 17:00 UTC
I'm working on ef migrations in web tool side. I use dotnet ef migrations script to generate T-SQL file of migrations. When this command is done, it will show a "Done" on screen, whose the code is from src/dotnet-ef/MigrationsScriptCommand.cs  (line 74 Reporter.Error.WriteLine("Done");) . This "Done" should not be handled by "Reporter.Error".

When I run the whole thing by msbuild tasks, the "Done" will be captured by msbuild.exe and it was recognized an error message. This makes people think this command has a problem and actually it is not. 

Is there an option not showing "Done" on screen or some other approach to skip "Done" ?

**Comment by natemcmaster** [comment] 2016-04-14 01:12
Fixed via #5020. More work on how we log needs to be done. See #4771

**Comment by smitpatel** [comment] 2016-04-29 19:55
I am using `Entity Framework .NET Core CLI Commands 1.0.0-rc3-20747` and still hitting this issue. 
```
dotnet : Done. To undo this action, use 'ef migrations remove'
At line:1 char:1
+ dotnet ef migrations add Init
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Done. To undo t...rations remove':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Comment by smitpatel** [comment] 2016-04-29 20:07
not just for done for any other message also same error
```
dotnet : An operation was scaffolded that may result in the loss of data. Please review the migration for accuracy.
At line:1 char:1
+ dotnet ef migrations add StringLength
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (An operation wa...n for accuracy.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Done. To undo this action, use 'ef migrations remove'
```

**Comment by divega** [comment] 2016-04-29 23:28
Reopening for now based on @smitpatel's findings.

**Comment by natemcmaster** [comment] 2016-05-02 19:00
Possible duplicate of #4771

**Comment by smitpatel** [comment] 2016-05-02 19:01
I was using powershell.

**Comment by natemcmaster** [comment] 2016-05-26 21:54
I've proposed 2 changes in #5542 that will help with this and related scripting errors:

1. dotnet ef will only use stderr for actual error messages. 
2. Commands with json output `--json` will now also have `--json-delimited`. This will additionally spit out '//BEGIN' and '//END' for those so those building scripting on top of ef commands and who need to ensure they get only JSON as they parse its output.

cc @mlorbetske

**Closed** 2016-05-27 20:54 UTC
Labels: bug, design-time, pri0
