### ISSUE TITLE
Adding nested child entities with server side identity key results stores everythin but with completely wrong mapping in database

### ISSUE THREAD

**Issue by fduerrbaum** [aspnet/EntityFramework#4396] opened 2016-01-25 23:19 UTC
http://stackoverflow.com/questions/34999455/entity-framework-7-rc1-adding-nested-child-entities-results-to-wrong-mapping

Seem's really to be a bug. I did some testing with and without (sql) server side generated primary keys and different configurations. Strangely the issue only occures when adding "more than a few entities" and the returned entity references have the correct mapping, while they are stored wrong in the database.

**Comment by rowanmiller** [comment] 2016-02-12 23:07
Confirmed issue, here is a simplified repro:

```c#
using Microsoft.Data.Entity;
using System.Collections.Generic;
using System;

namespace Repro
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (TestContext dbContext = new TestContext())
            {
                dbContext.Database.EnsureDeleted();
                dbContext.Database.EnsureCreated();

                for (int o = 0; o < 40; o++)
                {
                    var order = new Order
                    {
                        Name = $"Order {o}",
                        OrderItems = new List<OrderItem>()
                    };

                    for (int i = 0; i < 10; i++)
                    {
                        order.OrderItems.Add(new OrderItem
                        {
                            Name = $"Order {o} | Item {i}",
                            OrderPricing = new List<OrderPricing>
                            {
                                new OrderPricing { Name =  $"Order {o} | Item {i} | Pricing 1"}
                            }
                        });
                    }

                    dbContext.Add(order);
                }

                dbContext.SaveChanges();
            }

            using (TestContext dbContext = new TestContext())
            {
                foreach (var order in dbContext.Orders.Include(o => o.OrderItems).ThenInclude(i => i.OrderPricing))
                {
                    Console.WriteLine($"{order.Name}");
                    foreach (var item in order.OrderItems)
                    {
                        Console.WriteLine($" - {item.Name}");
                        foreach (var pricing in item.OrderPricing)
                        {
                            Console.WriteLine($"    * {pricing.Name}");
                        }
                    }
                }
            }
        }
    }

    public partial class TestContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder options)
        {
            options.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Sample;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<OrderPricing>()
                .HasKey(p => p.OrderItemId);
        }

        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<OrderPricing> OrderPricing { get; set; }
    }

    public partial class Order
    {
        public int OrderId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }

    public partial class OrderItem
    {
        public int OrderItemId { get; set; }
        public string Name { get; set; }
        public int OrderId { get; set; }

        public virtual ICollection<OrderPricing> OrderPricing { get; set; }
        public virtual Order Order { get; set; }
    }

    public partial class OrderPricing
    {
        public int OrderItemId { get; set; }
        public string Name { get; set; }

        public virtual OrderItem OrderItem { get; set; }
    }
}
```

You would expect output like the following (and that is what you get if you reduce the outer for loop to `10`).

```
Order 0
 - Order 0 | Item 0
    * Order 0 | Item 0 | Pricing 1
 - Order 0 | Item 9
    * Order 0 | Item 9 | Pricing 1
 - Order 0 | Item 8
    * Order 0 | Item 8 | Pricing 1
 - Order 0 | Item 7
    * Order 0 | Item 7 | Pricing 1
 - Order 0 | Item 6
    * Order 0 | Item 6 | Pricing 1
 - Order 0 | Item 5
    * Order 0 | Item 5 | Pricing 1
 - Order 0 | Item 4
    * Order 0 | Item 4 | Pricing 1
 - Order 0 | Item 3
    * Order 0 | Item 3 | Pricing 1
 - Order 0 | Item 2
    * Order 0 | Item 2 | Pricing 1
 - Order 0 | Item 1
    * Order 0 | Item 1 | Pricing 1
```

However, with the outer for loop at `40`, you get the following:

```c#
Order 0
 - Order 0 | Item 0
    * Order 0 | Item 0 | Pricing 1
 - Order 0 | Item 9
    * Order 27 | Item 2 | Pricing 1
 - Order 0 | Item 8
    * Order 27 | Item 1 | Pricing 1
 - Order 0 | Item 7
    * Order 27 | Item 0 | Pricing 1
 - Order 0 | Item 6
    * Order 26 | Item 9 | Pricing 1
 - Order 0 | Item 5
    * Order 26 | Item 8 | Pricing 1
 - Order 0 | Item 4
    * Order 26 | Item 7 | Pricing 1
 - Order 0 | Item 3
    * Order 26 | Item 6 | Pricing 1
 - Order 0 | Item 2
    * Order 26 | Item 5 | Pricing 1
 - Order 0 | Item 1
    * Order 26 | Item 4 | Pricing 1
```

**Comment by rowanmiller** [comment] 2016-02-12 23:08
BTW I thought maybe this was because `OrderPricing.OrderItemId` was being setup as generated, but confirmed that is not the case.

**Comment by rowanmiller** [comment] 2016-02-12 23:11
And fortunately, this is already fixed in the RC2 code base :smile:

**Closed by rowanmiller** 2016-02-12 23:11 UTC
