### ISSUE TITLE
Mismatched property types used in a relationship

### ISSUE THREAD

**Issue by markolbert** [aspnet/EntityFramework#6260] opened 2016-08-07 16:28 UTC
I noticed this using v1.0.0

If you specify a many to many relationship between three classes and the property types don't match:

```
public class Class1
{
    public int ID { get; set; }
}

public class Class2
{
    public int ID { get; set; }
}
public class Class2
{
    public string Class1ID { get; set; }
    public int Class2ID { get; set; }
}

// relationship defined in OnModelCreating
```

you'll get a rather obscure error message referencing shadow properties, when the problem is really that the property types don't match.

It would be nice if the code building the relationship noted that the types don't match.

**Comment by divega** [comment] 2016-08-08 18:40
There is a dupe assigned to @rowanmiller but @AndriySvyryd will go ahead a send a PR.

**Comment by AndriySvyryd** [comment] 2016-08-08 20:00
Dupe of #5655

**Closed** 2016-08-18 04:57 UTC
Labels: patch-approved, type-bug
