### ISSUE TITLE
SqlServer: Error when applying a second migration - Issue with default values on bit columns

### ISSUE THREAD

**Issue by ChristineBoersen** [aspnet/EntityFramework#2802] opened 2015-08-09 10:14 UTC
There's 2 bugs going on here...

Given that I have
-- done an initial migration
-- applied the migration to the database
-- That I have made no code changes between the initial and second migration creation, hence I should have ZERO changes to apply (bug 1)
-- Have made a second migration
-- Attempted to apply it.(bug 2)

At this point, the update fails on all of the bit columns in the database (that are defined initially with a DEFAULT value and again no schema changes were made in the code first so there was no reason to generate the statement)

I receive the following error
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'DEFAULT'.

Looking at the .cs file created by the second migration an example column is defined this way

     migration.AlterColumn(
                name: "Active",
                table: "ClueRelationTypes",
                type: "bit",
                nullable: false,
                defaultValue: true);

If I output the scripts, for the same column, I see this

     ALTER TABLE [ClueRelationTypes] ALTER COLUMN [Active] bit NOT NULL DEFAULT 1;

SqlServer doesn't allow specifying a default value in an ALTER TABLE statement, so hence it fails.

Let me know if you need any further information to reproduce the two issues.

Christine

**Comment by ChristineBoersen** [comment] 2015-08-09 10:21
Also the same migration.AlterColumn statement (bug 3) is listed identically in both the UP and DOWN portion of the second migration as well.

**Comment by ChristineBoersen** [comment] 2015-08-09 10:39
OK looking at some of the latest checkins, this may be resolved with Fixes #1345

**Comment by bricelam** [comment] 2015-08-10 16:32
Yes, "bug 2" should be fixed by #1345. Bugs 1 & 3 most likely have the same root cause. Could you share your model (DbContext and entity type classes)?

**Comment by ChristineBoersen** [comment] 2015-08-14 16:32
Note, when originally tested I had the DBSet and the ClueRelationType_CreateObject code *in* the Context as most examples show. I reorganized that code for unrelated reasons which had no effect on the bugs reported.

For the context

    public class ApplicationUser : IdentityUser
    {

    }

    public partial class ClueContext : IdentityDbContext<ApplicationUser>
    {

        protected ModelBuilder _ModelBuilder { get; set; }
      
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            _ModelBuilder = modelBuilder;
            
      
            ClueRelationTypes_CreateObject();
      


            base.OnModelCreating(modelBuilder);


        }
    }



And for the Entity

    public class ClueRelationTypes
    {
        public ClueRelationTypes()
        {
            ClueObjectRelation = new HashSet<ClueObjectRelation>();
        }

        public Guid RelationTypeID { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public bool UsesDateRange { get; set; }        
        
        public string Value1Name { get; set; }
        public string Value2Name { get; set; }
        public string Value3Name { get; set; }
        public string Value4Name { get; set; }
        public string Value5Name { get; set; }
        public string Value6Name { get; set; }
        public string Value7Name { get; set; }
        public string Value8Name { get; set; }
        public string Value9Name { get; set; }
        public string Value10Name { get; set; }

        public bool System { get; set; }
        public bool Active { get; set; }

        public virtual ICollection<ClueObjectRelation> ClueObjectRelation { get; set; }
    }

    public partial class ClueContext : IdentityDbContext<ApplicationUser>
    {

        public virtual DbSet<ClueRelationTypes> ClueRelationTypes { get; set; }

        protected void ClueRelationTypes_CreateObject()
        {

            _ModelBuilder.Entity<ClueRelationTypes>(entity =>
            {
                entity.Key(e => e.RelationTypeID);

                entity.Property(e => e.RelationTypeID).DefaultValueSql("newid()");

                entity.Property(e => e.UsesDateRange).Required();

                entity.Property(e => e.System)
                    .Required()
                    .DefaultValue(false);

                entity.Property(e => e.Active)
                  .Required()
                  .DefaultValue(true);



            });


        }

    }

**Closed** 2015-08-18 15:59 UTC
Labels: 2 - Done, bug, pri0
